/**
 * Keywords database for biocide-oil-gas.
 * Generated automatically.
 */

export const BIOCIDE_OIL_GAS_BUYING_INTENT: string[] = [
  "buy oil and gas biocide",
  "oilfield biocide price india",
  "oil and gas biocide manufacturer",
  "wholesale oilfield biocide exporter",
  "water injection biocide quote",
  "purchase srb control chemical",
  "bulk oilfield biocide supplier",
  "triazine oilfield biocide price",
  "industrial oilfield biocide buy online",
  "best price for oilfield biocide",
  "oilfield biocide for sale india",
  "top oilfield biocide manufacturers india",
  "export oilfield biocide to middle east",
  "oilfield biocide drum price",
  "ibc tank oilfield biocide price",
  "oilfield biocide chemical supply",
  "pipeline biocide buy",
  "produced water biocide price",
  "oilfield biocide procurement india",
  "reliable oilfield biocide supplier",
  "oilfield biocide fcl price",
  "oilfield biocide cnf price",
  "oilfield biocide fob mundra",
  "oilfield biocide lcl shipping",
  "oilfield biocide volume discount",
  "cheap oilfield biocide chemical",
  "high purity oilfield biocide buy",
  "oilfield biocide global exporter",
  "oilfield biocide technical grade price",
  "oilfield grade biocide price",
  "oilfield biocide contract manufacturing",
  "oilfield biocide white label supply",
  "oilfield biocide private label chemical",
  "oilfield biocide tender price",
  "oilfield biocide govt supplier india",
  "oilfield biocide msme manufacturer",
  "oilfield biocide iso tank price",
  "oilfield biocide bulk container price",
  "oilfield biocide 210l drum price",
  "oilfield biocide 1mt ibc price",
  "oilfield biocide sample request",
  "order oilfield biocide online",
  "oilfield biocide express delivery",
  "oilfield biocide stock availability",
  "oilfield biocide ready to ship",
  "oilfield biocide factory direct price",
  "oilfield biocide b2b supplier",
  "oilfield biocide indiamart price",
  "oilfield biocide alibaba supplier",
  "oilfield biocide tradewheel exporter",
  "oilfield biocide chemicals for pipelines",
  "oilfield biocide injection chemicals buy",
  "oilfield biocide hydrotest chemicals price",
  "oilfield biocide offshore chemicals buy",
  "oilfield biocide onshore chemicals price",
  "oilfield biocide drilling biocides buy",
  "oilfield biocide completion biocides price",
  "oilfield biocide production biocides supplier",
  "oilfield biocide chemical quote request",
  "get price list oilfield biocide",
  "oilfield biocide latest price 2026",
  "oilfield biocide market price india",
  "oilfield biocide chemical trading",
  "oilfield biocide distributor uae",
  "oilfield biocide distributor usa",
  "oilfield biocide distributor russia",
  "oilfield biocide distributor vietnam",
  "oilfield biocide distributor brazil",
  "oilfield biocide distributor egypt",
  "oilfield biocide distributor saudi arabia",
  "oilfield biocide distributor iraq",
  "oilfield biocide distributor oman",
  "oilfield biocide distributor qatar",
  "oilfield biocide distributor kuwait",
  "oilfield biocide distributor libya",
  "oilfield biocide distributor thailand",
  "oilfield biocide distributor turkey",
  "oilfield biocide distributor kazakhstan",
  "oilfield biocide distributor nigeria",
  "oilfield biocide distributor angola",
  "oilfield biocide agent in india",
  "oilfield biocide commission agent",
  "oilfield biocide chemical brokerage",
  "oilfield biocide chemical indenting",
  "oilfield biocide sourcing agent india",
  "oilfield biocide procurement services",
  "oilfield biocide chemical logistics",
  "oilfield biocide chemical storage price",
  "oilfield biocide chemical handling costs",
  "oilfield biocide chemical disposal price",
  "oilfield biocide hazardous waste price",
  "oilfield biocide chemical safety audit price",
  "oilfield biocide chemical training price",
  "oilfield biocide chemical consulting price",
  "oilfield biocide chemical analysis price",
  "oilfield biocide chemical testing price",
  "oilfield biocide quality control price",
  "oilfield biocide coa verification price",
  "oilfield biocide sds preparation price",
  "oilfield biocide reach registration price",
  "oilfield biocide tsca compliance price",
  "oilfield biocide biocide registration price",
];

export const BIOCIDE_OIL_GAS_RESEARCH_BASED: string[] = [
  "what is oilfield biocide",
  "how oilfield biocide works",
  "triazine biocide for oil and gas",
  "oilfield biocide chemical formula",
  "oilfield biocide cas number",
  "oilfield biocide msds",
  "oilfield biocide solubility in brine",
  "oilfield biocide solubility in produced water",
  "oilfield biocide ph range",
  "oilfield biocide specific gravity",
  "oilfield biocide flash point",
  "oilfield biocide boiling point",
  "oilfield biocide freezing point",
  "oilfield biocide viscosity",
  "oilfield biocide shelf life",
  "oilfield biocide compatibility with polymers",
  "oilfield biocide compatibility with scale inhibitors",
  "oilfield biocide corrosion prevention srb",
  "oilfield biocide srb control mechanism",
  "oilfield biocide microbial influenced corrosion inhibitor",
  "oilfield biocide sulfate reducing bacteria control",
  "oilfield biocide acid producing bacteria control",
  "oilfield biocide general aerobic bacteria control",
  "oilfield biocide iron oxidizing bacteria control",
  "oilfield biocide ghs classification",
  "oilfield biocide safety precautions",
  "oilfield biocide handling guide",
  "oilfield biocide storage recommendations",
  "oilfield biocide accidental spill response",
  "oilfield biocide ppe requirements",
  "oilfield biocide stability data",
  "oilfield biocide reactivity information",
  "oilfield biocide disposal methods",
  "oilfield biocide transport regulations",
  "oilfield biocide regulatory compliance",
  "oilfield biocide use in water injection",
  "oilfield biocide use in fracturing fluids",
  "oilfield biocide use in hydrostatic testing",
  "oilfield biocide use in pipeline preservation",
  "oilfield biocide use in storage tank bottoms",
  "oilfield biocide dosage calculator",
  "oilfield biocide kill rate studies",
  "oilfield biocide persistence in reservoirs",
  "oilfield biocide formaldehyde release mechanism",
  "oilfield biocide vs quaternary ammonium biocides",
  "oilfield biocide vs glutaraldehyde oilfield",
  "oilfield biocide vs thps biocide",
  "oilfield biocide vs dbnpa biocide",
  "oilfield biocide vs isothiazolinone oilfield",
  "oilfield biocide advantages and disadvantages",
  "oilfield biocide case studies offshore",
  "oilfield biocide technical white paper",
  "oilfield biocide industrial application review",
  "oilfield biocide latest research 2026",
  "oilfield biocide innovation in microbial control",
  "oilfield biocide sustainable oilfield chemicals",
  "oilfield biocide carbon footprint analysis",
  "oilfield biocide circular economy oilfield",
  "oilfield biocide waste optimization oilfield",
  "oilfield biocide molecular structure triazine",
  "oilfield biocide chemical synonyms triazine",
  "oilfield biocide popular trade names triazine",
  "oilfield biocide manufacturers list india triazine",
  "oilfield biocide global market trends oilfield",
  "oilfield biocide demand forecast 2030",
  "oilfield biocide supply chain logistics",
  "oilfield biocide manufacturing process triazine",
  "oilfield biocide factory setup cost india",
  "oilfield biocide raw material sourcing triazine",
  "oilfield biocide production optimization triazine",
  "oilfield biocide quality standards list triazine",
  "oilfield biocide iso 9001 requirements triazine",
  "oilfield biocide astm test methods produced water",
  "oilfield biocide nace microbial standards",
  "oilfield biocide api chemical standards oilfield",
  "oilfield biocide environmental impact assessment",
  "oilfield biocide safety training for oilfield workers",
  "oilfield biocide emergency response oilfield",
  "oilfield biocide risk mitigation pipeline",
  "oilfield biocide hazop study oilfield plant",
  "oilfield biocide chemical data sheets triazine",
  "oilfield biocide thermodynamic properties triazine",
  "oilfield biocide kinetic modeling biocide",
  "oilfield biocide solubility in high salinity water",
  "oilfield biocide partition coefficient oil water",
  "oilfield biocide surface tension properties oilfield",
  "oilfield biocide foaming tendency oilfield",
  "oilfield biocide emulsion stability effects oilfield",
  "oilfield biocide impact on produced water treatment",
  "oilfield biocide impact on biological oxygen demand",
  "oilfield biocide synergistic effect with scavengers",
  "oilfield biocide synergistic effect with inhibitors",
  "oilfield biocide interaction matrix oilfield chemicals",
];

export const BIOCIDE_OIL_GAS_PRIMARY_KEYWORD: string = "oil and gas biocide manufacturer india";

export const BIOCIDE_OIL_GAS_LONG_TAIL_KEYWORDS: string[] = [
  "oilfield water injection biocide",
  "srb control chemicals oilfield",
  "pipeline biocide supplier india",
  "microbial influenced corrosion inhibitor",
  "hydrostatic test biocide supplier",
  "produced water biocide manufacturer",
];
