export const BIT_20_BUYING_INTENT_EXTRA: string[] = [
  // ── State-level India buying intent (not covered by the existing city list) ──
  "bit 20 supplier in tamil nadu",
  "bit 20 supplier in maharashtra",
  "bit 20 supplier in karnataka",
  "bit 20 supplier in andhra pradesh",
  "bit 20 supplier in telangana",
  "bit 20 supplier in punjab",
  "bit 20 supplier in haryana",
  "bit 20 supplier in west bengal",
  "bit 20 supplier in madhya pradesh",
  "bit 20 supplier in rajasthan",
  "bit 20 supplier in uttar pradesh",
  "benzisothiazolinone manufacturer in gujarat gidc",
  "benzisothiazolinone manufacturer in dahej",
  "benzisothiazolinone manufacturer in panoli",
  "benzisothiazolinone manufacturer in jhagadia",
  "benzisothiazolinone manufacturer in valsad",
  "benzisothiazolinone manufacturer in silvassa",
  "benzisothiazolinone manufacturer in daman",
  // ── Buyer-role / procurement-title phrasing ───────────────
  "bit 20 supplier for procurement manager",
  "bit 20 vendor registration india",
  "bit 20 vendor onboarding process",
  "bit 20 approved vendor list india",
  "bit 20 new vendor development",
  "bit 20 supplier evaluation checklist",
  "bit 20 supplier audit requirements",
  "bit 20 rfq template",
  "bit 20 rfq submission india",
  "request for proposal bit 20 supplier",
  "bit 20 supplier for r&d lab",
  "bit 20 lab scale sample for r&d",
  "bit 20 pilot batch quantity",
  "bit 20 trial order quantity",
  "bit 20 qc approved batch supplier",
  "bit 20 supplier with material test certificate",
  // ── Payment / commercial terms ─────────────────────────────
  "bit 20 supplier accepting lc payment",
  "bit 20 supplier advance payment terms",
  "bit 20 supplier credit terms india",
  "bit 20 payment against delivery",
  "bit 20 supplier net 30 terms",
  "bit 20 supplier net 60 terms",
  "bit 20 supplier flexible payment options",
  "bit 20 price negotiation bulk order",
  "bit 20 annual rate contract supplier",
  "bit 20 long term supply agreement",
  "bit 20 supplier for repeat orders",
  // ── Incoterm x pack-size combinations (not already covered) ──
  "bit 20 exw price india",
  "bit 20 fca price india",
  "bit 20 ddp price europe",
  "bit 20 ddp price usa",
  "bit 20 cif price dubai",
  "bit 20 cif price rotterdam",
  "bit 20 fob price nhava sheva",
  "bit 20 fob price mundra port",
  "bit 20 20ft container price",
  "bit 20 40ft container price",
  "bit 20 flexitank price",
  "bit 20 iso tank container price",
  // ── WhatsApp / call-first B2B search patterns (common in Indian chem trade) ──
  "bit 20 supplier whatsapp number",
  "bit 20 supplier contact number india",
  "bit 20 manufacturer phone number",
  "bit 20 supplier email id",
  "bit 20 supplier direct contact",
  "bit 20 factory visit request",
  "bit 20 supplier company profile",
  "bit 20 supplier gst number verification",
  "bit 20 supplier company registration details",
  // ── Additional trade-name / brand purchase intent ──────────
  "buy 1,2-benzisothiazolin-3-one bulk",
  "benzisothiazolinone 20 solution buy",
  "benzisothiazolinone aqueous solution price",
  "benzisothiazolinone dipropylene glycol solution price",
  "bit 20 dpg solution supplier",
  "bit 20 water based solution price",
  "bit in dpg carrier price",
  "isothiazolinone biocide bit type buy india",
  // ── Application-specific buying (new sectors) ─────────────
  "bit 20 for silicone sealants buy",
  "bit 20 for grouts and mortars price",
  "bit 20 for latex gloves manufacturing buy",
  "bit 20 for polymer emulsion buy",
  "bit 20 for starch based adhesive buy",
  "bit 20 for wallpaper paste price",
  "bit 20 for car wash chemicals buy",
  "bit 20 for floor cleaner formulation buy",
  "bit 20 for dishwashing liquid price",
  "bit 20 for fabric conditioner buy",
  "bit 20 for hand sanitizer gel formulation",
  "bit 20 for shoe polish preservative buy",
  // ── Comparison-driven purchase intent ─────────────────────
  "cheapest bit 20 alternative supplier",
  "bit 20 vs bit 85 which to buy",
  "best value bit 20 supplier india",
  "bit 20 supplier with fastest delivery",
  "bit 20 supplier for small batch buyers",
  "bit 20 supplier for large scale industrial buyers",
  "bit 20 supplier for private label cosmetics brand",
  "bit 20 supplier for paint contract manufacturer",
  "bit 20 supplier for adhesive contract manufacturer",
  "bit 20 supplier for detergent contract manufacturer",
];

export const BIT_20_RESEARCH_BASED_EXTRA: string[] = [
  // ── Analytical / QC method detail ─────────────────────────
  "benzisothiazolinone hplc analysis method",
  "benzisothiazolinone hplc mobile phase",
  "benzisothiazolinone gc-ms analysis",
  "benzisothiazolinone uv spectrophotometry method",
  "benzisothiazolinone titration method",
  "benzisothiazolinone karl fischer moisture test",
  "benzisothiazolinone assay by hplc percentage",
  "benzisothiazolinone identification test method",
  "benzisothiazolinone residual solvent testing",
  "benzisothiazolinone heavy metal testing method",
  "benzisothiazolinone microbiological testing method",
  "benzisothiazolinone reference standard supplier",
  "benzisothiazolinone certified reference material",
  "benzisothiazolinone impurity profile",
  "benzisothiazolinone related substances test",
  "benzisothiazolinone loss on drying test",
  "benzisothiazolinone ph meter calibration for testing",
  "benzisothiazolinone sample preparation for analysis",
  "benzisothiazolinone method validation parameters",
  "benzisothiazolinone limit of detection lod",
  "benzisothiazolinone limit of quantification loq",
  // ── Patent / literature / academic research ───────────────
  "benzisothiazolinone patent literature",
  "benzisothiazolinone synthesis patent",
  "benzisothiazolinone research paper",
  "benzisothiazolinone journal publication",
  "benzisothiazolinone pubmed studies",
  "benzisothiazolinone scientific literature review",
  "benzisothiazolinone academic research india",
  "benzisothiazolinone patent expiry status",
  "benzisothiazolinone process patent india",
  "benzisothiazolinone formulation patent examples",
  "benzisothiazolinone toxicology study reference",
  "benzisothiazolinone clinical dermatology study",
  "benzisothiazolinone environmental research study",
  "benzisothiazolinone thesis research topic",
  // ── Packaging material compatibility ──────────────────────
  "benzisothiazolinone compatibility with hdpe drum",
  "benzisothiazolinone compatibility with lined steel drum",
  "benzisothiazolinone compatibility with pp container",
  "benzisothiazolinone compatibility with glass bottle",
  "benzisothiazolinone compatibility with ibc liner material",
  "benzisothiazolinone corrosion effect on metal containers",
  "benzisothiazolinone packaging material recommendation",
  "benzisothiazolinone container headspace requirement",
  "benzisothiazolinone light sensitivity packaging",
  "benzisothiazolinone uv protection packaging need",
  "benzisothiazolinone temperature controlled storage requirement",
  "benzisothiazolinone freeze thaw stability",
  "benzisothiazolinone shelf storage temperature range",
  // ── Competitor product-code cross-reference research ──────
  "preventol bit 20 n technical data comparison",
  "nipacide bit 20 technical data comparison",
  "acticide bw20 vs bit 20 comparison",
  "proxel bd20 vs bit 20 comparison",
  "mergal bit20 technical specification comparison",
  "vinkocide bit 20 d technical specification",
  "kathon biocide vs bit 20 comparison",
  "rocima bt vs bit 20 comparison",
  "parmetol bit vs bit 20 comparison",
  "biochek bit vs bit 20 comparison",
  // ── Industry-specific regulatory phrasing (new sectors) ───
  "benzisothiazolinone regulation in agrochemical formulations",
  "benzisothiazolinone regulation in adhesive industry eu",
  "benzisothiazolinone regulation in printing ink industry",
  "benzisothiazolinone regulation for children's toys coatings",
  "benzisothiazolinone regulation in medical device coatings",
  "benzisothiazolinone regulation in food packaging adhesives",
  "benzisothiazolinone regulation in textile finishing india",
  "benzisothiazolinone regulation in leather export compliance",
  "benzisothiazolinone bis certification requirement india",
  "benzisothiazolinone cpcb norms india",
  "benzisothiazolinone pollution control board approval",
  "benzisothiazolinone factory license requirement india",
  "benzisothiazolinone hazardous chemical rules india",
  "benzisothiazolinone msihc rules classification india",
  // ── Formulation troubleshooting research ──────────────────
  "why is my paint failing preservative efficacy test",
  "why does my detergent smell bad after storage",
  "why does my adhesive show mold growth",
  "why is my metalworking fluid going rancid quickly",
  "how to troubleshoot preservative failure in paint",
  "how to troubleshoot biocide underperformance",
  "common reasons for preservative system failure",
  "how to re-preserve contaminated paint batch",
  "how to fix microbial contamination in bulk storage tank",
  "signs of inadequate preservation in water based products",
  "how to conduct root cause analysis for spoiled batch",
  "preservative boosting strategy for problem formulations",
  // ── Storage / handling deep-dive research ─────────────────
  "benzisothiazolinone recommended storage temperature",
  "benzisothiazolinone maximum storage duration",
  "benzisothiazolinone storage away from sunlight reason",
  "benzisothiazolinone storage humidity requirement",
  "benzisothiazolinone segregation from oxidizers",
  "benzisothiazolinone segregation from strong acids",
  "benzisothiazolinone segregation from strong bases",
  "benzisothiazolinone warehouse storage guideline",
  "benzisothiazolinone bulk tank storage material",
  "benzisothiazolinone drum storage stacking limit",
  // ── Market / trade data research ──────────────────────────
  "benzisothiazolinone india production capacity",
  "benzisothiazolinone india export volume data",
  "benzisothiazolinone india import dependency",
  "benzisothiazolinone asia pacific market share",
  "benzisothiazolinone europe market regulation impact",
  "benzisothiazolinone north america demand trend",
  "benzisothiazolinone price volatility factors",
  "benzisothiazolinone raw material supply chain risk",
  "benzisothiazolinone china plus one sourcing strategy",
  "benzisothiazolinone india plus one sourcing advantage",
  "benzisothiazolinone freight cost impact on pricing",
  "benzisothiazolinone crude oil price correlation",
  // ── Comparative chemistry deep-dive ────────────────────────
  "difference between bit and dbnpa mechanism",
  "difference between bit and glutaraldehyde mechanism",
  "difference between bit and octhilinone mechanism",
  "why is bit preferred over formaldehyde condensates",
  "why do formulators avoid parabens increasingly",
  "role of isothiazolinones in modern preservation systems",
  "history of isothiazolinone biocide development",
  "evolution of paint preservative technology",
  "regulatory history of formaldehyde donor biocides",
  // ── Sector deep-dive: additional industries ───────────────
  "benzisothiazolinone use in car wash soap industry",
  "benzisothiazolinone use in floor polish industry",
  "benzisothiazolinone use in fabric softener industry",
  "benzisothiazolinone use in dishwashing liquid industry",
  "benzisothiazolinone use in hand sanitizer gel industry",
  "benzisothiazolinone use in shoe care industry",
  "benzisothiazolinone use in latex glove manufacturing",
  "benzisothiazolinone use in silicone sealant industry",
  "benzisothiazolinone use in grout and mortar industry",
  "benzisothiazolinone use in wallpaper paste industry",
  // ── FAQ / natural-language extension ──────────────────────
  "is bit 20 the same everywhere or does purity vary",
  "how do i know if my bit 20 supplier is genuine",
  "what questions to ask a bit 20 supplier before buying",
  "what documents should a bit 20 supplier provide",
  "how to verify bit 20 coa authenticity",
  "how to check bit 20 quality before bulk order",
  "what is a reasonable lead time for bit 20 supply",
  "how many years should a bit 20 manufacturer be in business",
  "what makes an indian bit 20 manufacturer export ready",
  "how to compare two bit 20 supplier quotations",
  "what is the typical margin for bit 20 traders",
  "how does monsoon season affect bit 20 logistics in india",
  "what is the typical port turnaround time for bit 20 export",
  "how do currency fluctuations affect bit 20 import cost",
  "what insurance is needed for bit 20 bulk shipment",
  "how to classify bit 20 for dangerous goods shipping",
  "what is the un number for benzisothiazolinone shipment",
  "how to prepare export documentation for benzisothiazolinone",
  "what is a certificate of origin for benzisothiazolinone export",
  "how to get gsp certificate for benzisothiazolinone export",
  "what is the typical customs duty on benzisothiazolinone import",
  "how does free trade agreement affect benzisothiazolinone tariff",
  "what is the typical viscosity of bit 20 aqueous solution",
  "what is the specific gravity of bit 20 solution",
  "how to interpret a bit 20 certificate of analysis report",
];
