export const BIT_20_LONG_TAIL_EXTRA: string[] = [
  // ── Chemical identity + grade + use-case combinations ─────
  "benzisothiazolinone cas 2634-33-5 20 percent liquid preservative",
  "1,2-benzisothiazolin-3-one 20% aqueous solution for paints",
  "bit 20 formaldehyde free biocide for water based coatings",
  "bit 20 broad spectrum preservative for cosmetic formulations",
  "benzisothiazolinone 20% dpg carrier preservative for adhesives",
  "bit 20 in-can preservative for architectural emulsion paint",
  "benzisothiazolinone antimicrobial additive for detergent manufacturing",
  "bit 20 industrial biocide for metalworking fluid concentrate",
  "benzisothiazolinone preservative for water based industrial coatings",
  "bit 20 microbial growth inhibitor for latex based products",
  "benzisothiazolinone 20 percent solution for leather finishing chemicals",
  "bit 20 anti-fungal preservative for construction admixtures",
  "benzisothiazolinone biocide for oilfield drilling fluid preservation",
  "bit 20 preservative additive for textile spin finish formulation",
  "benzisothiazolinone in-can preservative shelf life extension paint",
  "bit 20 low voc preservative for eco-friendly paint formulation",
  "benzisothiazolinone preservative compatible with anionic surfactant systems",
  "bit 20 preservative for water based wood coating formulation",
  "benzisothiazolinone microbicide for pulp and paper slime control",
  "bit 20 biocide for cooling tower water treatment program",
  // ── Grade / purity / documentation multi-qualifier ────────
  "bit 20 iso 9001 certified manufacturer with coa and sds",
  "benzisothiazolinone reach compliant supplier with technical data sheet",
  "bit 20 industrial grade with certificate of analysis india",
  "benzisothiazolinone bulk supplier with msds and tds documentation",
  "bit 20 export quality supplier with third party lab testing",
  "benzisothiazolinone gmp certified manufacturer for cosmetic grade",
  "bit 20 supplier providing batch-wise coa for every shipment",
  "benzisothiazolinone manufacturer with fda and reach documentation",
  // ── Application troubleshooting long-tail ─────────────────
  "how much bit 20 to add per litre of water based paint",
  "recommended bit 20 dosage for detergent formulation ppm",
  "bit 20 dosage rate for metalworking fluid concentrate percentage",
  "how to prevent bacterial contamination in emulsion paint using bit 20",
  "bit 20 minimum inhibitory concentration against pseudomonas aeruginosa",
  "why does my water based adhesive need benzisothiazolinone preservative",
  "how to select correct bit 20 dosage for cosmetic formulation safety",
  "benzisothiazolinone dosage guide for personal care liquid soap",
  "bit 20 effective concentration for cutting oil preservation",
  "how long does bit 20 protect paint from microbial spoilage",
  // ── Comparison + use-case combined long-tail ──────────────
  "bit 20 vs formaldehyde donor biocide for paint preservation comparison",
  "benzisothiazolinone vs bronopol which is better for cosmetics",
  "bit 20 vs mit cmit blend for detergent preservation comparison",
  "is bit 20 safer than parabens for personal care formulation",
  "benzisothiazolinone vs isothiazolinone family comparison for paints",
  "why choose bit 20 over glutaraldehyde for industrial preservation",
  "bit 20 advantages over zinc pyrithione for coatings preservation",
  "benzisothiazolinone vs quaternary ammonium biocide for water treatment",
  // ── Buying + documentation + geography combined long-tail ──
  "bit 20 manufacturer in gujarat with export license and coa",
  "benzisothiazolinone exporter from india with iso certification",
  "bit 20 supplier near ankleshwar gidc with bulk drum packaging",
  "benzisothiazolinone bulk supplier from vapi with fast delivery",
  "bit 20 direct factory price from gujarat manufacturer india",
  "benzisothiazolinone supplier from india for middle east export",
  "bit 20 supplier for uae buyers with iso tank shipment option",
  "benzisothiazolinone exporter to africa with cif price quotation",
  // ── Packaging + logistics long-tail ────────────────────────
  "bit 20 25 kg carboy price with free sample for testing",
  "benzisothiazolinone 200 kg drum export packaging specification",
  "bit 20 bulk tanker supply for large paint manufacturing unit",
  "benzisothiazolinone ibc tank packaging for detergent manufacturer",
  "bit 20 small pack sample for r&d lab trial evaluation",
  "benzisothiazolinone flexitank shipment for overseas bulk buyer",
  // ── Safety / regulatory combined long-tail ────────────────
  "is benzisothiazolinone safe for use in children's personal care products",
  "bit 20 skin sensitization risk in leave-on cosmetic formulation",
  "benzisothiazolinone allowed concentration limit in eu cosmetic regulation",
  "bit 20 reach registration status for european union import",
  "benzisothiazolinone occupational exposure limit for factory workers india",
  "is bit 20 compliant with indian hazardous chemical handling rules",
  "benzisothiazolinone ghs classification for safety data sheet preparation",
  "bit 20 transport classification for dangerous goods shipping documentation",
  // ── Manufacturing / sourcing long-tail ────────────────────
  "how to find a reliable bit 20 manufacturer in india for export",
  "questions to ask before finalizing a benzisothiazolinone supplier",
  "how to verify bit 20 manufacturer factory and production capacity",
  "benzisothiazolinone supplier due diligence checklist for importers",
  "how to negotiate long term supply contract for bit 20 bulk buyer",
  "benzisothiazolinone alternate sourcing strategy for supply chain risk",
  "bit 20 supplier switching cost consideration for paint manufacturer",
  "how indian bit 20 manufacturers compare to chinese suppliers on quality",
  // ── Specific industry deep long-tail ───────────────────────
  "bit 20 preservative selection guide for waterborne architectural coatings",
  "benzisothiazolinone dosage for pva wood glue adhesive manufacturing",
  "bit 20 biocide selection for oil and gas produced water treatment",
  "benzisothiazolinone preservative for liquid hand wash contract manufacturing",
  "bit 20 for silicone sealant manufacturer microbial protection",
  "benzisothiazolinone for grout and mortar admixture preservation india",
  "bit 20 for car care liquid formulation shelf life extension",
  "benzisothiazolinone for floor cleaner concentrate microbial control",
  "bit 20 preservative for fabric softener manufacturing plant india",
  "benzisothiazolinone for latex glove dip manufacturing preservation",
  "bit 20 preservative dosage for industrial degreaser formulation",
  "benzisothiazolinone for printing ink water based formulation preservation",
  "bit 20 for dye dispersion manufacturing microbial contamination control",
  "benzisothiazolinone for agrochemical suspension concentrate preservation",
  "bit 20 for wallpaper adhesive paste manufacturing preservation",
  "benzisothiazolinone for car wash shampoo concentrate microbial control",
  "bit 20 for shoe polish emulsion preservation manufacturing",
  "benzisothiazolinone for hand sanitizer gel shelf life extension",
  "bit 20 preservative for starch based corrugation adhesive",
  "benzisothiazolinone for cement admixture microbial protection",
  "bit 20 for polymer emulsion latex manufacturing preservation india",
  "benzisothiazolinone preservative for photographic processing solution",
  "bit 20 for industrial coolant fluid microbial contamination prevention",
  "benzisothiazolinone for rubber latex dip formulation preservation india",
];

export const BIT_20_CITY_STATE_KEYWORDS: string[] = [
  // ── Maharashtra ────────────────────────────────────────────
  "bit 20 manufacturer in maharashtra",
  "benzisothiazolinone price in mumbai",
  "bit 20 distributor in pune maharashtra",
  "benzisothiazolinone supplier near me mumbai",
  "bit 20 wholesale dealer nagpur",
  "benzisothiazolinone exporter thane",
  // ── Gujarat ────────────────────────────────────────────────
  "bit 20 price in gujarat",
  "benzisothiazolinone distributor in surat",
  "bit 20 wholesale dealer ahmedabad",
  "benzisothiazolinone supplier near me vadodara",
  "bit 20 manufacturer bharuch gujarat",
  "benzisothiazolinone factory near me gujarat",
  // ── Tamil Nadu ─────────────────────────────────────────────
  "bit 20 manufacturer in tamil nadu",
  "benzisothiazolinone price in chennai",
  "bit 20 distributor in coimbatore tamil nadu",
  "benzisothiazolinone supplier near me chennai",
  "bit 20 wholesale dealer madurai",
  "benzisothiazolinone exporter tuticorin",
  // ── Karnataka ──────────────────────────────────────────────
  "bit 20 manufacturer in karnataka",
  "benzisothiazolinone price in bangalore",
  "bit 20 distributor in mysore karnataka",
  "benzisothiazolinone supplier near me bangalore",
  "bit 20 wholesale dealer belgaum",
  // ── Andhra Pradesh / Telangana ─────────────────────────────
  "bit 20 manufacturer in andhra pradesh",
  "benzisothiazolinone price in hyderabad",
  "bit 20 distributor in visakhapatnam",
  "benzisothiazolinone supplier near me vijayawada",
  "bit 20 wholesale dealer telangana",
  "benzisothiazolinone exporter guntur",
  // ── Delhi NCR / Haryana / Punjab ───────────────────────────
  "bit 20 manufacturer in delhi ncr",
  "benzisothiazolinone price in gurugram",
  "bit 20 distributor in noida",
  "benzisothiazolinone supplier near me faridabad",
  "bit 20 wholesale dealer punjab",
  "benzisothiazolinone manufacturer in ludhiana punjab",
  "bit 20 supplier in chandigarh",
  // ── West Bengal / Kolkata ───────────────────────────────────
  "bit 20 manufacturer in west bengal",
  "benzisothiazolinone price in kolkata",
  "bit 20 distributor in howrah",
  "benzisothiazolinone supplier near me kolkata",
  "bit 20 wholesale dealer siliguri",
  // ── Madhya Pradesh / Rajasthan ──────────────────────────────
  "bit 20 manufacturer in madhya pradesh",
  "benzisothiazolinone price in indore",
  "bit 20 distributor in bhopal",
  "benzisothiazolinone supplier near me jaipur",
  "bit 20 wholesale dealer rajasthan",
  "benzisothiazolinone manufacturer in udaipur",
  // ── Uttar Pradesh ────────────────────────────────────────────
  "bit 20 manufacturer in uttar pradesh",
  "benzisothiazolinone price in lucknow",
  "bit 20 distributor in kanpur uttar pradesh",
  "benzisothiazolinone supplier near me noida",
  "bit 20 wholesale dealer agra",
  "benzisothiazolinone manufacturer in ghaziabad",
  // ── Kerala / Odisha / Bihar / North-east ────────────────────
  "bit 20 manufacturer in kerala",
  "benzisothiazolinone price in kochi",
  "bit 20 distributor in thiruvananthapuram",
  "benzisothiazolinone supplier near me odisha",
  "bit 20 wholesale dealer bhubaneswar",
  "benzisothiazolinone supplier near me patna bihar",
  "bit 20 distributor in guwahati assam",
  // ── Additional Gujarat industrial hubs ──────────────────────
  "bit 20 manufacturer near me ankleshwar",
  "benzisothiazolinone price at vapi gidc",
  "bit 20 supplier near dahej sez",
  "benzisothiazolinone manufacturer near panoli gidc",
  "bit 20 supplier near jhagadia industrial estate",
  "benzisothiazolinone distributor near valsad gujarat",
  // ── Port cities / export hub city-state combinations ───────
  "bit 20 exporter near mundra port gujarat",
  "benzisothiazolinone exporter near kandla port",
  "bit 20 exporter near nhava sheva mumbai port",
  "benzisothiazolinone exporter near chennai port tamil nadu",
  "bit 20 exporter near visakhapatnam port andhra pradesh",
  "benzisothiazolinone exporter near tuticorin port tamil nadu",
  // ── International city/state-equivalent buying intent ───────
  "bit 20 supplier in dubai uae",
  "benzisothiazolinone distributor in abu dhabi",
  "bit 20 supplier in riyadh saudi arabia",
  "benzisothiazolinone distributor in jeddah",
  "bit 20 supplier in dhaka bangladesh",
  "benzisothiazolinone distributor in colombo sri lanka",
  "bit 20 supplier in lagos nigeria",
  "benzisothiazolinone distributor in cairo egypt",
  "bit 20 supplier in istanbul turkey",
  "benzisothiazolinone distributor in ho chi minh city vietnam",
  "bit 20 supplier in nairobi kenya",
  "benzisothiazolinone distributor in johannesburg south africa",
  "bit 20 supplier in jakarta indonesia",
  "benzisothiazolinone distributor in kuala lumpur malaysia",
  "bit 20 supplier in dammam saudi arabia",
  "benzisothiazolinone distributor in muscat oman",
  "bit 20 manufacturer in jharkhand",
  "benzisothiazolinone supplier near me ranchi",
  "bit 20 distributor in chhattisgarh",
  "benzisothiazolinone supplier near me raipur",
  "bit 20 manufacturer in goa",
  "benzisothiazolinone distributor in panaji goa",
  "bit 20 supplier in doha qatar",
  "benzisothiazolinone distributor in manama bahrain",
  "bit 20 manufacturer in uttarakhand",
  "benzisothiazolinone supplier near me dehradun",
  "bit 20 distributor in himachal pradesh",
  "benzisothiazolinone supplier near me baddi himachal pradesh",
];
