/**
 * Keywords database for bit-20-benzisothiazolinone.
 * Generated automatically.
 *
 * Chemical synonyms covered by this keyword set (CAS 2634-33-5):
 * Benzisothiazolinone, 1,2-Benzisothiazolin-3-one (BIT), BIT 20,
 * 1,2-Benzisothiazol-3(2H)-one, Benzisothiazolone, 1,2-Benzoisothiazol-3-one,
 * Benz[d]isothiazol-3(2H)-one, 2,3-Dihydro-1,2-benzisothiazol-3-one.
 *
 * Sources reviewed for keyword/content research (competitor pages, marketplaces,
 * chemical databases): innovacorporate.com, gohildyechem.com, chemicalbook.in,
 * lanxess.com, navdeep.com, multichemindia.com, clariant.com, rxchemicals.com,
 * mymicrolab.com, mumbaichemical.com, chennaichemicals.com, indiamart.com,
 * haihangchem.com, elizzyme.in, vizagchemical.com, trivenichemicalsindia.com,
 * marinechemical.in, chemicalbusinessdirectory.com, echemi.com, cneasychem.com,
 * riverlandtrading.com, chemical-suppliers.eu, excelorganics.in,
 * thegoodscentscompany.com, chemspider.com, atamankimya.com, cymitquimica.com,
 * tcichemicals.com, nacchemical.com, chemicalbook.com, pharmaffiliates.com,
 * sinobiochemistry.com, synzeal.com, bocsci.com, chemicalbull.com,
 * ennoreindiachemicals.com.
 */

export const BIT_20_BUYING_INTENT: string[] = [
  // ── Core purchase intent ──────────────────────────────────
  "buy bit 20 online",
  "bit 20 price",
  "bit 20 price in india",
  "bit 20 price per kg",
  "bit 20 price per litre",
  "bit 20 latest price 2026",
  "bit 20 manufacturer",
  "bit 20 manufacturer in india",
  "bit 20 manufacturer in gujarat",
  "bit 20 manufacturer in ankleshwar",
  "bit 20 manufacturer in vapi",
  "bit 20 manufacturer in ahmedabad",
  "bit 20 manufacturer in surat",
  "bit 20 exporter in india",
  "bit 20 exporter in gujarat",
  "bit 20 supplier",
  "bit 20 supplier in india",
  "bit 20 supplier near me",
  "bit 20 distributor in india",
  "bit 20 wholesale supplier",
  "bit 20 dealer in india",
  "bit 20 stockist in india",
  "bit 20 trader in india",
  "bit 20 bulk supplier",
  "bit 20 bulk order",
  "bit 20 bulk price",
  "bit 20 for sale",
  "bit 20 for sale india",
  "bit 20 online purchase",
  "order bit 20 online",
  "purchase bit 20 industrial grade",
  "bit 20 sample request",
  "bit 20 free sample",
  "bit 20 quotation",
  "bit 20 quote request",
  "get bit 20 price list",
  "bit 20 cost",
  "bit 20 cost per kg",
  "bit 20 rate today",
  "bit 20 rate in mumbai",
  "bit 20 rate in gujarat",
  "cheap bit 20 chemical",
  "best price bit 20",
  "bit 20 best price india",
  "bit 20 factory direct price",
  "bit 20 factory price",
  "bit 20 direct from manufacturer",
  "bit 20 fob price",
  "bit 20 fob mundra",
  "bit 20 cif price",
  "bit 20 cnf price",
  "bit 20 export price",
  "bit 20 import price",
  // ── MOQ / packaging purchase intent ───────────────────────
  "bit 20 minimum order quantity",
  "bit 20 moq",
  "bit 20 25 kg price",
  "bit 20 25 kg carboy price",
  "bit 20 200 kg drum price",
  "bit 20 210 litre drum price",
  "bit 20 1000 litre ibc price",
  "bit 20 ibc tank price",
  "bit 20 bulk tanker price",
  "bit 20 small pack price",
  "bit 20 packaging options",
  "bit 20 available pack sizes",
  "bit 20 drum supplier",
  "bit 20 carboy supplier",
  "bit 20 hdpe drum price",
  "bit 20 jerry can price",
  "bit 20 5 litre pack",
  "bit 20 20 litre pack",
  "bit 20 500 ml pack price",
  // ── Trade names / brand purchase intent ───────────────────
  "buy benzisothiazolinone online",
  "benzisothiazolinone price",
  "benzisothiazolinone price india",
  "benzisothiazolinone price per kg",
  "benzisothiazolinone manufacturer",
  "benzisothiazolinone manufacturer india",
  "benzisothiazolinone manufacturer gujarat",
  "benzisothiazolinone supplier india",
  "benzisothiazolinone supplier near me",
  "benzisothiazolinone exporter india",
  "benzisothiazolinone distributor india",
  "benzisothiazolinone wholesale india",
  "benzisothiazolinone dealer india",
  "benzisothiazolinone stockist",
  "benzisothiazolinone importer",
  "benzisothiazolinone bulk buyer",
  "benzisothiazolinone bulk price",
  "benzisothiazolinone for sale",
  "benzisothiazolinone sample order",
  "benzisothiazolinone quote",
  "benzisothiazolinone cost per litre",
  "benzisothiazolinone technical grade price",
  "benzisothiazolinone industrial grade price",
  "benzisothiazolinone cosmetic grade price",
  "benzisothiazolinone 20 percent price",
  "benzisothiazolinone 85 percent price",
  "1,2-benzisothiazolin-3-one price",
  "1,2-benzisothiazolin-3-one manufacturer",
  "1,2-benzisothiazolin-3-one supplier india",
  "1,2-benzisothiazolin-3-one buy online",
  "bit preservative price",
  "bit preservative supplier",
  "bit preservative manufacturer india",
  "bit biocide price india",
  "bit biocide supplier",
  "bit biocide manufacturer",
  "buy bit chemical online",
  "bit chemical price per kg",
  "bit chemical supplier near me",
  // ── Geographic hub keywords (India) ───────────────────────
  "bit 20 supplier in mumbai",
  "bit 20 supplier in gujarat",
  "bit 20 supplier in chennai",
  "bit 20 supplier in bangalore",
  "bit 20 supplier in coimbatore",
  "bit 20 supplier in delhi",
  "bit 20 supplier in kolkata",
  "bit 20 supplier in vadodara",
  "bit 20 supplier in vizag",
  "bit 20 supplier in visakhapatnam",
  "bit 20 supplier in hyderabad",
  "bit 20 supplier in pune",
  "bit 20 supplier in kanpur",
  "bit 20 supplier in ludhiana",
  "bit 20 supplier in indore",
  "bit 20 supplier in rajkot",
  "bit 20 supplier in ankleshwar gidc",
  "bit 20 supplier in vapi gidc",
  "bit 20 supplier in tarapur midc",
  "bit 20 supplier in gandhidham",
  "bit 20 supplier in kandla",
  "bit 20 supplier in jamnagar",
  "benzisothiazolinone supplier chennai tamilnadu",
  "benzisothiazolinone supplier visakhapatnam",
  "benzisothiazolinone supplier maharashtra",
  "benzisothiazolinone supplier gujarat",
  "benzisothiazolinone manufacturer ankleshwar",
  // ── Export / international purchase intent ────────────────
  "bit 20 exporter to uae",
  "bit 20 exporter to saudi arabia",
  "bit 20 exporter to bangladesh",
  "bit 20 exporter to sri lanka",
  "bit 20 exporter to vietnam",
  "bit 20 exporter to nigeria",
  "bit 20 exporter to egypt",
  "bit 20 exporter to turkey",
  "bit 20 exporter to usa",
  "bit 20 exporter to europe",
  "bit 20 supplier dubai",
  "bit 20 supplier oman",
  "bit 20 supplier qatar",
  "benzisothiazolinone exporter to middle east",
  "benzisothiazolinone exporter to africa",
  "benzisothiazolinone supplier fujairah",
  "benzisothiazolinone supplier sharjah",
  "benzisothiazolinone supplier muscat",
  "benzisothiazolinone global supplier",
  "benzisothiazolinone international trade",
  "biocide bit 20 export india",
  "in-can preservative bit 20 exporter",
  // ── Application-specific buying intent ────────────────────
  "bit 20 for paints buy",
  "bit 20 preservative for paints price",
  "bit 20 for adhesives price",
  "bit 20 for inks price",
  "bit 20 for detergents price",
  "bit 20 for metalworking fluids price",
  "bit 20 for cutting oils price",
  "bit 20 for cosmetics grade buy",
  "bit 20 for personal care price",
  "bit 20 for leather processing price",
  "bit 20 for textile industry price",
  "bit 20 for water treatment price",
  "bit 20 for construction chemicals price",
  "bit 20 for wood preservation buy",
  "bit 20 for drilling fluids price",
  "bit 20 for agrochemicals buy",
  "in-can preservative buy india",
  "paint preservative biocide buy",
  "formaldehyde free preservative buy",
  "formaldehyde free biocide supplier",
  "voc free preservative supplier",
  "broad spectrum biocide buy india",
  "waterborne coatings preservative supplier",
  "emulsion paint biocide supplier",
  "adhesive preservative supplier india",
  "ink preservative manufacturer india",
  "detergent preservative supplier india",
  // ── Competitor / brand-alternative buying intent ──────────
  "preventol bit 20 alternative india",
  "preventol bit 20 n equivalent",
  "nipacide bit 20 alternative",
  "nipacide bit 20 equivalent india",
  "acticide bit alternative",
  "proxel bit equivalent india",
  "mergal bit20 alternative",
  "vinkocide bit 20 d equivalent",
  "lanxess preventol bit substitute india",
  "clariant nipacide substitute india",
  "buy bit 20 instead of preventol",
  "indian alternative to imported bit 20",
  "cost effective bit 20 alternative",
  "bit 20 replacement for imported biocide",
  // ── Documentation / compliance purchase support ───────────
  "bit 20 coa supplier",
  "bit 20 sds request",
  "bit 20 msds request",
  "bit 20 tds download",
  "bit 20 certificate of analysis",
  "bit 20 with iso certification",
  "bit 20 iso 9001 manufacturer",
  "bit 20 reach compliant supplier",
  "bit 20 fda compliant supplier",
  "bit 20 halal certified",
  "bit 20 gmp certified manufacturer",
  "bit 20 food contact approved supplier",
  "benzisothiazolinone reach registered supplier",
  "benzisothiazolinone fda approved supplier",
  // ── B2B platform / procurement style ───────────────────────
  "bit 20 b2b supplier india",
  "bit 20 indiamart price",
  "bit 20 tradeindia listing",
  "bit 20 alibaba supplier",
  "bit 20 exportersindia listing",
  "bit 20 tender supplier india",
  "bit 20 government supplier india",
  "bit 20 msme manufacturer india",
  "bit 20 gst registered supplier",
  "bit 20 udyam registered manufacturer",
  "bit 20 private label manufacturing",
  "bit 20 contract manufacturing india",
  "bit 20 oem supplier",
  "bit 20 toll manufacturing",
  "bit 20 white label supplier",
  "bit 20 third party manufacturing",
  "reliable bit 20 supplier india",
  "trusted bit 20 manufacturer",
  "top bit 20 manufacturers india",
  "leading bit 20 exporters india",
  "bit 20 chemical trading company",
  "bit 20 procurement agent india",
  "bit 20 sourcing agent",
  "bit 20 chemical broker india",
  // ── Availability / logistics purchase intent ──────────────
  "bit 20 stock availability",
  "bit 20 ready stock supplier",
  "bit 20 express delivery",
  "bit 20 same day dispatch",
  "bit 20 pan india delivery",
  "bit 20 door delivery price",
  "bit 20 logistics support",
  "bit 20 shipping from mumbai",
  "bit 20 shipping from kandla",
  "bit 20 shipping from mundra",
  "bit 20 shipping from hazira",
  "bit 20 lcl shipment",
  "bit 20 fcl shipment",
  "bit 20 container load price",
  "bit 20 tanker load price",
];

export const BIT_20_RESEARCH_BASED: string[] = [
  // ── Identity / chemistry ───────────────────────────────────
  "what is bit 20",
  "what is benzisothiazolinone",
  "what is 1,2-benzisothiazolin-3-one",
  "what does bit stand for in chemicals",
  "bit 20 full form",
  "bit 20 chemical name",
  "bit 20 cas number",
  "benzisothiazolinone cas number",
  "benzisothiazolinone cas 2634-33-5",
  "bit 20 molecular formula",
  "benzisothiazolinone molecular formula",
  "benzisothiazolinone chemical formula c7h5nos",
  "bit 20 molecular weight",
  "benzisothiazolinone molecular weight",
  "benzisothiazolinone iupac name",
  "1,2-benzisothiazol-3(2h)-one iupac name",
  "benzisothiazolinone structure",
  "benzisothiazolinone smiles notation",
  "benzisothiazolinone inchi key",
  "benzisothiazolinone einecs number",
  "benzisothiazolinone ec number 220-120-9",
  "benzisothiazolinone un number",
  "benzisothiazolinone hs code india",
  "benzisothiazolinone melting point",
  "benzisothiazolinone boiling point",
  "benzisothiazolinone density",
  "benzisothiazolinone appearance",
  "benzisothiazolinone physical state",
  "benzisothiazolinone color",
  "benzisothiazolinone odour",
  "benzisothiazolinone solubility in water",
  "benzisothiazolinone solubility in glycol",
  "benzisothiazolinone ph value",
  "benzisothiazolinone vapour pressure",
  "benzisothiazolinone viscosity",
  "benzisothiazolinone flash point",
  "benzisothiazolinone ignition temperature",
  "benzisothiazolinone stability data",
  "benzisothiazolinone shelf life",
  "benzisothiazolinone thermal stability",
  "benzisothiazolinone ph stability range",
  "benzisothiazolinone stable at high ph",
  "benzisothiazolinone stable at high temperature",
  "why is bit 20 stable at alkaline ph",
  "bit 20 aqueous glycolic solution",
  "bit 20 percent active content meaning",
  "bit 20 vs bit 85 difference",
  "bit 20 vs bit 100 difference",
  "bit 20 vs neat bit powder",
  "difference between bit 20 and bit 85",
  "benzisothiazolinone crystalline solid form",
  "benzisothiazolinone liquid vs powder form",
  // ── Synonyms / naming ──────────────────────────────────────
  "1,2-benzisothiazolin-3-one synonym",
  "benzisothiazolone synonym",
  "1,2-benzoisothiazol-3-one same as bit",
  "benz[d]isothiazol-3(2h)-one synonym",
  "2,3-dihydro-1,2-benzisothiazol-3-one synonym",
  "other names for benzisothiazolinone",
  "chemical synonyms of bit",
  "trade names for benzisothiazolinone",
  "proxel chemical name",
  "acticide bit chemical name",
  "nipacide bit chemical composition",
  "preventol bit 20 n composition",
  "mergal bit20 chemical composition",
  "vinkocide bit 20 d composition",
  "is bit and benzisothiazolinone the same",
  "is 1,2-benzisothiazolin-3-one the same as bit 20",
  "bit 20 also known as",
  "what is bit preservative made of",
  // ── Mechanism / function ──────────────────────────────────
  "how does bit 20 work",
  "how does benzisothiazolinone kill bacteria",
  "bit 20 mode of action",
  "benzisothiazolinone mechanism of action",
  "benzisothiazolinone antimicrobial mechanism",
  "how does bit prevent microbial growth",
  "bit 20 antibacterial activity",
  "bit 20 antifungal activity",
  "benzisothiazolinone effective against which bacteria",
  "benzisothiazolinone effective against fungi",
  "benzisothiazolinone effective against yeast",
  "benzisothiazolinone gram positive gram negative bacteria",
  "benzisothiazolinone broad spectrum activity explained",
  "what organisms does bit 20 control",
  "how long does bit 20 preservation last",
  "bit 20 minimum inhibitory concentration",
  "bit 20 effective dosage percentage",
  "bit 20 recommended use level",
  "bit 20 use level in paints",
  "bit 20 use level in cosmetics",
  "bit 20 dosage in detergents",
  "bit 20 dosage calculator",
  "how much bit 20 to add per litre",
  "bit 20 ppm dosage guide",
  // ── Applications (informational) ──────────────────────────
  "bit 20 uses",
  "bit 20 applications",
  "benzisothiazolinone uses in industry",
  "benzisothiazolinone uses in paints",
  "benzisothiazolinone uses in coatings",
  "benzisothiazolinone uses in adhesives",
  "benzisothiazolinone uses in sealants",
  "benzisothiazolinone uses in inks",
  "benzisothiazolinone uses in printing",
  "benzisothiazolinone uses in photographic solutions",
  "benzisothiazolinone uses in detergents",
  "benzisothiazolinone uses in laundry products",
  "benzisothiazolinone uses in stain removers",
  "benzisothiazolinone uses in fabric softeners",
  "benzisothiazolinone uses in home cleaning products",
  "benzisothiazolinone uses in car care products",
  "benzisothiazolinone uses in metalworking fluids",
  "benzisothiazolinone uses in cutting oils",
  "benzisothiazolinone uses in coolants",
  "benzisothiazolinone uses in leather processing",
  "benzisothiazolinone uses in tanning industry",
  "benzisothiazolinone uses in textile industry",
  "benzisothiazolinone uses in textile spin finish",
  "benzisothiazolinone uses in dyes and pigments",
  "benzisothiazolinone uses in dye dispersions",
  "benzisothiazolinone uses in cosmetics",
  "benzisothiazolinone uses in shampoos",
  "benzisothiazolinone uses in conditioners",
  "benzisothiazolinone uses in body wash",
  "benzisothiazolinone uses in sunscreen",
  "benzisothiazolinone uses in liquid hand soap",
  "benzisothiazolinone uses in personal care products",
  "benzisothiazolinone uses in wood preservatives",
  "benzisothiazolinone uses in wood treatment",
  "benzisothiazolinone uses in construction chemicals",
  "benzisothiazolinone uses in caulks and grouts",
  "benzisothiazolinone uses in spackles",
  "benzisothiazolinone uses in wallboards",
  "benzisothiazolinone uses in putties and plasters",
  "benzisothiazolinone uses in admixtures",
  "benzisothiazolinone uses in oil drilling muds",
  "benzisothiazolinone uses in packer fluids",
  "benzisothiazolinone uses in oilfield chemicals",
  "benzisothiazolinone uses in oil recovery fluids",
  "benzisothiazolinone uses in water treatment",
  "benzisothiazolinone uses in cooling towers",
  "benzisothiazolinone uses in industrial water systems",
  "benzisothiazolinone uses in pulp and paper mills",
  "benzisothiazolinone uses in paper mill slime control",
  "benzisothiazolinone uses in agriculture",
  "benzisothiazolinone uses in pesticide formulations",
  "benzisothiazolinone uses as inert ingredient in crops",
  "benzisothiazolinone uses in flea and tick treatments",
  "benzisothiazolinone uses in vinyl gloves",
  "benzisothiazolinone uses in emulsion polymerization",
  "benzisothiazolinone uses in pigment preparation",
  "benzisothiazolinone uses in polymer dispersions",
  "benzisothiazolinone uses in latex systems",
  "benzisothiazolinone typical concentration in paints",
  "benzisothiazolinone typical concentration ppm",
  "benzisothiazolinone combination with methylisothiazolinone",
  "benzisothiazolinone and mit combination biocide",
  "bit 20 for architectural coatings",
  "bit 20 for decorative paints",
  "bit 20 for industrial coatings",
  "bit 20 for pva adhesives",
  "bit 20 for acrylic adhesives",
  "bit 20 for synthetic adhesive formulations",
  // ── Safety / regulatory / compliance research ─────────────
  "bit 20 msds",
  "bit 20 sds sheet",
  "benzisothiazolinone safety data sheet",
  "benzisothiazolinone ghs classification",
  "benzisothiazolinone hazard statements",
  "benzisothiazolinone signal word",
  "benzisothiazolinone h314 h317 meaning",
  "benzisothiazolinone corrosive to skin",
  "benzisothiazolinone eye damage risk",
  "benzisothiazolinone skin sensitizer",
  "benzisothiazolinone allergic contact dermatitis",
  "benzisothiazolinone occupational allergy",
  "benzisothiazolinone toxicity",
  "benzisothiazolinone toxicity to aquatic life",
  "benzisothiazolinone environmental impact",
  "benzisothiazolinone biodegradability",
  "benzisothiazolinone epa review",
  "benzisothiazolinone epa registration eligibility decision",
  "benzisothiazolinone reach registration",
  "benzisothiazolinone echa classification",
  "benzisothiazolinone eu biocidal products regulation",
  "benzisothiazolinone bpr approval",
  "benzisothiazolinone cosing database",
  "benzisothiazolinone inci name",
  "benzisothiazolinone eu cosmetic regulation limit",
  "benzisothiazolinone allowed concentration cosmetics eu",
  "benzisothiazolinone china gb 9685 food contact",
  "benzisothiazolinone food contact approval",
  "benzisothiazolinone ppe requirements",
  "benzisothiazolinone handling precautions",
  "benzisothiazolinone storage precautions",
  "benzisothiazolinone spill response",
  "benzisothiazolinone disposal methods",
  "benzisothiazolinone transport classification",
  "benzisothiazolinone dangerous goods classification",
  "is benzisothiazolinone banned anywhere",
  "is benzisothiazolinone safe in cosmetics",
  "is bit 20 formaldehyde free",
  "is bit 20 voc free",
  "is benzisothiazolinone carcinogenic",
  "is benzisothiazolinone an irritant",
  "benzisothiazolinone occupational exposure limit",
  "benzisothiazolinone workplace exposure standard",
  // ── Comparisons ────────────────────────────────────────────
  "bit 20 vs mit preservative",
  "bit 20 vs methylisothiazolinone",
  "bit 20 vs cmit mit blend",
  "bit vs mit vs cmit comparison",
  "bit 20 vs formaldehyde releasing biocide",
  "bit 20 vs bronopol preservative",
  "bit 20 vs iodopropynyl butylcarbamate",
  "bit 20 vs dbnpa biocide",
  "bit 20 vs parabens preservative",
  "bit 20 vs octhilinone",
  "bit 20 vs zinc pyrithione",
  "benzisothiazolinone vs isothiazolinone family",
  "benzisothiazolinone vs chloromethylisothiazolinone",
  "benzisothiazolinone vs glutaraldehyde",
  "benzisothiazolinone vs quaternary ammonium biocide",
  "which preservative is better than bit 20",
  "is bit 20 safer than formaldehyde biocides",
  "bit 20 advantages over other preservatives",
  "bit 20 disadvantages",
  "bit 85 vs bit 20 which to choose",
  "how to choose the right isothiazolinone biocide",
  // ── Technical / manufacturing / market research ───────────
  "benzisothiazolinone manufacturing process",
  "how is benzisothiazolinone made",
  "benzisothiazolinone synthesis route",
  "benzisothiazolinone raw materials",
  "benzisothiazolinone production process india",
  "benzisothiazolinone factory setup cost india",
  "benzisothiazolinone quality standards",
  "benzisothiazolinone purity specification",
  "benzisothiazolinone assay percentage",
  "benzisothiazolinone technical data sheet",
  "benzisothiazolinone specification sheet",
  "benzisothiazolinone grades available",
  "benzisothiazolinone industrial grade vs cosmetic grade",
  "benzisothiazolinone testing methods",
  "benzisothiazolinone quality control parameters",
  "benzisothiazolinone analytical testing hplc",
  "benzisothiazolinone astm test method",
  "benzisothiazolinone global market size",
  "benzisothiazolinone market trends 2026",
  "benzisothiazolinone market demand india",
  "benzisothiazolinone industry growth forecast",
  "benzisothiazolinone major manufacturers worldwide",
  "benzisothiazolinone key producers list",
  "benzisothiazolinone supply chain india",
  "benzisothiazolinone competitive landscape",
  "benzisothiazolinone price trend analysis",
  "benzisothiazolinone raw material cost trend",
  "benzisothiazolinone import export data india",
  "benzisothiazolinone customs hs code classification",
  // ── Compatibility / formulation research ──────────────────
  "benzisothiazolinone compatibility with surfactants",
  "benzisothiazolinone compatibility with emulsifiers",
  "benzisothiazolinone compatibility with anionic surfactants",
  "benzisothiazolinone compatibility with nonionic surfactants",
  "benzisothiazolinone compatibility with cationic surfactants",
  "benzisothiazolinone compatibility with amines",
  "benzisothiazolinone compatibility with latex",
  "benzisothiazolinone compatibility with acrylic emulsions",
  "benzisothiazolinone compatibility with pigments",
  "benzisothiazolinone compatibility with fillers",
  "benzisothiazolinone discoloration risk",
  "does bit 20 discolor formulations",
  "benzisothiazolinone light yellow color impact",
  "benzisothiazolinone effect on final product color",
  "benzisothiazolinone interaction with other biocides",
  "benzisothiazolinone synergy with other preservatives",
  "benzisothiazolinone when to add during production",
  "benzisothiazolinone addition temperature limit",
  "benzisothiazolinone heat stability during processing",
  "benzisothiazolinone homogeneous distribution requirement",
  "benzisothiazolinone incorporation into metalworking concentrate",
  "benzisothiazolinone pre-trial compatibility testing",
  "benzisothiazolinone effect on viscosity",
  "benzisothiazolinone effect on ph of formulation",
  // ── Health, allergen and dermatology research ─────────────
  "benzisothiazolinone allergy symptoms",
  "benzisothiazolinone contact allergen list",
  "benzisothiazolinone patch test",
  "benzisothiazolinone dermatitis paint manufacturers",
  "benzisothiazolinone dermatitis pottery moldmakers",
  "benzisothiazolinone dermatitis printers",
  "benzisothiazolinone dermatitis paper makers",
  "benzisothiazolinone dermatitis rubber factory workers",
  "benzisothiazolinone occupational exposure paint industry",
  "benzisothiazolinone sensitization rate",
  "benzisothiazolinone cosmetic allergy cases",
  "benzisothiazolinone air freshener allergy",
  "benzisothiazolinone cutting fluid dermatitis",
  // ── Environmental / ecotoxicology research ────────────────
  "benzisothiazolinone aquatic toxicity data",
  "benzisothiazolinone effect on algae",
  "benzisothiazolinone effect on scenedesmus",
  "benzisothiazolinone effect on chlorella",
  "benzisothiazolinone effect on chlamydomonas",
  "benzisothiazolinone ec50 value",
  "benzisothiazolinone photosynthesis inhibition mechanism",
  "benzisothiazolinone eco-risk assessment",
  "benzisothiazolinone biodegradation rate",
  "benzisothiazolinone environmental fate",
  "benzisothiazolinone persistence in water",
  "benzisothiazolinone bioaccumulation potential",
  "benzisothiazolinone wastewater treatment impact",
  "benzisothiazolinone initial threshold screening level",
  // ── FAQ / long-tail informational phrasing ─────────────────
  "why is bit 20 used in paints",
  "why choose bit 20 over other biocides",
  "why is bit 20 formaldehyde-free important",
  "can bit 20 be used in cosmetics",
  "can bit 20 be used in food contact products",
  "can bit 20 replace formaldehyde donors",
  "can bit 20 be mixed with other preservatives",
  "is bit 20 the same as bit 85 diluted",
  "is bit 20 water soluble",
  "is bit 20 flammable",
  "how long can bit 20 be stored",
  "how to store bit 20 safely",
  "how to handle bit 20 safely",
  "what happens if bit 20 is overdosed",
  "what happens if bit 20 is underdosed",
  "what is the shelf life of bit 20",
  "what certifications does bit 20 need",
  "what documents come with bit 20 shipment",
  "what is the hs code for bit 20 export",
  "what is the difference between bit and mit preservatives",
  "what is the recommended dosage of bit 20",
  "what industries use bit 20 the most",
  "who manufactures bit 20 in india",
  "where to buy bit 20 in bulk",
  "where is bit 20 manufactured in india",
  // ── Extended informational / how-to research ──────────────
  "how to preserve water based paint from bacteria",
  "how to prevent microbial spoilage in paint",
  "how to prevent fungal growth in adhesives",
  "how to extend shelf life of water based coatings",
  "how to stop bacterial contamination in detergents",
  "how to select the right in-can preservative",
  "how to test preservative efficacy in formulation",
  "how to conduct a preservative challenge test",
  "how to prevent bad odour in paint cans",
  "how to prevent viscosity drop in emulsion paint",
  "how to prevent gas formation in paint storage",
  "how to prevent discolouration in water based ink",
  "how to protect metalworking fluid from bacteria",
  "how to protect cutting oil from rancidity",
  "how to protect adhesive from spoilage during storage",
  "how to dose biocide in paint manufacturing",
  "how to dose preservative in detergent formulation",
  "how to calculate biocide dosage for a formulation",
  "how to verify preservative is working",
  "how to detect microbial contamination in paint",
  "what causes microbial spoilage in paint",
  "what causes bad smell in water based paint",
  "what causes viscosity loss in latex paint",
  "what causes gassing in paint cans",
  "what causes discoloration in adhesives",
  "what is in-can preservation",
  "what is dry film preservation",
  "what is the difference between in-can and dry film preservative",
  "what is a broad spectrum biocide",
  "what is a formaldehyde releasing biocide",
  "what is an isothiazolinone biocide",
  "what is a microbicide",
  "what is a fungicide biocide",
  "what is a bactericide biocide",
  "what is an algicide",
  "what is a slimicide",
  "what does broad spectrum mean in biocides",
  "what does in-can preservative mean",
  "what does formaldehyde-free mean for biocides",
  "what does ph stability mean for a preservative",
  "what does thermal stability mean for biocides",
  "what is preservative efficacy testing",
  "what is challenge testing for preservatives",
  "what is microbial contamination control",
  "what is antimicrobial agent in paint industry",
  // ── Industry / sector deep-dive research ──────────────────
  "paint industry preservative requirements",
  "coatings industry biocide selection guide",
  "adhesive industry preservation standards",
  "ink manufacturing microbial control",
  "detergent industry preservative regulations",
  "cosmetic industry preservative regulations india",
  "personal care preservative selection guide",
  "leather industry biocide requirements",
  "textile industry antimicrobial finish standards",
  "metalworking fluid industry biocide guide",
  "cutting oil industry preservation standards",
  "water treatment industry biocide selection",
  "cooling tower biocide selection guide",
  "oilfield chemicals biocide selection guide",
  "drilling fluid preservation requirements",
  "construction chemicals biocide standards",
  "wood preservation industry standards",
  "paper industry slime control standards",
  "agriculture formulation preservative standards",
  "pesticide formulation preservative requirements",
  // ── Product knowledge / decision-support research ─────────
  "benzisothiazolinone product knowledge guide",
  "benzisothiazolinone technical white paper",
  "benzisothiazolinone case study paints",
  "benzisothiazolinone case study adhesives",
  "benzisothiazolinone case study metalworking",
  "benzisothiazolinone industrial application review",
  "benzisothiazolinone innovation in preservation",
  "benzisothiazolinone sustainable chemistry",
  "benzisothiazolinone green chemistry alternative",
  "benzisothiazolinone low toxicity biocide profile",
  "benzisothiazolinone non-heavy-metal preservative",
  "benzisothiazolinone halogen free preservative",
  "benzisothiazolinone amine compatible preservative",
  "benzisothiazolinone future trends preservation",
  "benzisothiazolinone regulatory trends 2026",
  "benzisothiazolinone alternative to parabens trend",
  "benzisothiazolinone role in circular economy",
  "benzisothiazolinone waste minimisation in production",
  "benzisothiazolinone carbon footprint",
  "benzisothiazolinone sustainable packaging options",
  // ── Frequently searched natural-language questions ────────
  "does bit 20 kill mold",
  "does bit 20 kill algae",
  "does bit 20 prevent bacterial growth",
  "does bit 20 need to be combined with another biocide",
  "does bit 20 work in high ph detergents",
  "does bit 20 work in acidic formulations",
  "does bit 20 evaporate over time",
  "does bit 20 affect the smell of the final product",
  "does bit 20 change the colour of paint",
  "is bit 20 suitable for organic certified products",
  "is bit 20 approved for cosmetic use in india",
  "is bit 20 approved for use in europe",
  "is bit 20 registered under biocidal products regulation",
  "is bit 20 listed in indian pharmacopoeia",
  "is bit 20 compliant with reach regulation",
  "is bit 20 suitable for children's products",
  "is bit 20 suitable for food packaging adhesives",
  "is bit 20 suitable for medical device coatings",
  "why does paint need a preservative",
  "why does adhesive need a biocide",
  "why do water based products need microbial protection",
  "why choose liquid biocide over powder biocide",
  "why is 20 percent concentration common for bit",
  "why is glycol used as a carrier for bit 20",
  "why do formulators prefer formaldehyde-free preservatives",
  // ── AEO / voice search style phrasing ──────────────────────
  "best preservative for water based paint",
  "best biocide for adhesive formulations",
  "best in-can preservative for detergents",
  "best preservative for metalworking fluids",
  "top rated biocide for paints india",
  "recommended dosage of bit in paint formulation",
  "recommended preservative for cosmetic formulations india",
  "safe preservative options for personal care products",
  "effective biocide for leather processing",
  "reliable preservative for construction chemicals",
  "how effective is bit 20 against bacteria",
  "how effective is bit 20 against fungi",
  "how fast does bit 20 act against microbes",
  "how much bit 20 is needed for 1000 litres of paint",
  "how to calculate ppm of biocide in formulation",
  "typical dosage range for isothiazolinone biocides",
  "typical shelf life extension from bit 20",
  "average cost of preservative per litre of paint",
  "industry standard preservative concentration paints",
  "industry standard preservative concentration detergents",
];

export const BIT_20_PRIMARY_KEYWORD: string =
  "bit 20 benzisothiazolinone manufacturer india";

export const BIT_20_LONG_TAIL_KEYWORDS: string[] = [
  "bit 20 benzisothiazolinone manufacturer india",
  "1,2-benzisothiazolin-3-one 20% supplier india",
  "benzisothiazolinone bit preservative exporter india",
  "formaldehyde free in-can preservative bit 20",
  "bit 20 biocide for paints and coatings",
  "bit 20 preservative for adhesives and inks",
  "bit 20 preservative for metalworking fluids",
  "benzisothiazolinone cas 2634-33-5 supplier",
  "bit 20 broad spectrum bactericide fungicide",
  "buy bit 20 preservative india price",
];
