/**
 * Keywords database for eddm-non-triazine-h2s-scavenger.
 * Generated automatically.
 */

export const EDDM_BUYING_INTENT: string[] = [
  "eddm manufacturer in india",
  "eddm manufacturers in india",
  "eddm supplier in india",
  "eddm suppliers in india",
  "eddm manufacturer in gujarat",
  "eddm manufacturers in gujarat",
  "eddm supplier in gujarat",
  "eddm suppliers in gujarat",
  "eddm exporter in india",
  "eddm exporters in india",
  "eddm exporter in gujarat",
  "eddm exporters in gujarat",
  "eddm distributor in india",
  "eddm distributor in gujarat",
  "eddm dealer in india",
  "eddm dealer in gujarat",
  "eddm wholesaler in india",
  "eddm wholesaler in gujarat",
  "eddm trader in india",
  "eddm trader in gujarat",
  "eddm stockist in india",
  "eddm stockist in gujarat",
  "eddm producer in india",
  "eddm producer in gujarat",
  "eddm factory in india",
  "eddm factory in gujarat",
  "eddm plant in india",
  "eddm plant in gujarat",
  "eddm vendor in india",
  "eddm vendor in gujarat",
  "(ethylenedioxy)dimethanol manufacturer in india",
  "(ethylenedioxy)dimethanol manufacturers in india",
  "(ethylenedioxy)dimethanol supplier in india",
  "(ethylenedioxy)dimethanol suppliers in india",
  "(ethylenedioxy)dimethanol manufacturer in gujarat",
  "(ethylenedioxy)dimethanol manufacturers in gujarat",
  "(ethylenedioxy)dimethanol supplier in gujarat",
  "(ethylenedioxy)dimethanol suppliers in gujarat",
  "ethylenedioxy dimethanol manufacturer in india",
  "ethylenedioxy dimethanol manufacturers in india",
  "ethylenedioxy dimethanol supplier in india",
  "ethylenedioxy dimethanol suppliers in india",
  "ethylenedioxy dimethanol manufacturer in gujarat",
  "ethylenedioxy dimethanol manufacturers in gujarat",
  "ethylenedioxy dimethanol supplier in gujarat",
  "ethylenedioxy dimethanol suppliers in gujarat",
  "ethylenedioxydimethanol manufacturer in india",
  "ethylenedioxydimethanol supplier in india",
  "ethylenedioxydimethanol manufacturer in gujarat",
  "ethylenedioxydimethanol supplier in gujarat",
  "ethylenedioxy dimethanol exporter india",
  "ethylenedioxy dimethanol exporter gujarat",
  "biocides eddm manufacturer in india",
  "biocides eddm manufacturers in india",
  "biocides eddm supplier in india",
  "biocides eddm suppliers in india",
  "biocides eddm manufacturer in gujarat",
  "biocides eddm manufacturers in gujarat",
  "biocides eddm supplier in gujarat",
  "biocides eddm suppliers in gujarat",
  "biocides ethylenedioxy dimethanol manufacturer",
  "biocides ethylenedioxy dimethanol supplier",
  "biocides ethylenedioxy dimethanol exporter",
  "biocides eddm exporter india",
  "biocides eddm price india",
  "biocides eddm wholesale india",
  "buy biocides eddm india",
  "buy biocides eddm gujarat",
  "biocides eddm manufacturer ankleshwar",
  "biocides eddm manufacturer mumbai",
  "biocides eddm supplier mumbai",
  "biocides eddm supplier ankleshwar",
  "biocides eddm bulk supplier",
  "biocides eddm bulk price",
  "buy eddm india",
  "buy eddm gujarat",
  "buy eddm mumbai",
  "buy eddm ankleshwar",
  "buy eddm online",
  "buy eddm bulk",
  "buy eddm wholesale",
  "buy eddm at best price",
  "buy ethylenedioxy dimethanol",
  "buy ethylenedioxy dimethanol india",
  "buy ethylenedioxy dimethanol bulk",
  "buy ethylenedioxy dimethanol online",
  "buy non triazine h2s scavenger",
  "buy non triazine h2s scavenger india",
  "buy non triazine h2s scavenger bulk",
  "buy non triazine h2s scavenger online",
  "buy formaldehyde based h2s scavenger",
  "buy non amine h2s scavenger",
  "buy eddm cas 3586-55-8",
  "buy eddm 90 percent",
  "buy eddm 90 active liquid",
  "buy eddm drum india",
  "buy eddm ibc india",
  "buy eddm tanker india",
  "purchase eddm india",
  "purchase eddm online",
  "order eddm online",
  "order eddm bulk",
  "order ethylenedioxy dimethanol",
  "eddm price",
  "eddm price india",
  "eddm price gujarat",
  "eddm price per kg",
  "eddm price per ton",
  "eddm price per mt",
  "eddm price per drum",
  "eddm price per ibc",
  "eddm price list",
  "eddm price list 2026",
  "eddm price list 2027",
  "eddm market price",
  "eddm market price india",
  "eddm wholesale price",
  "eddm bulk price",
  "eddm bulk price india",
  "eddm factory price",
  "eddm fob price",
  "eddm cif price",
  "eddm ex works price",
  "eddm cnf price",
  "eddm landed price india",
  "eddm cheap price",
  "eddm discount price",
  "eddm best price india",
  "eddm latest price",
  "eddm quotation",
  "eddm quote",
  "eddm rfq",
  "eddm rfp",
  "eddm price quote india",
  "eddm tender price",
  "eddm offer price",
  "eddm price comparison",
  "ethylenedioxy dimethanol price",
  "ethylenedioxy dimethanol price india",
  "ethylenedioxy dimethanol price per kg",
  "ethylenedioxy dimethanol price per ton",
  "ethylenedioxy dimethanol bulk price",
  "ethylenedioxy dimethanol wholesale price",
  "non triazine h2s scavenger price",
  "non triazine h2s scavenger price india",
  "non triazine h2s scavenger price per ton",
  "non triazine h2s scavenger quote",
  "eddm minimum order quantity",
  "eddm moq",
  "eddm 1 mt moq",
  "eddm 5 mt price",
  "eddm 10 mt price",
  "eddm 20 mt fcl price",
  "eddm sample price",
  "eddm sample free",
  "eddm trial order",
  "eddm 230 kg drum supplier",
  "eddm 230 kg hdpe drum price",
  "eddm 1000 l ibc tank price",
  "eddm 1000 l ibc supplier",
  "eddm bulk tanker delivery",
  "eddm iso tank supplier",
  "eddm iso tank price india",
  "eddm flexitank supply",
  "eddm 200 l drum price",
  "eddm 25 kg can price",
  "eddm packaging options",
  "eddm custom packaging",
  "eddm hdpe drum manufacturer",
  "eddm ibc tank manufacturer",
  "eddm bulk tanker price",
  "eddm indiamart",
  "eddm tradeindia",
  "eddm justdial",
  "eddm exportersindia",
  "eddm alibaba",
  "eddm made in china",
  "eddm b2b",
  "eddm b2b supplier india",
  "eddm direct manufacturer india",
  "eddm direct factory price",
  "eddm verified supplier india",
  "eddm gold supplier",
  "eddm trusted supplier",
  "non triazine h2s scavenger indiamart",
  "non triazine h2s scavenger tradeindia",
  "ethylenedioxy dimethanol indiamart",
  "ethylenedioxy dimethanol tradeindia",
  "ethylenedioxy dimethanol exportersindia",
  "ethylenedioxy dimethanol alibaba",
  "eddm manufacturer ankleshwar",
  "eddm manufacturer bharuch",
  "eddm manufacturer vadodara",
  "eddm manufacturer ahmedabad",
  "eddm manufacturer surat",
  "eddm manufacturer vapi",
  "eddm manufacturer dahej",
  "eddm manufacturer mumbai",
  "eddm manufacturer navi mumbai",
  "eddm manufacturer pune",
  "eddm manufacturer chennai",
  "eddm manufacturer hyderabad",
  "eddm manufacturer delhi",
  "eddm manufacturer kolkata",
  "eddm manufacturer kandla",
  "eddm supplier ankleshwar",
  "eddm supplier bharuch",
  "eddm supplier vadodara",
  "eddm supplier ahmedabad",
  "eddm supplier surat",
  "eddm supplier mumbai",
  "eddm supplier vapi",
  "eddm supplier dahej",
  "eddm supplier kandla",
  "eddm exporter mundra",
  "eddm exporter nhava sheva",
  "eddm exporter mumbai port",
  "eddm exporter kandla port",
  "eddm exporter pipavav",
  "eddm exporter hazira",
  "buy eddm in uae",
  "buy eddm in dubai",
  "buy eddm in abu dhabi",
  "buy eddm in saudi arabia",
  "buy eddm in jeddah",
  "buy eddm in dammam",
  "buy eddm in oman",
  "buy eddm in qatar",
  "buy eddm in kuwait",
  "buy eddm in iraq",
  "buy eddm in egypt",
  "buy eddm in turkey",
  "buy eddm in russia",
  "buy eddm in usa",
  "buy eddm in brazil",
  "buy eddm in vietnam",
  "buy eddm in thailand",
  "buy eddm in indonesia",
  "buy eddm in malaysia",
  "buy eddm in nigeria",
  "buy eddm in china",
  "buy eddm in europe",
  "buy eddm in germany",
  "buy eddm in netherlands",
  "eddm supplier uae",
  "eddm supplier saudi arabia",
  "eddm supplier oman",
  "eddm supplier qatar",
  "eddm supplier kuwait",
  "eddm supplier iraq",
  "eddm supplier egypt",
  "eddm supplier turkey",
  "eddm supplier russia",
  "eddm supplier usa",
  "eddm supplier brazil",
  "eddm supplier vietnam",
  "eddm supplier thailand",
  "eddm supplier indonesia",
  "eddm supplier malaysia",
  "eddm supplier nigeria",
  "eddm supplier china",
  "eddm exporter to uae",
  "eddm exporter to saudi arabia",
  "eddm exporter to usa",
  "eddm exporter to europe",
  "eddm cif jebel ali",
  "eddm cif houston",
  "eddm cif rotterdam",
  "eddm cif santos",
  "eddm cif singapore",
  "eddm cif laem chabang",
  "buy eddm for oil and gas",
  "buy eddm for refineries",
  "buy eddm for natural gas",
  "buy eddm for crude oil",
  "buy eddm for produced water",
  "buy eddm for biogas desulphurisation",
  "buy eddm for pipeline h2s removal",
  "buy eddm for water treatment",
  "buy eddm for cooling water",
  "buy eddm for paints",
  "buy eddm for adhesives",
  "buy eddm for metalworking fluids",
  "buy eddm for cutting fluids",
  "buy eddm for polymer dispersions",
  "buy eddm for pigment slurries",
  "buy eddm for concrete admixtures",
  "buy eddm for paper mills",
  "buy eddm for leather industry",
  "buy eddm in-can preservative",
  "buy eddm slow release biocide",
  "buy eddm for emulsion paints",
  "buy eddm for printing inks",
  "buy eddm for detergent formulations",
  "buy eddm for personal care",
  "buy eddm for cosmetics preservation",
  "buy eddm for textile auxiliaries",
  "preventol eddm alternative india",
  "preventol eddm alternative supplier",
  "lanxess preventol eddm alternative",
  "lanxess preventol eddm equivalent",
  "preventol d 9 alternative india",
  "k-bio eddm alternative",
  "exocide fc eddm alternative",
  "biocide ghf eddm alternative",
  "biocel eddm alternative",
  "ataman ethylenedioxydimethanol alternative",
  "atamankimya eddm alternative",
  "madhuchemicals biocides eddm alternative",
  "trigon chemie ethylenedioxydimethanol alternative",
  "haihang eddm alternative",
  "sinobio eddm alternative",
  "sinotrust ethylenedioxy dimethanol alternative",
  "alfa industry ethylenedioxy dimethanol alternative",
  "parchem ethylenedioxy dimethanol alternative",
  "getchem eddm alternative",
  "cymitquimica eddm alternative",
  "evitachem eddm alternative",
  "imperial chem biocide eddm alternative",
  "excelind biocel alternative",
  "matangi industries biocide alternative",
  "spectrum biocides alternative",
  "shiv shakti biocide alternative",
  "pisces india biocide alternative",
  "envichem biocide alternative",
  "rxchemicals biocide alternative",
  "yumpu biocide ghf alternative",
  "musechem ethylenedioxy dimethanol alternative",
  "iso 9001 eddm manufacturer",
  "iso certified eddm supplier india",
  "reach registered eddm supplier",
  "tsca compliant eddm supplier",
  "gmp grade eddm manufacturer",
  "halal certified eddm supplier",
  "kosher certified eddm supplier",
  "msme eddm manufacturer india",
  "eddm sgs inspection supplier",
  "eddm bv inspection supplier",
  "eddm intertek inspection supplier",
  "eddm coa supplier india",
  "eddm tds supplier india",
  "eddm sds supplier india",
  "eddm fcl shipping india",
  "eddm lcl shipping india",
  "eddm air freight",
  "eddm sea freight",
  "eddm bulk export india",
  "eddm export documentation",
  "eddm hs code 29094980 supplier",
  "eddm hs code supplier",
  "eddm un number supplier",
  "eddm dangerous goods shipping",
  "eddm ready stock india",
  "eddm fast delivery india",
  "eddm 24/7 support supplier",
  "eddm technical service supplier",
  "eddm dosing service india",
  "eddm field service india",
];

export const EDDM_RESEARCH_BASED: string[] = [
  "ethylenedioxy dimethanol cas no",
  "ethylenedioxy dimethanol cas number",
  "ethylenedioxy dimethanol cas 3586-55-8",
  "(ethylenedioxy)dimethanol cas no",
  "(ethylenedioxy)dimethanol cas number",
  "eddm cas no",
  "eddm cas number",
  "eddm cas 3586-55-8",
  "eddm einecs number",
  "eddm einecs 222-720-6",
  "eddm chemical formula",
  "eddm molecular formula",
  "eddm molecular formula c4h10o4",
  "eddm molecular weight",
  "eddm molecular weight 122.12",
  "eddm structure",
  "eddm molecular structure",
  "eddm structural formula",
  "eddm smiles",
  "eddm inchi",
  "eddm inchikey",
  "eddm iupac name",
  "eddm iupac name 1,6-dihydroxy-2,5-dioxahexane",
  "ethylenedioxy dimethanol iupac name",
  "ethylenedioxy dimethanol smiles",
  "ethylenedioxy dimethanol inchi",
  "ethylenedioxy dimethanol pubchem",
  "ethylenedioxy dimethanol pubchem cid",
  "ethylenedioxy dimethanol echa",
  "ethylenedioxy dimethanol echa registration",
  "ethylenedioxy dimethanol synonyms",
  "ethylenedioxy dimethanol other names",
  "eddm synonyms list",
  "eddm trade names",
  "eddm chemical names",
  "eddm alternate names",
  "eddm 1,6-dihydroxy-2,5-dioxahexane",
  "eddm dimethylol glycol",
  "eddm ethylene glycol bis(semiformal)",
  "eddm ethylene glycol hemiacetal",
  "ethylenedioxy dimethanol vs dimethylol glycol",
  "1,6-dihydroxy-2,5-dioxahexane cas",
  "1,6-dihydroxy-2,5-dioxahexane structure",
  "ethylenedioxy dimethanol uses",
  "ethylenedioxy dimethanol uses in oil and gas",
  "ethylenedioxy dimethanol uses in water treatment",
  "ethylenedioxy dimethanol uses in paints",
  "ethylenedioxy dimethanol uses in adhesives",
  "ethylenedioxy dimethanol uses in metalworking",
  "ethylenedioxy dimethanol applications",
  "ethylenedioxy dimethanol industrial applications",
  "ethylenedioxy dimethanol biocide application",
  "ethylenedioxy dimethanol h2s scavenger application",
  "eddm uses",
  "eddm uses in oil and gas",
  "eddm uses in water treatment",
  "eddm uses in biogas",
  "eddm uses in refinery",
  "eddm uses in paints",
  "eddm uses in adhesives",
  "eddm uses in pigment slurries",
  "eddm uses in polymer dispersions",
  "eddm uses in concrete admixtures",
  "eddm uses in metalworking fluids",
  "eddm uses in cutting fluids",
  "eddm uses in cooling water",
  "eddm uses in paper industry",
  "eddm uses in leather industry",
  "eddm uses in detergents",
  "eddm uses in personal care",
  "eddm applications list",
  "eddm major applications",
  "eddm typical applications",
  "eddm in-can preservative use",
  "eddm slow release bactericide use",
  "eddm formaldehyde donor use",
  "eddm fungicide use",
  "how eddm works",
  "how non triazine h2s scavenger works",
  "how does eddm scavenge h2s",
  "eddm reaction with h2s",
  "eddm mechanism of action",
  "eddm mechanism h2s removal",
  "eddm mechanism biocide",
  "eddm slow release formaldehyde",
  "eddm formaldehyde release rate",
  "eddm gas phase sterilization",
  "eddm broad spectrum bactericide",
  "eddm action against srb",
  "eddm action against gram positive bacteria",
  "eddm action against gram negative bacteria",
  "eddm action against yeast and fungi",
  "eddm reaction kinetics",
  "eddm reaction stoichiometry",
  "eddm h2s reaction byproducts",
  "eddm reaction byproduct analysis",
  "eddm vs triazine reaction byproducts",
  "eddm reaction with mercaptans",
  "eddm reaction with co2",
  "eddm reaction with water",
  "eddm reaction with steel",
  "eddm hydrolysis",
  "eddm thermal stability",
  "eddm decomposition products",
  "eddm vs mea triazine",
  "eddm vs mma triazine",
  "eddm vs triazine",
  "eddm vs glutaraldehyde",
  "eddm vs acrolein",
  "eddm vs zinc oxide",
  "eddm vs solid h2s scavengers",
  "eddm vs amine units",
  "eddm vs iron sponge",
  "eddm vs sulfatreat",
  "eddm vs nitrite scavengers",
  "non triazine vs triazine h2s scavenger",
  "non triazine h2s scavenger advantages",
  "non triazine h2s scavenger benefits",
  "non triazine h2s scavenger disadvantages",
  "non triazine vs amine based h2s scavenger",
  "non amine h2s scavenger comparison",
  "formaldehyde based vs amine based h2s scavenger",
  "eddm advantages over triazine",
  "eddm disadvantages",
  "eddm vs preventol d 9",
  "eddm vs preventol eddm",
  "eddm vs k-bio eddm",
  "eddm vs exocide fc",
  "eddm vs biocide ghf",
  "eddm vs biocel",
  "eddm vs bronopol",
  "eddm vs methylisothiazolinone",
  "eddm vs benzisothiazolinone",
  "eddm vs bit 20",
  "eddm vs cmit/mit",
  "eddm physical properties",
  "eddm chemical properties",
  "eddm appearance",
  "eddm color",
  "eddm odor",
  "eddm density",
  "eddm specific gravity",
  "eddm specific gravity 20c",
  "eddm refractive index",
  "eddm refractive index 20c",
  "eddm boiling point",
  "eddm freezing point",
  "eddm flash point",
  "eddm flash point greater than 100",
  "eddm viscosity",
  "eddm viscosity at 25c",
  "eddm vapor pressure",
  "eddm vapor density",
  "eddm solubility in water",
  "eddm water miscibility",
  "eddm solubility in oil",
  "eddm solubility in solvents",
  "eddm ph",
  "eddm ph 1 percent solution",
  "eddm ph range 6 to 8",
  "eddm operating ph range",
  "eddm active substance content",
  "eddm 90 percent active",
  "eddm total aldehyde content",
  "eddm formaldehyde content",
  "eddm formaldehyde content 42 to 48 percent",
  "eddm purity",
  "eddm 90 percent purity",
  "eddm spec sheet",
  "eddm technical specifications",
  "eddm typical specifications",
  "eddm specifications table",
  "eddm msds",
  "eddm msds pdf",
  "eddm msds download",
  "eddm sds",
  "eddm sds pdf",
  "eddm sds download",
  "eddm safety data sheet",
  "eddm tds",
  "eddm technical data sheet",
  "eddm coa",
  "eddm certificate of analysis",
  "eddm hazard classification",
  "eddm ghs classification",
  "eddm ghs07 hazard",
  "eddm signal word warning",
  "eddm h315 skin irritation",
  "eddm h319 eye irritation",
  "eddm h317 allergic skin reaction",
  "eddm hazard statements",
  "eddm precautionary statements",
  "eddm first aid measures",
  "eddm firefighting measures",
  "eddm accidental release measures",
  "eddm handling and storage",
  "eddm storage conditions",
  "eddm shelf life",
  "eddm shelf life 2 years",
  "eddm exposure controls",
  "eddm ppe requirements",
  "eddm toxicity data",
  "eddm acute toxicity",
  "eddm skin sensitization",
  "eddm chronic toxicity",
  "eddm ld50",
  "eddm lc50",
  "eddm ecotoxicity",
  "eddm aquatic toxicity",
  "eddm biodegradation",
  "eddm aox content",
  "eddm low aox",
  "eddm formaldehyde release safety",
  "eddm reach registration status",
  "eddm tsca status",
  "eddm k-reach status",
  "eddm china reach status",
  "eddm echa registration",
  "eddm echa substance information",
  "eddm bpr biocidal products regulation",
  "eddm regulatory information",
  "eddm transport information",
  "eddm un number",
  "eddm hs code",
  "eddm hs code 29094980",
  "eddm dangerous goods classification",
  "eddm dosage calculation",
  "eddm dosage in oil and gas",
  "eddm dosage in produced water",
  "eddm dosage in biogas",
  "eddm dosage in metalworking fluid",
  "eddm dosage in pigment slurry",
  "eddm dosage 0.05 to 0.15 percent",
  "eddm typical dosing rate",
  "eddm scavenging efficiency",
  "eddm temperature effects",
  "eddm pressure effects",
  "eddm impact of co2",
  "eddm impact of water",
  "eddm impact on steel pipelines",
  "eddm corrosion data",
  "eddm non corrosive chemistry",
  "eddm no salt precipitation",
  "eddm catalyst poisoning data",
  "eddm impact on refinery catalysts",
  "eddm impact on amine units",
  "eddm impact on desalters",
  "eddm impact on wastewater treatment plant",
  "eddm compatibility with corrosion inhibitors",
  "eddm compatibility with demulsifiers",
  "eddm compatibility with scale inhibitors",
  "eddm compatibility with biocides",
  "eddm compatibility list",
  "eddm manufacturing process",
  "eddm production process",
  "eddm synthesis route",
  "eddm synthesis from ethylene glycol and paraformaldehyde",
  "eddm raw materials",
  "eddm production cost analysis",
  "eddm chemical plant setup",
  "eddm capacity in india",
  "eddm production capacity gujarat",
  "eddm production volume india",
  "eddm global market size",
  "eddm global market report",
  "eddm market size 2026",
  "eddm market size 2027",
  "eddm market growth rate",
  "eddm demand forecast 2030",
  "eddm supply chain analysis",
  "eddm import export data india",
  "eddm import data india",
  "eddm export data india",
  "eddm trade data india",
  "eddm hs code import data",
  "eddm hs code export data",
  "eddm price trend",
  "eddm price forecast",
  "eddm market share india",
  "eddm key manufacturers global",
  "eddm top manufacturers india",
  "eddm top suppliers global",
  "eddm competitive landscape",
  "eddm value chain",
  "eddm market drivers",
  "eddm market restraints",
  "eddm market opportunities",
  "eddm iso 9001 standards",
  "eddm astm standards",
  "eddm api standards",
  "eddm nace standards",
  "eddm quality standards",
  "eddm qa qc parameters",
  "eddm impurity profile",
  "eddm stability study",
  "eddm long term stability",
  "eddm storage stability",
  "eddm packaging compatibility",
  "eddm hdpe drum compatibility",
  "eddm ibc tank compatibility",
  "eddm patent information",
  "eddm new research 2026",
  "eddm latest innovations",
  "eddm green chemistry",
  "eddm sustainable chemistry",
  "eddm life cycle assessment",
  "eddm carbon footprint",
  "eddm circular economy",
  "eddm waste management",
  "eddm disposal best practices",
  "eddm recycling and reuse",
  "eddm bioequivalent alternatives",
  "eddm sustainable raw materials",
  "eddm scientific literature",
  "eddm white paper",
  "eddm technical white paper",
  "eddm case study oilfield",
  "eddm case study biogas",
  "eddm case study water treatment",
  "eddm case study metalworking fluid",
  "eddm research paper",
  "eddm sciencedirect article",
  "eddm review paper",
  "eddm pubchem compound information",
  "eddm chemicalbook information",
  "eddm chemspider information",
  "eddm reaxys information",
  "eddm benchchem product information",
  "eddm sigma aldrich information",
  "eddm cymitquimica information",
  "preventol eddm product description",
  "preventol eddm composition",
  "preventol eddm specification",
  "preventol eddm uses",
  "preventol d 9 composition",
  "preventol d 9 uses",
  "ataman ethylenedioxydimethanol specification",
  "ataman chemicals biocide specification",
  "lanxess industrial biocides brochure",
  "madhuchemicals biocides product list",
  "trigon chemie ethylenedioxy dimethanol specification",
  "k-bio eddm composition",
  "exocide fc composition",
  "biocide ghf composition",
  "biocel composition",
  "research and markets eddm report",
  "ethylenedioxy dimethanol eddm global market report",
  "linkedin eddm market analysis north america",
  "researchgate ethylenedioxy dimethanol study",
];

export const EDDM_PRIMARY_KEYWORD: string = "non triazine based H2S scavenger";

export const EDDM_LONG_TAIL_KEYWORDS: string[] = [
  "non triazine H2S scavenger",
  "EDDM H2S scavenger",
  "EDDM manufacturer India",
  "ethylenedioxydimethanol H2S scavenger",
  "non triazine based H2S scavenger manufacturer",
  "non triazine H2S scavenger supplier India",
  "EDDM non triazine scavenger",
  "non amine H2S scavenger",
  "formaldehyde based H2S scavenger",
  "EDDM oilfield chemical",
  "non triazine desulfurizer",
  "EDDM hydrogen sulfide scavenger",
  "buy non triazine H2S scavenger",
  "non triazine H2S scavenger price",
  "EDDM CAS 3586-55-8",
  "ethylenedioxy dimethanol supplier",
  "EDDM manufacturer Gujarat India",
  "non triazine H2S scavenger for natural gas",
  "non triazine H2S scavenger for crude oil",
  "EDDM water treatment chemical",
  "non triazine scavenger oil and gas",
  "EDDM biocide preservative",
  "non triazine H2S removal chemical",
  "EDDM supplier UAE",
  "EDDM exporter India",
  "non triazine H2S scavenger bulk supply",
  "EDDM IBC drum supply",
  "non triazine alternative to MEA triazine",
  "EDDM vs MEA triazine",
  "non triazine H2S scavenger manufacturer India",
  "EDDM for biogas desulphurisation",
  "non triazine H2S scavenger for produced water",
  "EDDM metalworking fluid preservative",
  "non triazine H2S scavenger dosing",
  "EDDM slow release bactericide",
  "non triazine scavenger no salt precipitation",
  "EDDM non corrosive H2S scavenger",
  "buy EDDM bulk India",
  "EDDM price per ton",
  "non triazine H2S scavenger ISO certified",
  "EDDM for pipeline H2S treatment",
  "non triazine H2S scavenger for refineries",
  "EDDM formaldehyde donor",
  "non triazine H2S scavenger supplier Gujarat",
  "EDDM in-can preservative",
  "non triazine H2S scavenger for water treatment",
  "EDDM supplier Middle East",
  "non triazine H2S scavenger CIF price",
  "EDDM manufacturer Ankleshwar",
];
