/**
 * Keyword Content Sections Helper
 *
 * Transforms EXPANDED_KEYWORDS into structured content sections
 * for rendering on product pages. These sections surface keyword-rich
 * text as real, crawlable page content — not just meta tags.
 *
 * Google ranks pages based on visible content, headings, and structured data.
 * Meta keywords alone have been ignored by Google since 2009.
 */

import { EXPANDED_KEYWORDS } from "@/lib/seo/expanded-keywords";

/* ── Types ───────────────────────────────────────────────────────── */

export type KeywordContentGroup = {
  heading: string;
  description: string;
  items: string[];
  prose: string;
};

export type ProductKeywordContentSections = {
  categoryLabel: string;
  categorySummary: string;
  supplySectionHeading: string;
  applicationGroups: KeywordContentGroup[];
  supplyGroups: KeywordContentGroup[];
  geographyGroups: KeywordContentGroup[];
};

/* ── Helpers ─────────────────────────────────────────────────────── */

function extractByPattern(keywords: string[], patterns: RegExp[]): string[] {
  return keywords.filter((kw) => patterns.some((p) => p.test(kw)));
}

function titleCase(str: string): string {
  return str
    .split(" ")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

function dedupeArray(arr: string[]): string[] {
  return Array.from(new Set(arr.map((s) => s.trim()).filter(Boolean)));
}

/**
 * Returns the clean human-written description as the visible "prose" for a section.
 *
 * IMPORTANT: We deliberately do NOT echo keyword arrays into visible body text.
 * Earlier versions concatenated 8+ keyword phrases with boilerplate connectors
 * ("Our product range covers...", "We supply solutions for...", "Customers rely on us for...")
 * which produced classic keyword-stuffing patterns that Google's Helpful Content
 * Update and SpamBrain demote sitewide. Even echoing 3 keywords per section still
 * repeats the head term ("h2s scavenger", "triazine") across 13 sections of the
 * product page — high-density repetition that triggers spam classifiers.
 *
 * The keywords still drive SEO via:
 *   - meta keywords tag (generated by getProductSeoKeywords)
 *   - structured data alternateName (ProductSchema)
 *   - product synonym section (rendered separately for enriched products)
 *   - long-tail topic pages (/applications/*, /supply/*, /resources/*)
 *
 * Visible body content here only shows the clean human-written description.
 */
function keywordsToProse(_keywords: string[], context: string): string {
  return context;
}

/* ── Category content config ─────────────────────────────────────── */

const CATEGORY_CONTENT: Record<
  string,
  {
    categoryLabel: string;
    categorySummary: string;
    supplySectionHeading: string;
  }
> = {
  "mea-triazine-78-h2s-scavenger": {
    categoryLabel: "H2S Scavenger — MEA Triazine 78%",
    categorySummary:
      "MEA Triazine 78% is a triazine-based H2S scavenger manufactured by Vasudev Chemo Pharma. It belongs to the broader H2S Scavenger chemical category and is used across oilfield, gas processing, biogas, refinery, and pipeline applications worldwide.",
    supplySectionHeading:
      "Global Supply Network for MEA Triazine 78% H2S Scavenger",
  },
  "mma-triazine-40": {
    categoryLabel: "H2S Scavenger — MMA Triazine 40%",
    categorySummary:
      "MMA Triazine 40% is a BTX-free triazine-based H2S scavenger manufactured by Vasudev Chemo Pharma. Part of the H2S Scavenger chemical category, it is specifically designed for environmental compliance in refineries and gas processing operations.",
    supplySectionHeading:
      "Global Supply Network for MMA Triazine 40% H2S Scavenger",
  },
  "triazine-h2s-scavenger-general": {
    categoryLabel: "Triazine H2S Scavenger",
    categorySummary:
      "Triazine-based H2S scavengers from Vasudev Chemo Pharma are used in oil and gas, biogas, water treatment, and industrial applications. Available as MEA Triazine 78% and MMA Triazine 40% (BTX-free), they provide efficient, cost-effective hydrogen sulphide removal.",
    supplySectionHeading:
      "Global Supply of Triazine H2S Scavenger Chemicals",
  },
  "metal-working-fluids": {
    categoryLabel: "Metal Working Fluid Biocide",
    categorySummary:
      "Triazine-based biocides from Vasudev Chemo Pharma preserve metal working fluids by controlling bacterial and fungal growth. They prevent rancidity, odour, and degradation of cutting fluids, coolants, and machining fluids used in automotive, aerospace, and precision manufacturing.",
    supplySectionHeading:
      "Global Supply of Metal Working Fluid Biocide",
  },
  "biocide-oil-gas": {
    categoryLabel: "Oilfield Biocide",
    categorySummary:
      "Triazine-based oilfield biocides from Vasudev Chemo Pharma control sulphate reducing bacteria (SRB), acid producing bacteria (APB), and general aerobic bacteria in oil and gas operations. They prevent microbially influenced corrosion (MIC) in pipelines, water injection systems, and produced water.",
    supplySectionHeading:
      "Global Supply of Oilfield Biocide Chemicals",
  },
  "mea-triazine-78-high-concentration": {
    categoryLabel: "H2S Scavenger — High Concentration MEA Triazine 78%",
    categorySummary:
      "High concentration MEA Triazine 78% from Vasudev Chemo Pharma delivers maximum scavenging efficiency per unit volume. This premium H2S scavenger is designed for high H2S load operations in offshore, deepwater, and sour gas applications.",
    supplySectionHeading:
      "Global Supply of High Concentration MEA Triazine 78%",
  },
  "mma-triazine-40-btx-free": {
    categoryLabel: "H2S Scavenger — BTX-Free MMA Triazine 40%",
    categorySummary:
      "BTX-free MMA Triazine 40% from Vasudev Chemo Pharma meets strict environmental regulations for BTEX emissions. This environmentally responsible H2S scavenger is used in refineries, gas processing plants, and operations requiring compliance with VOC emission standards.",
    supplySectionHeading:
      "Global Supply of BTX-Free MMA Triazine 40%",
  },
  "benzalkonium-chloride-50": {
    categoryLabel: "Surfactant Chemicals — Benzalkonium Chloride 50% (BKC 50%)",
    categorySummary:
      "Benzalkonium Chloride 50% (BKC 50%) is a 50% aqueous solution of Alkyl Dimethyl Benzyl Ammonium Chloride (ADBAC, CAS 8001-54-5) — a broad-spectrum cationic surfactant and quaternary ammonium biocide manufactured by Vasudev Chemo Pharma. It is the global formulation reference standard for hospital surface disinfectants, food and beverage CIP/COP sanitation, swimming-pool algicides, cosmetic and pharmaceutical preservation, cooling-tower biocide, and agricultural disinfection. Supplied in Industrial / Technical, Cosmetic (CTFA-compliant), and Disinfectant grades from our ISO 9001:2015, GMP, and Halal-certified facility in Gujarat, India.",
    supplySectionHeading:
      "Global Supply of Benzalkonium Chloride 50% (BKC 50%)",
  },
  "benzalkonium-chloride-80": {
    categoryLabel: "Surfactant Chemicals — Benzalkonium Chloride 80% (BKC 80%) Concentrate",
    categorySummary:
      "Benzalkonium Chloride 80% (BKC 80%) is the high-active, export-economical concentrate of Alkyl Dimethyl Benzyl Ammonium Chloride (ADBAC, CAS 8001-54-5) — manufactured by Vasudev Chemo Pharma as a drop-in equivalent to Lonza Bardac® 2280, Stepan BTC® 8358, Nouryon Maquat® 4480-E, and Pilot Lonzabac® 80%. Global disinfectant brands and sanitiser blenders procure 80% concentrate and dilute on-site to 50%, 25%, 10%, or final-use concentrations — saving ~37% freight cost per kilogram of active matter shipped vs BKC 50%. Supplied in Industrial / Technical, Cosmetic (CTFA-compliant), and Disinfectant grades from our ISO 9001:2015, GMP, and Halal-certified facility in Gujarat, India.",
    supplySectionHeading:
      "Global Supply of Benzalkonium Chloride 80% (BKC 80%) Concentrate",
  },
  "p-toluenesulfonic-acid": {
    categoryLabel: "Catalyst Chemicals — p-Toluenesulfonic Acid (PTSA)",
    categorySummary:
      "p-Toluenesulfonic Acid (PTSA, CAS 104-15-4) is a strong organic acid catalyst manufactured by Vasudev Chemo Pharma. It is widely used in organic synthesis, polymer curing (for amino, furan, and phenolic resins), pharmaceutical API manufacturing, and as an acid catalyst in the coatings and plastics industries. Supplied as high-purity crystalline monohydrate with strict moisture controls.",
    supplySectionHeading:
      "Global Supply of p-Toluenesulfonic Acid (PTSA) Catalyst",
  },
  "sodium-cumene-sulfonate-40": {
    categoryLabel: "Surfactant & Hydrotrope Chemicals — Sodium Cumene Sulfonate 40% (SCS 40%)",
    categorySummary:
      "Sodium Cumene Sulfonate 40% (SCS 40%, CAS 28348-53-0) is an aqueous hydrotrope solution manufactured by Vasudev Chemo Pharma. It acts as a solubilizer, coupling agent, and viscosity reducer in liquid laundry detergents, industrial cleaning concentrates, and agrochemical formulations. SCS 40% helps maintain phase stability and low cloud points in surfactant-rich formulations.",
    supplySectionHeading:
      "Global Supply of Sodium Cumene Sulfonate 40% (SCS 40%) Liquid",
  },
  "sodium-cumene-solid-sulfonate-40": {
    categoryLabel: "Surfactant & Hydrotrope Chemicals — Sodium Cumene Sulfonate 40% (SCS 40%)",
    categorySummary:
      "Sodium Cumene Sulfonate 40% (SCS 40%, CAS 28348-53-0) is an aqueous hydrotrope solution manufactured by Vasudev Chemo Pharma. It acts as a solubilizer, coupling agent, and viscosity reducer in liquid laundry detergents, industrial cleaning concentrates, and agrochemical formulations. SCS 40% helps maintain phase stability and low cloud points in surfactant-rich formulations.",
    supplySectionHeading:
      "Global Supply of Sodium Cumene Sulfonate 40% (SCS 40%) Liquid",
  },
  "sodium-cumene-sulfonate-90": {
    categoryLabel: "Surfactant & Hydrotrope Chemicals — Sodium Cumene Sulfonate 90% (SCS 90%) Powder",
    categorySummary:
      "Sodium Cumene Sulfonate 90% (SCS 90%, CAS 28348-53-0) is a high-active, free-flowing hydrotrope powder manufactured by Vasudev Chemo Pharma. It is used as a solubilizing and anti-caking agent in spray-dried powder detergents, automatic dishwasher detergents, and dry agricultural formulations. The 90% active powder is highly optimized for long-haul export, reducing water shipping weight and freight costs.",
    supplySectionHeading:
      "Global Supply of Sodium Cumene Sulfonate 90% (SCS 90%) Powder",
  },
  "sodium-xylene-sulfonate-40": {
    categoryLabel: "Surfactant & Hydrotrope Chemicals — Sodium Xylene Sulfonate 40% (SXS 40%) Liquid",
    categorySummary:
      "Sodium Xylene Sulfonate 40% (SXS 40%, CAS 1300-72-7) is a liquid hydrotrope solution manufactured by Vasudev Chemo Pharma. It is a key formulation ingredient used as a coupling agent, solubilizer, and viscosity control modifier in liquid laundry detergents, dishwashing liquids, shampoo, and personal care products. SXS 40% prevents gel formation and phase separation in highly built electrolyte systems.",
    supplySectionHeading:
      "Global Supply of Sodium Xylene Sulfonate 40% (SXS 40%) Liquid",
  },
  "sodium-xylene-solid-sulfonate-90": {
    categoryLabel: "Surfactant & Hydrotrope Chemicals — Sodium Xylene Sulfonate 90% (SXS 90%) Powder",
    categorySummary:
      "Sodium Xylene Sulfonate 90% (SXS 90%, CAS 1300-72-7) is a high-active hydrotrope powder manufactured by Vasudev Chemo Pharma. Designed for use in powdered detergents, dishwash powders, and dry agricultural formulations as an anti-caking and coupling agent. SXS 90% powder provides excellent export logistics cost-efficiency, eliminating shipped water weights.",
    supplySectionHeading:
      "Global Supply of Sodium Xylene Sulfonate 90% (SXS 90%) Powder",
  },
  "sodium-xylene-sulfonate-90": {
    categoryLabel: "Surfactant & Hydrotrope Chemicals — Sodium Xylene Sulfonate 90% (SXS 90%) Powder",
    categorySummary:
      "Sodium Xylene Sulfonate 90% (SXS 90%, CAS 1300-72-7) is a high-active hydrotrope powder manufactured by Vasudev Chemo Pharma. Designed for use in powdered detergents, dishwash powders, and dry agricultural formulations as an anti-caking and coupling agent. SXS 90% powder provides excellent export logistics cost-efficiency, eliminating shipped water weights.",
    supplySectionHeading:
      "Global Supply of Sodium Xylene Sulfonate 90% (SXS 90%) Powder",
  },
  "bis-2-chloroethyl-amine-hydrochloride": {
    categoryLabel: "Pharmaceutical Intermediates — Bis(2-chloroethyl)amine Hydrochloride",
    categorySummary:
      "Bis(2-chloroethyl)amine Hydrochloride (CAS 821-48-2) is a high-purity pharmaceutical intermediate manufactured by Vasudev Chemo Pharma. It serves as a key heterocyclic building block in the synthesis of oncology drug substances (nitrogen mustards like cyclophosphamide) and other active pharmaceutical ingredients (APIs).",
    supplySectionHeading:
      "Global Supply of Bis(2-chloroethyl)amine Hydrochloride Intermediate",
  },
  "di-ethyl-amino-ethyl-chloride-hydrochloride": {
    categoryLabel: "Pharmaceutical Intermediates — 2-Diethylaminoethyl Chloride Hydrochloride (DEC HCl)",
    categorySummary:
      "2-Diethylaminoethyl Chloride Hydrochloride (DEC HCl / DEAEC HCl, CAS 869-24-9) is a specialty chemical intermediate manufactured by Vasudev Chemo Pharma. It acts as an active alkylating agent in the synthesis of pharmaceutical drugs, including local anesthetics (procaine), cardiovascular agents (amiodarone), and antihistamines.",
    supplySectionHeading:
      "Global Supply of 2-Diethylaminoethyl Chloride Hydrochloride",
  },
  "2-amino-5-methylthiazole": {
    categoryLabel: "Pharmaceutical Intermediates — 2-Amino-5-Methylthiazole (AMIT)",
    categorySummary:
      "2-Amino-5-Methylthiazole (AMIT, CAS 7305-71-7) is a heterocyclic organic intermediate manufactured by Vasudev Chemo Pharma. It is widely utilized as a precursor in the synthesis of pharmaceutical therapeutics and active agrochemical pesticide ingredients.",
    supplySectionHeading:
      "Global Supply of 2-Amino-5-Methylthiazole (AMIT) Intermediate",
  },
  "2-chloroethylamine-hydrochloride": {
    categoryLabel: "Pharmaceutical Intermediates — 2-Chloroethylamine Hydrochloride (CEA HCl)",
    categorySummary:
      "2-Chloroethylamine Hydrochloride (CEA HCl, CAS 870-24-6) is a high-purity organic reagent and intermediate manufactured by Vasudev Chemo Pharma. It is used as an aminoethylating agent in the chemical synthesis of active pharmaceutical ingredients, surfactants, and agricultural crop-protection agents.",
    supplySectionHeading:
      "Global Supply of 2-Chloroethylamine Hydrochloride (CEA HCl)",
  },
  "eddm-non-triazine-h2s-scavenger": {
    categoryLabel: "Non-Triazine H2S Scavengers — EDDM (Ethylene Glycol Bis-Hemiformal)",
    categorySummary:
      "EDDM (Ethylene Glycol Bis-Hemiformal, CAS 3586-55-8) is a non-triazine liquid hydrogen sulfide (H2S) scavenger and oilfield biocide manufactured by Vasudev Chemo Pharma. It removes toxic H2S from natural gas, crude oil, and produced water without the carbonate scaling issues of conventional triazines, making it the preferred choice for offshore platforms and high-scaling environments.",
    supplySectionHeading:
      "Global Supply of EDDM (Non-Triazine) H2S Scavenger",
  },
};

/* ── Keyword grouping patterns ───────────────────────────────────── */

const APPLICATION_PATTERNS: {
  heading: string;
  description: string;
  patterns: RegExp[];
}[] = [
  {
    heading: "Oilfield & Gas Processing Applications",
    description:
      "H2S scavenger chemicals for upstream oil and gas operations, wellhead injection, pipeline treatment, and offshore platforms.",
    patterns: [
      /oilfield|offshore|onshore|drilling|completion|production chemicals|wellhead|pipeline/i,
    ],
  },
  {
    heading: "Refinery & Petrochemical Applications",
    description:
      "H2S scavenger and chemical treatment for refinery overhead, crude oil sweetening, and petrochemical processing operations.",
    patterns: [/refiner|petrochemical|crude oil|sweetening|desalter/i],
  },
  {
    heading: "Biogas & Environmental Applications",
    description:
      "H2S removal from biogas, landfill gas, and wastewater treatment using triazine-based scavenging chemicals.",
    patterns: [/biogas|wastewater|environmental|waste|landfill|sour water/i],
  },
  {
    heading: "Natural Gas & LPG Treatment",
    description:
      "Gas sweetening chemicals for natural gas processing, LPG purification, and gas pipeline integrity.",
    patterns: [/natural gas|lpg|gas processing|gas sweetening/i],
  },
  {
    heading: "Biocide for Metalworking Fluids",
    description:
      "Triazine-based biocide for metalworking fluids — prevents bacterial and fungal growth in cutting fluids, coolants, grinding fluids, and CNC machining coolants. Extends fluid life and eliminates rancid odours.",
    patterns: [/metalworking|cutting fluid|coolant biocide|machining|grinding fluid|cnc/i],
  },
  {
    heading: "Healthcare & Hospital Surface Disinfection",
    description:
      "Quaternary ammonium biocide (ADBAC / Benzalkonium Chloride) for hospital surface disinfection, clinical sanitation, and pharmaceutical-grade healthcare environments. Effective against bacteria, fungi, and enveloped viruses including SARS-CoV-2.",
    patterns: [/hospital|clinical|healthcare|medical|nosocomial|sars|coronavirus|surface disinfect/i],
  },
  {
    heading: "Food & Beverage Industry CIP / COP Sanitation",
    description:
      "FDA 21 CFR 178.1010-compliant no-rinse food-contact sanitiser at 200 ppm active quat. Used in dairy, brewery, soft drink, and food packaging facilities.",
    patterns: [/food contact|cip|cop|dairy|brewery|food.beverage|food.contact|fda 21 cfr/i],
  },
  {
    heading: "Pool, Spa, and Recreational Water Sanitation",
    description:
      "Algaecide and supplementary sanitiser for swimming pools, spas, fountains, and recreational water systems. Synergistic with chlorine.",
    patterns: [/swimming pool|pool algicide|spa water|recreational water|algaecide|algicide/i],
  },
  {
    heading: "Cosmetic and Pharmaceutical Preservation",
    description:
      "INCI-listed cosmetic preservative (max 0.1% rinse-off, 0.05% leave-on per Cosmetics Europe Annex V). USP / BP / EP / IP / JP pharmacopoeia-compliant. Used in eye drops, nasal sprays, hair conditioners, and topical antiseptics.",
    patterns: [/cosmetic preservative|inci|hair conditioner|mouthwash|eye drops|nasal spray|pharmaceutical preservative|topical antiseptic/i],
  },
  {
    heading: "Cooling Tower, HVAC, and Water Treatment Biocide",
    description:
      "Quaternary ammonium biocide for cooling towers, HVAC chillers, and recirculating water systems. Controls Legionella, sulphate-reducing bacteria, and biofilm.",
    patterns: [/cooling tower|hvac|legionella|biofilm|water treatment biocide/i],
  },
  {
    heading: "Agricultural & Veterinary Disinfection",
    description:
      "Biosecurity disinfectant for poultry houses, dairy farms, hatcheries, greenhouses, and foot-baths. Used in livestock, animal husbandry, and crop biosecurity programs.",
    patterns: [/poultry|dairy farm|hatchery|veterinary|livestock|biosecurity|foot.bath|agricultural disinfect/i],
  },
];

const SUPPLY_PATTERNS: {
  heading: string;
  description: string;
  patterns: RegExp[];
}[] = [
  {
    heading: "Bulk Supply & Packaging Options",
    description:
      "Available in 210L drums, 1 MT IBC tanks, ISO tanks, flexitanks, and bulk containers. Factory direct pricing from Gujarat, India.",
    patterns: [
      /drum|ibc|iso tank|flexitank|bulk container|210l|1mt|container|fcl|lcl/i,
    ],
  },
  {
    heading: "Contract Manufacturing & White Label Supply",
    description:
      "Private label, white label, and contract manufacturing services for H2S scavenger chemicals. OEM supply from ISO 9001:2015 certified facility.",
    patterns: [
      /contract manufacturing|white label|private label|tender|govt supplier|msme/i,
    ],
  },
  {
    heading: "Chemical Trading & Procurement",
    description:
      "B2B supply, chemical trading, procurement services, and competitive pricing. Available on IndiaMart, Alibaba, and TradeWheel.",
    patterns: [
      /b2b|trading|procurement|indiamart|alibaba|tradewheel|agent|commission|brokerage|indenting/i,
    ],
  },
];

/* ── Main content builder ────────────────────────────────────────── */

export function getProductKeywordContentSections(
  slug: string
): ProductKeywordContentSections | null {
  const expanded = EXPANDED_KEYWORDS[slug as keyof typeof EXPANDED_KEYWORDS];
  const categoryConfig = CATEGORY_CONTENT[slug];

  if (!expanded || !categoryConfig) return null;

  const allBuying = expanded.buyingIntent;
  const allResearch = expanded.researchBased;
  const allKeywords = [...allBuying, ...allResearch];

  // Build application groups
  const applicationGroups: KeywordContentGroup[] = APPLICATION_PATTERNS.map(
    ({ heading, description, patterns }) => {
      const matchedKeywords = dedupeArray(
        extractByPattern(allKeywords, patterns)
      );
      const items = matchedKeywords.slice(0, 8).map(titleCase);
      return {
        heading,
        description,
        items,
        prose: keywordsToProse(items, description),
      };
    }
  ).filter((g) => g.items.length > 0);

  // Build supply groups
  const supplyGroups: KeywordContentGroup[] = SUPPLY_PATTERNS.map(
    ({ heading, description, patterns }) => {
      const matchedKeywords = dedupeArray(
        extractByPattern(allBuying, patterns)
      );
      const items = matchedKeywords.slice(0, 8).map(titleCase);
      return {
        heading,
        description,
        items,
        prose: keywordsToProse(items, description),
      };
    }
  ).filter((g) => g.items.length > 0);

  // NOTE: We deliberately do NOT generate auto-templated geography groups here.
  // Earlier versions emitted 5 region cards ("Middle East & GCC Supply",
  // "Americas Supply", etc.) where the visible body text for every region was
  // an identical templated sentence — a duplicate-content pattern that adds
  // no user value. Country-level supply context lives on the dedicated
  // /supply/mea-triazine-78/{country} hub pages with unique transit times,
  // ports, and import documentation per market.
  const geographyGroups: KeywordContentGroup[] = [];

  return {
    ...categoryConfig,
    applicationGroups,
    supplyGroups,
    geographyGroups,
  };
}

/**
 * Returns the list of product slugs that have expanded keyword content sections.
 */
export function getExpandedKeywordSlugs(): string[] {
  return Object.keys(EXPANDED_KEYWORDS);
}
