/**
 * Keywords database for metal-working-fluids.
 * Generated automatically.
 */

export const METAL_WORKING_FLUIDS_BUYING_INTENT: string[] = [
  "buy metal working fluid biocide",
  "metal working fluid biocide price india",
  "metal working fluid preservative manufacturer",
  "wholesale metal working fluid biocide exporter",
  "cutting fluid biocide quote",
  "purchase coolant biocide triazine",
  "bulk metal working fluid preservative supplier",
  "triazine biocide price per mt",
  "industrial metal working fluid biocide buy online",
  "best price for metal working fluid biocide",
  "metal working fluid biocide for sale india",
  "top metal working fluid biocide manufacturers india",
  "export metal working fluid biocide to southeast asia",
  "metal working fluid biocide drum price",
  "ibc tank metal working fluid biocide price",
  "metal working fluid biocide chemical supply",
  "cnc coolant biocide buy",
  "metalworking fluid additive price",
  "metal working fluid biocide procurement india",
  "reliable metal working fluid biocide supplier",
  "metal working fluid biocide fcl price",
  "metal working fluid biocide cnf price",
  "metal working fluid biocide fob mundra",
  "metal working fluid biocide lcl shipping",
  "metal working fluid biocide volume discount",
  "cheap metal working fluid biocide chemical",
  "high purity metal working fluid biocide buy",
  "metal working fluid biocide global exporter",
  "metal working fluid biocide technical grade price",
  "metal working fluid biocide machining grade price",
  "metal working fluid biocide contract manufacturing",
  "metal working fluid biocide white label supply",
  "metal working fluid biocide private label chemical",
  "metal working fluid biocide tender price",
  "metal working fluid biocide govt supplier india",
  "metal working fluid biocide manufacturer",
  "metal working fluid biocide iso tank price",
  "metal working fluid biocide bulk drum supply",
  "metal working fluid biocide bulk container price",
  "metal working fluid biocide 50l drum price",
  "metal working fluid biocide 210l drum price",
  "metal working fluid biocide sample request",
  "order metal working fluid biocide online",
  "metal working fluid biocide express delivery",
  "metal working fluid biocide stock availability",
  "metal working fluid biocide ready to ship",
  "metal working fluid biocide factory direct price",
  "metal working fluid biocide b2b supplier",
  "metal working fluid biocide indiamart price",
  "metal working fluid biocide alibaba supplier",
  "metal working fluid biocide tradewheel exporter",
  "metal working fluid biocide chemicals for automotive",
  "metal working fluid biocide aerospace chemicals buy",
  "metal working fluid biocide machining chemicals price",
  "metal working fluid biocide industrial coolant buy",
  "metal working fluid biocide coolant preservation price",
  "metal working fluid biocide cnc additives buy",
  "metal working fluid biocide metal processing chemicals price",
  "metal working fluid biocide factory supply price",
  "metal working fluid biocide chemical quote request",
  "get price list metal working fluid biocide",
  "metal working fluid biocide latest price 2026",
  "metal working fluid biocide market price india",
  "metal working fluid biocide chemical trading",
  "metal working fluid biocide distributor asia",
  "metal working fluid biocide distributor europe",
  "metal working fluid biocide distributor americas",
  "metal working fluid biocide distributor africa",
  "metal working fluid biocide distributor australia",
  "metal working fluid biocide distributor china",
  "metal working fluid biocide distributor japan",
  "metal working fluid biocide distributor korea",
  "metal working fluid biocide distributor germany",
  "metal working fluid biocide distributor italy",
  "metal working fluid biocide distributor france",
  "metal working fluid biocide distributor uk",
  "metal working fluid biocide distributor canada",
  "metal working fluid biocide distributor mexico",
  "metal working fluid biocide distributor brazil",
  "metal working fluid biocide agent in india",
  "metal working fluid biocide commission agent",
  "metal working fluid biocide chemical brokerage",
  "metal working fluid biocide chemical indenting",
  "metal working fluid biocide sourcing agent india",
  "metal working fluid biocide procurement services",
  "metal working fluid biocide chemical logistics",
  "metal working fluid biocide chemical storage price",
  "metal working fluid biocide chemical handling costs",
  "metal working fluid biocide chemical disposal price",
  "metal working fluid biocide handling price",
  "metal working fluid biocide chemical safety audit price",
  "metal working fluid biocide chemical training price",
  "metal working fluid biocide chemical consulting price",
  "metal working fluid biocide chemical analysis price",
  "metal working fluid biocide chemical testing price",
  "metal working fluid biocide quality control price",
  "metal working fluid biocide coa verification price",
  "metal working fluid biocide sds preparation price",
  "metal working fluid biocide reach registration price",
  "metal working fluid biocide tsca compliance price",
  "metal working fluid biocide registration price",
  "metal working fluid biocide label compliance price",
];

export const METAL_WORKING_FLUIDS_RESEARCH_BASED: string[] = [
  "what is metal working fluid biocide",
  "how metal working fluid biocide works",
  "triazine biocide for metal working fluids",
  "metal working fluid biocide chemical formula",
  "metal working fluid biocide cas number",
  "metal working fluid biocide msds",
  "metal working fluid biocide solubility in oil",
  "metal working fluid biocide solubility in water",
  "metal working fluid biocide ph stability",
  "metal working fluid biocide specific gravity",
  "metal working fluid biocide flash point",
  "metal working fluid biocide boiling point",
  "metal working fluid biocide freezing point",
  "metal working fluid biocide viscosity",
  "metal working fluid biocide shelf life",
  "metal working fluid biocide compatibility with metals",
  "metal working fluid biocide corrosion inhibition properties",
  "metal working fluid biocide impact on tool life",
  "metal working fluid biocide odor control mechanism",
  "metal working fluid biocide prevention of rancidity",
  "metal working fluid biocide bacteria control",
  "metal working fluid biocide fungus control",
  "metal working fluid biocide sulfate reducing bacteria",
  "metal working fluid biocide acid producing bacteria",
  "metal working fluid biocide ghs classification",
  "metal working fluid biocide safety precautions",
  "metal working fluid biocide handling guide",
  "metal working fluid biocide storage recommendations",
  "metal working fluid biocide accidental spill response",
  "metal working fluid biocide ppe requirements",
  "metal working fluid biocide stability data",
  "metal working fluid biocide reactivity information",
  "metal working fluid biocide disposal methods",
  "metal working fluid biocide transport regulations",
  "metal working fluid biocide regulatory compliance",
  "metal working fluid biocide use in synthetic coolants",
  "metal working fluid biocide use in semi-synthetic coolants",
  "metal working fluid biocide use in soluble oils",
  "metal working fluid biocide use in neat oils",
  "metal working fluid biocide use in cleaning fluids",
  "metal working fluid biocide dosage calculator",
  "metal working fluid biocide kill rate data",
  "metal working fluid biocide persistence in systems",
  "metal working fluid biocide formaldehyde release mechanism",
  "metal working fluid biocide vs non-formaldehyde biocides",
  "metal working fluid biocide effect of high temperature",
  "metal working fluid biocide effect of high pressure",
  "metal working fluid biocide impact on skin irritation",
  "metal working fluid biocide dermatitis prevention",
  "metal working fluid biocide vs glutaraldehyde",
  "metal working fluid biocide vs isothiazolinone",
  "metal working fluid biocide vs carbamates",
  "metal working fluid biocide advantages in machining",
  "metal working fluid biocide case studies automotive",
  "metal working fluid biocide technical white paper",
  "metal working fluid biocide industrial application review",
  "metal working fluid biocide latest research 2026",
  "metal working fluid biocide innovation in fluid preservation",
  "metal working fluid biocide sustainable machining chemicals",
  "metal working fluid biocide carbon footprint analysis",
  "metal working fluid biocide circular economy machining",
  "metal working fluid biocide waste optimization machining",
  "metal working fluid biocide molecular structure triazine",
  "metal working fluid biocide chemical synonyms triazine",
  "metal working fluid biocide popular trade names triazine",
  "metal working fluid biocide manufacturers list india triazine",
  "metal working fluid biocide global market trends machining",
  "metal working fluid biocide demand forecast 2030",
  "metal working fluid biocide supply chain logistics",
  "metal working fluid biocide manufacturing process triazine",
  "metal working fluid biocide factory setup cost india",
  "metal working fluid biocide raw material sourcing triazine",
  "metal working fluid biocide production optimization triazine",
  "metal working fluid biocide quality standards list triazine",
  "metal working fluid biocide iso 9001 requirements triazine",
  "metal working fluid biocide astm test methods coolants",
  "metal working fluid biocide din standards machining",
  "metal working fluid biocide aerospace standards coolants",
  "metal working fluid biocide automotive standards coolants",
  "metal working fluid biocide safety training for machinist",
  "metal working fluid biocide emergency response machining",
  "metal working fluid biocide risk mitigation factory",
  "metal working fluid biocide hazop study chemical unit",
  "metal working fluid biocide chemical data sheets triazine",
  "metal working fluid biocide thermodynamic properties triazine",
  "metal working fluid biocide kinetic modeling triazine",
  "metal working fluid biocide solubility in metal soaps",
  "metal working fluid biocide partition coefficient oil water",
  "metal working fluid biocide surface tension effects",
  "metal working fluid biocide foaming issues coolants",
  "metal working fluid biocide emulsion stability effects",
  "metal working fluid biocide impact on filtration systems",
  "metal working fluid biocide impact on sumps and pumps",
  "metal working fluid biocide synergistic effect with amines",
  "metal working fluid biocide synergistic effect with copper",
  "metal working fluid biocide interaction matrix coolants",
];

export const METAL_WORKING_FLUIDS_PRIMARY_KEYWORD: string = "metal working fluid biocide manufacturer india";

export const METAL_WORKING_FLUIDS_LONG_TAIL_KEYWORDS: string[] = [
  "metal working fluid preservative supplier",
  "cnc coolant biocide manufacturer",
  "triazine biocide for mwf",
  "cutting fluid odor control chemicals",
  "synthetic coolant biocide supplier",
  "metal working fluid additive manufacturer",
];
