export type SynonymGroup = {
  heading: string;
  items: string[];
};

export type ProductSynonyms = {
  intro: string;
  groups: SynonymGroup[];
  casNote?: string;
  closingText: string;
};

export const MEA_TRIAZINE_SYNONYMS: ProductSynonyms = {
  intro:
    "MEA Triazine 78% is known by many chemical names, IUPAC names, and trade names. Our product is the same compound regardless of the name your specification uses:",
  groups: [
    {
      heading: "IUPAC and Chemical Names",
      items: [
        "Hexahydro-1,3,5-tris(2-hydroxyethyl)-s-triazine",
        "1,3,5-Triazine-1,3,5(2H,4H,6H)-triethanol",
        "2,2',2''-(1,3,5-triazinane-1,3,5-triyl)triethanol",
        "2,2',2''-(hexahydro-1,3,5-triazine-1,3,5-triyl)triethanol",
        "TRIS(N-HYDROXYETHYL) HEXAHYDROTRIAZINE",
        "HEXAHYDRO-1,3,5-TRIS(HYDROXYETHYL)-S-TRIAZINE",
        "1,3,5-Tris(2-hydroxyethyl)hexahydro-1,3,5-triazine",
        "Triazinetriethanol",
        "HHT (Hexahydrotriazine Triethanol)",
      ],
    },
    {
      heading: "Trade Names and Brand Equivalents",
      items: [
        "Grotan BK (equivalent)",
        "J2.219E",
        "MEA based Triazine",
        "MEA Triazine",
        "1,3,5-Triazine",
      ],
    },
    {
      heading: "Application-Based Names",
      items: [
        "H2S Scavenger Chemicals",
        "H2S Scavenger",
        "Hydrogen Sulfide Scavenger",
        "Mercaptan Scavenger",
        "Gas Sweetener / Sweetening Agent",
        "Desulfurizer",
        "Offshore H2S Scavenger",
        "Onshore H2S Scavenger",
        "Triazine H2S Scavenger",
        "Formaldehyde-Releasing Biocide",
        "Industrial Microbiocide / Microbiostat",
        "Slimicide",
        "Bactericide and Algicide",
        "Cutting Fluid Preservative",
        "Anti-mildew Agent",
        "Industrial Preservation Biocide",
      ],
    },
    {
      heading: "Vietnamese-Language Names (Tên tiếng Việt)",
      items: [
        "Chất hấp thụ H2S (H2S Absorbent)",
        "Hóa chất khử hydro sulfide (Hydrogen Sulfide Remover)",
        "Hóa chất xử lý khí chua (Sour Gas Treatment Chemical)",
        "Chất khử lưu huỳnh (Desulfurization Chemical)",
        "Triazine xử lý khí chua (Sour Gas Triazine)",
        "Hóa chất dầu khí MEA Triazine (Oil & Gas Chemical)",
      ],
    },
    {
      heading: "Brand Names Recognized in Vietnam",
      items: [
        "BK Biocide (Chinese trade name, widely traded in SEA)",
        "Dayong MEA Triazine (Dongying Dayong, Made-in-China)",
        "IRO MEA Triazine (IRO Group Inc.)",
        "JDC H2S Scavenger (Jay Dinesh Chemicals)",
        "H2S Scavenger Conc (generic trade description)",
        "MEA-T (Monoethanolamine Triazine abbreviation)",
        "Amine Solution (Q2 Technologies descriptor)",
      ],
    },
    {
      heading: "Brand Names Recognized in the USA",
      items: [
        "Pro3 / Pro3 HT / Pro3 GT / Pro3 NGL (Q2 Technologies)",
        "PureMark M500 / PureMark B800 (Foremark Performance Chemicals)",
        "Enviro-Scrub / Enviro-Scrub Bio (Q2 Technologies)",
        "HSCAV-80 / Kontin (Geocon Products)",
        "HS-1526-40 (Univar Solutions product code)",
        "Sulfa-Check (oilfield trade name)",
        "Bioban GK (Dow Chemical)",
        "Onyxide 200 (Lonza)",
        "Busan 1060 / Busan 1506 (Buckman Laboratories)",
        "Nuosept 78 (industrial preservative)",
        "Protectol HT (BASF)",
        "Triadine 3 / Triadine 10 (Arxada / Lonza)",
        "Troyshield B2 (Troy Chemical)",
      ],
    },
    {
      heading: "Arabic-Language Names (الأسماء العربية)",
      items: [
        "مزيل كبريتيد الهيدروجين (H2S Scavenger)",
        "كاسح H2S (H2S Scavenger)",
        "مادة إزالة كبريتيد الهيدروجين (H2S Removal Substance)",
        "معالجة الغاز الحامض (Sour Gas Treatment)",
        "إزالة الكبريت (Desulfurization)",
        "كيماويات حقول النفط (Oilfield Chemicals)",
        "مبيد حيوي ترايازين (Triazine Biocide)",
      ],
    },
    {
      heading: "Brand Names Recognized in UAE / GCC",
      items: [
        "RXSOL-43-8160-210 (RX Chemicals, UAE/India/Oman)",
        "Saudi Multichem MEA Triazine (Saudi Arabia regional producer)",
        "Geco Chemicals Triazine (UAE, Alibaba-listed)",
        "G-SCAV EA77 (77% active, specialty scavenger)",
        "BASOLON SC 78 (BASF, 78% H2S scavenger)",
        "STEPANQUAT 200 (Stepan Company)",
        "H2Stopper 1908C (specialty H2S scavenger)",
        "SINE PF77 (Chinese manufacturer, multiple variants)",
        "Dorf Ketal (service company, ADNOC JVs)",
        "Scomi Group (regional oilfield services)",
      ],
    },
    {
      heading: "Brand Names Recognized in Oman",
      items: [
        "RXSOL H2S Scavenger (RXSOL-11-5014-210, Oman Chemical)",
        "MC MX 2-1106 (Muscat Chemical, H2S scavenger equivalent)",
        "SULFA-CLEAR™ 8411HC (Lubrizol, 80% MEA Triazine, distributed in Oman)",
        "SULFA-CLEAR™ 8411C (Lubrizol, 60% MEA Triazine)",
        "OS TRI-SCAV (OSS Ltd., triazine-based H2S scavenger)",
        "BASOLON SC 78 (IRO Chemical, regional distribution)",
        "SINE PF77 (IRO Chemical, regional distribution)",
        "MBBT H2S Scavenger (Muscat & Barka Business Trading)",
        "OOISS Triazine (Oman Oil Industry Supplies & Services)",
        "ICPL Triazine H2S Scavenger (Imperial Oilfield Chemicals, exports to Oman)",
      ],
    },
    {
      heading: "Brand Names Recognized in Egypt",
      items: [
        "ACPA H2S Scavenger (Alexandria Company for Petroleum Additives)",
        "AquaNile H2S Scavenger (Giza/Cairo, ethanolamines for gas treating)",
        "MPC H2S Scavenger (Manufacture of Production Chemicals, Alamia Oil Services Group)",
        "Scomi Egypt drilling chemicals (Scomi Group Bhd)",
        "SULFA-CLEAR™ 8411HC (Lubrizol, distributed to Egypt)",
        "ICG MEA Triazine 40/60/77% (International Chemical Group)",
        "Filtron H2S Scavenger (Filtron Envirotech, India — exports to Egypt)",
        "CACIDE 301 (biodegradable triazine biocide, oilfield use)",
      ],
    },
    {
      heading: "Brand Names Recognized in Brazil",
      items: [
        "Global Trend MEA-Triazina 78% (Rio de Janeiro, local supplier)",
        "SCAVTREAT 1063 (Clariant Oil Services, used in Brazil export treatment)",
        "ABATE™ S-200 Scavenger (Dow Chemical, acid gas removal)",
        "Brenntag MEA / Triazine (Brenntag Química Brasil, São Paulo)",
        "SULFA-CLEAR™ 8411HC (Lubrizol, 80% MEA Triazine)",
        "BerrySweet™ 80% (Berryman Chemical, concentrated triazine)",
        "ICS-5780 (International Chemical Group, 77% MEA Triazine)",
        "SLB Triazine H2S Scavenger (Schlumberger, deepwater operations)",
        "Nalco/Ecolab H2S Scavenger (triazine formulations, Ecolab Brasil)",
        "Foscote MEA (Foscote Group, ethanolamines supplier Brazil)",
      ],
    },
    {
      heading: "Brand Names Recognized in Saudi Arabia",
      items: [
        "Chemara HS-1501 (Saudi Multichem, Dammam — local manufacturer)",
        "G-SCAV Triazine H2S Scavenger 78% (Global Company for Chemical Industries, Jubail)",
        "SUGEST H2S Scavenger (Dammam, Aramco approved vendor #10045611)",
        "CHEMAOIL Triazine (amine-based H2S scavenger, KSA)",
        "NassGuard MEA (oilfield chemicals, Dammam/Jubail)",
        "REPC Triazine (Dammam, serves Saudi Aramco)",
        "UCC Triazine (United Chemical Company, Dammam)",
        "Alkemist KSA MEA (Dammam, Eastern Province wholesale)",
        "SABIC® Monoethanolamine (Jubail — MEA raw material)",
        "DubiChem Triazine Biocide (UAE, distributes to KSA)",
        "Cola®Triazine 50 ME (Colonial Chemical, Middle East)",
        "HME-FILM MEA Triazine (MED Drilling Fluids, GCC)",
      ],
    },
    {
      heading: "Brand Names Recognized in Iraq",
      items: [
        "Tawreed H2S Scavenger (Baghdad, ISO-certified oilfield chemicals)",
        "ALDUHA H2S Scavenger (ALDUHA Engineering Group, Basra)",
        "SAHARA MEA Triazine (SAHARA Middle East Petroleum Services, North Rumaila)",
        "Federal Group / Advanced Chemicals (Erbil, Kurdistan Region warehouse)",
        "Sama Alyarmouk Oilfield Chemicals (Baghdad)",
        "Manar Al-Basra Oilfield Services (Basra, est. 2022)",
        "Petrobon MEA (Petrobon Trading, Iran → Iraq import)",
        "Ishtar MEA (Ishtar Company, petroleum/chemicals, Iran/Iraq)",
        "ATDMCO MEA (ATDM Company, UAE/Turkey → Iraq supply)",
        "TAQA Group Chemicals (Iraq, oil & gas chemical distributor)",
        "Falizan HS-9003 (Falizan Tasfyeh, Iran — triazine H2S scavenger)",
        "Xipeng MEA Triazine 78% (Xipeng Technology, China export)",
      ],
    },
    {
      heading: "Brand Names Recognized in Qatar",
      items: [
        "BKC Gulf Triazine Scavenger (Qatar-focused supplier)",
        "RXSOL Triazine Based Biocide (RXSOL-43-8160-210, DubiChem/RX Marine)",
        "DubiChem Triazine Biocide (distributed to GCC incl. Qatar)",
        "HS-1526-40 (Univar Solutions, global triazine product code)",
        "SULFA-CLEAR™ 8411HC (Lubrizol, 80% MEA Triazine)",
        "SULFA-CLEAR™ 8411C (Lubrizol, 60% MEA Triazine)",
        "ChampionX H2S Scavenger (QatarEnergy-approved)",
        "Baker Hughes H2S Scavenger (QatarEnergy-approved)",
        "Halliburton Triazine (QatarEnergy vendor)",
        "Scavtreat (Schlumberger/SLB proprietary blend)",
        "G-SCAV EA77 (77% active, GCC oilfields)",
        "BASOLON SC 78 (IRO Chemical)",
        "SINE PF77 (IRO Chemical)",
        "ICPL Triazine H2S Scavenger (Imperial Oilfield Chemicals, exports to Qatar)",
        "K2P MEA-T (K2P Chemical Products, monoethanolamine triazine)",
        "Deluxe MEA (Deluxe Trading Services WLL, Qatar — raw MEA, not triazine)",
        "Chemway MEA Triazine (UAE/GCC distribution)",
        "JadeScan54 (Jay Dinesh Chemicals, Indian export)",
      ],
    },
    {
      heading: "Qatar Arabic-Language Names (الأسماء العربية – قطر)",
      items: [
        "كاسح كبريتيد الهيدروجين قطر (H2S Scavenger Qatar)",
        "مورد ترايازين قطر (Triazine Supplier Qatar)",
        "مورد مواد كيميائية لمعالجة الغاز قطر (Gas Treatment Chemical Supplier Qatar)",
        "معالجة الغاز الحامض قطر (Sour Gas Treatment Qatar)",
        "كيماويات حقول النفط قطر (Oilfield Chemicals Qatar)",
        "كاسح H2S حقل الشمال (H2S Scavenger North Field)",
        "مزيل كبريتيد الهيدروجين ترايازين قطر (H2S Remover Triazine Qatar)",
        "مورد كيماويات صناعية الدوحة (Industrial Chemical Supplier Doha)",
      ],
    },
    {
      heading: "Brand Names Recognized in Kuwait",
      items: [
        "Bait Al Aseel H₂S Scavenger – Triazine Based (Shuwaikh, Kuwait)",
        "Bait Al Aseel MEA — Monoethanolamine (Kuwait supplier — raw MEA, not triazine)",
        "DK Petrochemicals MEA (Dar Al Kuwait Petrochemical Company — raw MEA)",
        "RXSOL Triazine Based Biocide (RX Chemicals / DubiChem, GCC distribution)",
        "HME-FILM MEA Triazine (MED Drilling Fluids, GCC oilfield use)",
        "HS-1526-40 (Univar Solutions, global triazine product code)",
        "SULFA-CLEAR™ 8411HC (Lubrizol, 80% MEA Triazine)",
        "ChampionX H2S Scavenger (KOC service contracts)",
        "Baker Hughes H2S Scavenger (KOC service contracts)",
        "Dorf Ketal H2S Scavenger (KOC service contracts)",
        "Triasorb® (Sintez-Oka, Russia — MEA triazine H2S absorber)",
        "ICPL Triazine H2S Scavenger (Imperial Oilfield Chemicals, India)",
        "K2P MEA-T (K2P Chemical Products)",
        "Xipeng MEA Triazine 78% (Xipeng Technology, China export)",
        "G-SCAV EA77 (77% active, GCC oilfields)",
        "Sarex HPT Triazine (Sarex Chemicals, India)",
      ],
    },
    {
      heading: "Kuwait Arabic-Language Names (الأسماء العربية – الكويت)",
      items: [
        "كاسح كبريتيد الهيدروجين الكويت (H2S Scavenger Kuwait)",
        "مورد ترايازين الكويت (Triazine Supplier Kuwait)",
        "مادة إزالة H2S لحقول نفط الكويت (H2S Removal for Kuwait Oilfields)",
        "معالجة الغاز الحامض الكويت (Sour Gas Treatment Kuwait)",
        "كيماويات حقول النفط الكويت (Oilfield Chemicals Kuwait)",
        "كاسح H2S حقل برقان (H2S Scavenger Burgan Field)",
        "مورد كيماويات صناعية الأحمدي (Industrial Chemical Supplier Ahmadi)",
        "مزيل كبريتيد الهيدروجين ترايازين الكويت (H2S Remover Triazine Kuwait)",
      ],
    },
    {
      heading: "Brand Names Recognized in Thailand",
      items: [
        "Brenntag MEA (Brenntag Ingredients Thailand, Bangkok — raw MEA, not triazine)",
        "PTT GC MEA (PTT Global Chemical, Map Ta Phut — Thai raw MEA manufacturer)",
        "Krungthep Trading MEA (Bangkok, Thai raw MEA supplier)",
        "Chemipan MEA (retail chemical supplier, Bangkok)",
        "BK Biocide (Chinese trade name, widely traded in SEA)",
        "Dayong MEA Triazine (Dongying Dayong, China export)",
        "IRO MEA Triazine (IRO Group Inc., China export to SEA)",
        "ECHEMI MEA Triazine 78% (Chinese marketplace)",
        "Borregaard H2S Scavenger (Norway, bio-based scavenger)",
        "HS-1526-40 (Univar Solutions, global triazine product code)",
        "SULFA-CLEAR™ 8411HC (Lubrizol, 80% MEA Triazine)",
        "ChampionX H2S Scavenger (PTTEP service contracts)",
        "JDC H2S Scavenger (Jay Dinesh Chemicals, India)",
        "Xipeng MEA Triazine 78% (Xipeng Technology, China export)",
      ],
    },
    {
      heading: "Thai-Language Names (ชื่อภาษาไทย)",
      items: [
        "สารกำจัด H2S ไตรอะซีน (H2S Scavenger Triazine)",
        "สารดักจับไฮโดรเจนซัลไฟด์ (Hydrogen Sulfide Scavenger)",
        "สารบำบัดก๊าซเปรี้ยว (Sour Gas Treatment Agent)",
        "ผู้ผลิต MEA ไตรอะซีน ประเทศไทย (MEA Triazine Manufacturer Thailand)",
        "สารเคมีขจัด H2S สำหรับแก๊สธรรมชาติ (H2S Removal Chemical for Natural Gas)",
        "เคมีภัณฑ์สำหรับอุตสาหกรรมน้ำมันและแก๊ส (Oil & Gas Industry Chemicals)",
        "สารเคมีขจัดไฮโดรเจนซัลไฟด์ก๊าซชีวภาพ (H2S Removal Chemical for Biogas)",
        "สารดักจับ H2S สำหรับแท่นขุดเจาะอ่าวไทย (H2S Scavenger Gulf of Thailand Rigs)",
      ],
    },
    {
      heading: "Brand Names Recognized in Iran",
      items: [
        "Tsorb3400 (Tasfyeh Group, Iran — MEA Triazine H2S scavenger)",
        "Tasfyeh MEA Triazine 80% (Tasfyeh Group, Iran)",
        "Tasfyeh MEA Triazine 60% (Tasfyeh Group, Iran)",
        "Tasfyeh MEA Triazine 50% (Tasfyeh Group, Iran)",
        "Chemical Iran MEA (Chemical Iran, Tehran — raw MEA supplier)",
        "IranChemicalMine MEA (Iran Chemical Mine — raw MEA exporter)",
        "RXSOL Triazine Based Biocide (RX Chemicals / DubiChem, GCC)",
        "Triasorb® (Sintez-Oka, Russia — supply to Iran)",
        "HS-1526-40 (Univar Solutions, global triazine product)",
        "SULFA-CLEAR™ 8411HC (Lubrizol, 80% MEA Triazine)",
        "ChampionX H2S Scavenger (NIOC service contracts)",
        "Baker Hughes H2S Scavenger (NIOC contractors)",
        "ICPL Triazine H2S Scavenger (Imperial Oilfield Chemicals, India)",
        "Sarex HPT Triazine (Sarex Chemicals, India export)",
      ],
    },
    {
      heading: "Farsi (Persian) Names (نام‌های فارسی)",
      items: [
        "حذف‌کننده H2S تری‌آزین (H2S Scavenger Triazine)",
        "حذف‌کننده سولفید هیدروژن ایران (H2S Scavenger Iran)",
        "تری‌آزین تأمین‌کننده ایران (Triazine Supplier Iran)",
        "تصفیه گاز ترش ایران (Sour Gas Treatment Iran)",
        "مواد شیمیایی صنعتی میدان پارس جنوبی (South Pars Industrial Chemicals)",
        "خرید تری‌آزین MEA ایران (Buy MEA Triazine Iran)",
        "تأمین‌کننده مواد شیمیایی بندرعباس (Chemical Supplier Bandar Abbas)",
        "شیمیایی پالایشگاه اصفهان آبادان (Isfahan Abadan Refinery Chemical)",
      ],
    },
    {
      heading: "Brand Names Recognized in Russia",
      items: [
        "Triasorb® (Sintez-Oka, Dzerzhinsk — Russian H2S absorber, 10,000+ tons/yr)",
        "Triasorb® MMA (Sintez-Oka — methylamine triazine variant)",
        "Sintez-Oka MEA (Dzerzhinsk — raw MEA producer since 1948)",
        "Kazanorgsintez MEA (PAO Kazanorgsintez, Kazan — raw MEA technical grade)",
        "Mirrico H2S Scavenger (Mirrico Group, Kazan — largest Russian oilfield chemical co.)",
        "NIKA-Synthetics Triazine (domestic Russian production)",
        "Himeko Triazine (domestic Russian production)",
        "Elarum MEA (Russian ethanolamine distributor, warehouse delivery)",
        "ILEM MEA (Kazanorgsintez distributor, Kazan — wholesale/retail)",
        "Sinotrust MEA Triazine Biocide (Chinese manufacturer, export to Russia/CIS)",
        "Sinolook MEA (Chinese raw MEA, 99% purity)",
        "HME-FILM (ME Drilling Fluids, triazine-based scavenger)",
        "HS-1526-40 (Univar Solutions, global triazine product)",
        "SULFA-CLEAR™ 8411HC (Lubrizol, 80% MEA Triazine)",
      ],
    },
    {
      heading: "Russian-Language Names (Русские названия)",
      items: [
        "нейтрализатор сероводорода триазин (H2S Neutralizer Triazine)",
        "поглотитель H2S триазин МЭА 78% (H2S Absorbent MEA Triazine 78%)",
        "триазин МЭА поставщик Россия (MEA Triazine Supplier Russia)",
        "удаление сероводорода из природного газа (H2S Removal from Natural Gas)",
        "химический реагент очистка попутного газа (Associated Gas Treatment Reagent)",
        "нейтрализатор H2S нефтегазовая промышленность (H2S Neutralizer Oil & Gas)",
        "осушка и очистка газа триазин (Gas Drying & Purification Triazine)",
        "поставщик химических реагентов из Индии (Chemical Reagent Supplier from India)",
      ],
    },
  ],
  casNote: "CAS: 4719-04-4",
  closingText:
    "If your specification, purchase order, or safety requirement lists any of the above names or the CAS number 4719-04-4, Vasudev Chemo Pharma can supply the matching product. Contact us for confirmation and TDS.",
};

export const MMA_TRIAZINE_SYNONYMS: ProductSynonyms = {
  intro:
    "MMA Triazine 40% may be listed under various names in technical specifications:",
  groups: [
    {
      heading: "IUPAC and Chemical Names",
      items: [
        "1,3,5-Trimethylhexahydro-1,3,5-triazine",
        "1,3,5-Trimethyl-1,3,5-triazinane",
        "Hexahydro-1,3,5-trimethyl-s-triazine",
        "sym-Trimethyl-hexahydrotriazine",
        "N,N',N''-Trimethyl-1,3,5-triazinane",
        "Trimethyltriazine",
      ],
    },
    {
      heading: "Synonyms and Application Names",
      items: [
        "H2S Scavenger Chemicals",
        "MMA Triazine",
        "MMA based Triazine",
        "1,3,5-Triazine (MMA variant)",
        "Monomethylamine Triazine",
        "H2S Scavenger (MMA type)",
        "Hydrogen Sulfide Scavenger",
        "Triazine biocide",
        "Industrial biocide for water treatment",
        "Formaldehyde condensate biocide",
        "BTX-free H2S scavenger",
      ],
    },
  ],
  casNote: "CAS Number: 108-74-7",
  closingText:
    "Contact us if your specification lists any of these names — we will confirm whether our MMA Triazine 40% matches your requirement.",
};

export const EDDM_SYNONYMS: ProductSynonyms = {
  intro:
    "EDDM (Ethylenedioxydimethanol) is known by several chemical names, trade names, and application-based names. Our product is the same compound regardless of the name your specification uses:",
  groups: [
    {
      heading: "IUPAC and Chemical Names",
      items: [
        "(Ethylenedioxy)dimethanol",
        "Ethylenedioxydimethanol",
        "1,6-Dihydroxy-2,5-dioxahexane",
        "2-Methyloloxyethoxymethanol",
        "Ethylene glycol hemiacetal",
        "Bis(hydroxymethyl)-1,4-dioxane-2,5-diol",
        "HOCH₂OCH₂CH₂OCH₂OH",
      ],
    },
    {
      heading: "Trade Names and Abbreviations",
      items: [
        "EDDM",
        "Non-Triazine H2S Scavenger",
        "Non-Triazine Based H2S Scavenger",
        "Formaldehyde-Based H2S Scavenger",
        "Non-Amine H2S Scavenger",
        "Glycol Hemiacetal Scavenger",
      ],
    },
    {
      heading: "Application-Based Names",
      items: [
        "Non-Triazine Desulfurizer",
        "Slow-Release Bactericide",
        "Formaldehyde Donor Biocide",
        "In-Can Preservative",
        "Non-Triazine Gas Sweetener",
        "H2S Scavenger (Non-Triazine Type)",
        "Hydrogen Sulfide Scavenger (Formaldehyde-Based)",
        "Water Treatment Biocide EDDM",
        "Metalworking Fluid Preservative",
        "Oil/Water Separation Agent",
      ],
    },
    {
      heading: "SEO Meta Titles (Alternate Page Titles)",
      items: [
        "Non-Triazine Based H2S Scavenger | EDDM Manufacturer India",
        "EDDM Manufacturer in India | Ethylenedioxydimethanol Supplier",
        "Buy EDDM Non-Triazine H2S Scavenger | Best Price from India",
        "Ethylenedioxydimethanol (EDDM) CAS 3586-55-8 | Bulk Supplier",
        "Non-Triazine H2S Scavenger for Oil & Gas | EDDM Exporter India",
      ],
    },
  ],
  casNote: "CAS Number: 3586-55-8 | EINECS: 222-720-6",
  closingText:
    "Contact us if your specification lists any of these names — we will confirm whether our EDDM Non-Triazine H2S Scavenger matches your requirement.",
};


export const BENZALKONIUM_CHLORIDE_SYNONYMS: ProductSynonyms = {
  intro:
    "Benzalkonium Chloride (BKC) is sold globally under dozens of chemical names, IUPAC variants, and trade names. Vasudev Chemo Pharma's BKC 50% and BKC 80% are the same active substance regardless of which name your specification, MSDS, or purchase order uses:",
  groups: [
    {
      heading: "IUPAC and Chemical Names",
      items: [
        "Alkyl Dimethyl Benzyl Ammonium Chloride",
        "Alkyl(C8-C18) Dimethyl Benzyl Ammonium Chloride",
        "Alkyl Dimethyl Benzyl Ammonium Chloride (ADBAC)",
        "Benzyl Dimethyl Alkyl Ammonium Chloride",
        "N-Alkyl-N,N-Dimethyl-N-Benzyl Ammonium Chloride",
        "Benzyl Dimethyl C12-C16 Alkyl Ammonium Chloride",
        "Alkyl Benzyldimethylammonium Chloride",
        "Alkyldimethylbenzylammonium Chloride",
        "Quaternary Ammonium Compound, Benzyl-C8-18-Alkyldimethyl, Chloride",
        "Quaternary Ammonium Compounds, Benzyl-(C12-C16)-alkyldimethyl Chlorides",
        "Benzene methanaminium, alkyl-dimethyl-, chloride",
        "Benzenemethanaminium, N-alkyl-N,N-dimethyl-, chloride",
        "Benzyldimethyl(C8-C18)alkylammonium Chloride",
        "Benzyl(dodecyl)dimethylammonium Chloride",
        "Benzyl(tetradecyl)dimethylammonium Chloride",
        "Benzyl(hexadecyl)dimethylammonium Chloride",
      ],
    },
    {
      heading: "Common Abbreviations and Synonyms",
      items: [
        "BKC",
        "BAC",
        "BZK",
        "BZC",
        "ADBAC",
        "BAK",
        "BACL",
        "Quat-12",
        "Quat-14",
        "Quat-16",
        "C12-Quat",
        "C14-Quat",
        "C16-Quat",
        "DMBAC (Dimethyl Benzyl Ammonium Chloride)",
        "BDBAC (Benzyl Dimethyl Benzyl Ammonium Chloride)",
      ],
    },
    {
      heading: "Trade Names and Brand Equivalents",
      items: [
        "Lonza Bardac® 22 (50% BKC equivalent)",
        "Lonza Bardac® 2280 (80% BKC equivalent)",
        "Lonza Hyamine® 3500 (50% BKC equivalent)",
        "Stepan BTC® 824 (50% BKC equivalent)",
        "Stepan BTC® 8358 (80% BKC equivalent)",
        "Stepan BTC® 50NF",
        "Nouryon (AkzoNobel) Maquat® 2280 (80% BKC equivalent)",
        "Nouryon Maquat® MC 1412 (50% BKC equivalent)",
        "Nouryon Maquat® 4480-E",
        "Pilot Lonzabac® 80% (80% BKC equivalent)",
        "Pilot Lonzabac® 50",
        "Kao Sanisol® C (BKC equivalent)",
        "Kao Quartamin® 50",
        "BASF Cetrimonium Quat (cosmetic-grade BKC equivalent)",
        "Solvay Mirapol® Surf-S (BKC blend)",
        "Croda Crodaquat® BAC (50% BKC)",
        "Sigma-Aldrich BC 234245 (50% BKC reagent)",
        "Sigma-Aldrich BC 12060 (80% BKC reagent)",
        "Roquat® 50 / Roquat® 80",
        "Aliquat® 336 (related but distinct quat)",
      ],
    },
    {
      heading: "Application-Based Names",
      items: [
        "Quaternary Ammonium Disinfectant",
        "Quaternary Ammonium Compound (Quat / QAC)",
        "Cationic Surfactant",
        "Cationic Biocide",
        "Hospital Surface Disinfectant",
        "Hard Surface Sanitiser",
        "Food Contact Surface Sanitiser",
        "Pool & Spa Algicide",
        "Algaecide for Cooling Towers",
        "HVAC Biocide",
        "Cosmetic Preservative (CTFA-listed Benzalkonium Chloride)",
        "Pharmaceutical Preservative (Benzalkonium Chloride NF / Ph.Eur.)",
        "Eye Drop Preservative",
        "Nasal Spray Preservative",
        "Skin Antiseptic Active",
        "Wood Preservative",
        "Veterinary Disinfectant",
        "Poultry House Disinfectant",
        "Dairy Farm Disinfectant",
        "Hatchery Foot-Bath Disinfectant",
        "Phase-Transfer Catalyst",
        "Cationic Softener Base",
        "Antimicrobial Textile Finish",
        "Oilfield Biocide for Microbial Control",
        "Sour Service Biocide",
      ],
    },
    {
      heading: "Pharmacopoeia and Regulatory References",
      items: [
        "Benzalkonium Chloride USP",
        "Benzalkonium Chloride NF",
        "Benzalkonium Chloride BP",
        "Benzalkonium Chloride EP / Ph. Eur.",
        "Benzalkonium Chloride IP (Indian Pharmacopoeia)",
        "Benzalkonium Chloride JP (Japanese Pharmacopoeia)",
        "EPA-registered antimicrobial active ingredient",
        "EPA Registration Reference: PC Code 069105",
        "EU BPR Approved Active Substance (Product Types 1, 2, 3, 4)",
        "FDA OTC Monograph antiseptic active ingredient",
        "ECHA REACH Pre-registered Substance",
        "INCI Name: Benzalkonium Chloride (cosmetic ingredient nomenclature)",
        "CTFA-listed cosmetic preservative",
        "FDA 21 CFR 178.1010 sanitising solutions for food-contact surfaces",
      ],
    },
    {
      heading: "Regional / Language Variants",
      items: [
        "Cloruro de Benzalconio (Spanish — for Latin America export)",
        "Cloreto de Benzalcônio (Portuguese — for Brazil export)",
        "Chlorure de Benzalkonium (French)",
        "Benzalkoniumchlorid (German)",
        "塩化ベンザルコニウム (Japanese — Enka Benzarukoniumu)",
        "苯扎氯铵 (Simplified Chinese — Benzha Lü'an)",
        "Бензалкония хлорид (Russian — Benzalkoniya Khlorid)",
        "كلوريد البنزالكونيوم (Arabic — for Middle East export to UAE, Saudi Arabia, Egypt)",
        "Benzalkonyum Klorür (Turkish)",
        "Clorua Benzalkonium (Vietnamese)",
        "Benzalkonyumchloride (Dutch)",
        "Cloruro di Benzalconio (Italian)",
      ],
    },
    {
      heading: "SEO Meta Titles (Alternate Page Titles)",
      items: [
        "Benzalkonium Chloride 50% Manufacturer India | BKC 50% Supplier",
        "Benzalkonium Chloride 80% Manufacturer India | BKC 80% Concentrate",
        "Buy BKC 50% Liquid (CAS 8001-54-5) | ADBAC Quat Disinfectant",
        "ADBAC 50% / 80% Manufacturer India | Quaternary Ammonium Biocide",
        "Lonza Bardac® 2280 Equivalent | BKC 80% from Vasudev Chemo Pharma",
        "Stepan BTC® 8358 Alternative | BKC 80% Indian Manufacturer",
        "Nouryon Maquat® 4480-E Alternative | BKC 80% Bulk Export",
        "Quat-12 / Quat-14 BKC Manufacturer | Hospital Disinfectant Active",
        "Cosmetic Grade Benzalkonium Chloride | CTFA-Compliant Preservative",
        "Disinfectant Grade BKC for EPA-Registered Formulators | India Export",
      ],
    },
  ],
  casNote: "CAS Number: 8001-54-5 (mixture) | Also: 63449-41-2, 68391-01-5, 68424-85-1 (chain-specific) | EC: 264-151-6, 269-919-4 | HS: 29239000",
  closingText:
    "If your specification, purchase order, MSDS, formulation manual, or regulatory filing lists any of the above names, abbreviations, brand equivalents, or pharmacopoeia references, Vasudev Chemo Pharma can supply the matching product. Both BKC 50% and BKC 80% are available in Industrial / Technical Grade, Cosmetic Grade (CTFA-compliant), and Disinfectant Grade (suitable for EPA-registered formulators), with ISO 9001:2015, GMP, and Halal certification. Contact us for COA, SDS, samples, and trade-equivalence confirmation.",
};

export const SODIUM_XYLENE_SULFONATE_SYNONYMS: ProductSynonyms = {
  intro:
    "Sodium Xylene Sulfonate (SXS) is referenced across formulation, regulatory and customs systems by multiple chemical names, trade equivalents, and brand names. Our product is the same active substance regardless of your specification requirements:",
  groups: [
    {
      heading: "IUPAC and Chemical Names",
      items: [
        "Sodium xylenesulfonate",
        "Sodium xylene sulphonate",
        "Sodium dimethylbenzenesulfonate",
        "3,4-Xylenesulfonic acid sodium salt",
        "Sodium o-xylene-4-sulfonate",
        "Xylenesulfonic acid sodium salt",
        "Dimethylbenzenesulfonic acid sodium salt",
        "SXS",
        "SXS-40",
        "SXS 40%",
        "SXS-90",
        "SXS 90%",
      ],
    },
    {
      heading: "Trade Names and Brand Equivalents",
      items: [
        "Naxonate",
        "Naxonate G",
        "Naxonate SX",
        "Stepanate X",
        "Stepanate SXS",
        "Richonate SXS",
        "Cyclophil SXS 30",
        "Conco SXS",
        "Surco SXS",
        "Ultrawet 40SX",
        "Eltesol SX 30",
        "Eltesol SX 93",
        "Witconate SXS",
        "Calsoft SXS 96",
        "Reworyl NXS40",
        "Alkatrope SX-40",
        "Carsosulf SXS",
        "Kemmat SN 18",
        "Spolapon XS NaP",
        "ELSURFAC™-NaXS",
        "GARDILENE SX40AU",
        "Kualimate SXS 40",
        "Zeonol 40",
        "DOLSX-40",
      ],
    },
  ],
  casNote: "CAS Number: 1300-72-7 | EINECS: 215-090-9 | HS Code: 29041090",
  closingText:
    "If your specification, MSDS, formulation manual, or customs filing lists any of the above names or the CAS number 1300-72-7, Vasudev Chemo Pharma can supply the matching product. We provide both 40% liquid and 90% powder grades in bulk drums, IBC totes, and container loads. Contact us for COA, SDS, samples, and specification alignment.",
};

export const TRIAZINE_SCAVENGER_GENERAL_SYNONYMS: ProductSynonyms = {
  intro:
    "Triazine Based H2S Scavengers are supplied under several chemical names, designations, and application terms. Our product portfolio meets the requirements of the following specifications:",
  groups: [
    {
      heading: "IUPAC and Chemical Names",
      items: [
        "Hexahydro-1,3,5-tris(2-hydroxyethyl)-s-triazine",
        "1,3,5-Trimethylhexahydro-1,3,5-triazine",
        "1,3,5-Triazine-1,3,5(2H,4H,6H)-triethanol",
        "2,2',2''-(1,3,5-triazinane-1,3,5-triyl)triethanol",
        "Triazinetriethanol",
        "Hexahydrotriazine Triethanol (HHT)",
        "sym-Trimethyl-hexahydrotriazine",
      ],
    },
    {
      heading: "Generic and Trade Names",
      items: [
        "MEA Triazine",
        "MMA Triazine",
        "Triazine H2S Scavenger",
        "Triazine Biocide",
        "Amine-based H2S Scavenger",
        "Formaldehyde Condensate Biocide",
      ],
    },
    {
      heading: "Application Names",
      items: [
        "Hydrogen Sulfide Scavenger",
        "Mercaptan Scavenger",
        "Sour Gas Sweetener / Sweetening Agent",
        "Gas Desulfurizer",
        "Offshore and Onshore H2S Scavenger",
        "Pipeline Corrosion Inhibitor and Scavenger Blend",
      ],
    },
  ],
  casNote: "CAS Numbers: 4719-04-4 (MEA Based) / 108-74-7 (MMA Based)",
  closingText:
    "If your specification lists any of the above names or the CAS numbers 4719-04-4 or 108-74-7, Vasudev Chemo Pharma can supply the matching grade. Contact us for a quote.",
};

export const METAL_WORKING_FLUIDS_SYNONYMS: ProductSynonyms = {
  intro:
    "Triazine-based metalworking fluid biocides are known by several synonyms and application titles in industrial machining, formulating, and preservation sectors:",
  groups: [
    {
      heading: "IUPAC and Chemical Names",
      items: [
        "Hexahydro-1,3,5-tris(2-hydroxyethyl)-s-triazine",
        "1,3,5-Triazine-1,3,5(2H,4H,6H)-triethanol",
        "2,2',2''-(hexahydro-1,3,5-triazine-1,3,5-triyl)triethanol",
        "Triazinetriethanol",
      ],
    },
    {
      heading: "Trade and Brand Equivalents",
      items: [
        "Grotan BK (equivalent)",
        "Bioban GK (equivalent)",
        "Onyxide 200 (equivalent)",
        "Triadine 3 / Triadine 10 (equivalent)",
        "Troyshield B2 (equivalent)",
        "Protectol HT (equivalent)",
      ],
    },
    {
      heading: "Application Names",
      items: [
        "Metalworking Fluid Preservative",
        "MWF Biocide",
        "Cutting Fluid Preservative",
        "Coolant Microbiocide",
        "Formaldehyde-Releasing Biocide",
        "In-Can Preservative for Alkaline Systems",
        "CNC Fluid Odor Control Agent",
      ],
    },
  ],
  casNote: "CAS Number: 4719-04-4 | EC Number: 225-208-0",
  closingText:
    "If your formulation manual or raw material specification lists these synonyms, Vasudev Chemo Pharma can supply equivalent grades. Contact us for technical support.",
};

export const BIOCIDE_OIL_GAS_SYNONYMS: ProductSynonyms = {
  intro:
    "Oil & Gas biocides, primarily triazine-based, are marketed and specified under various generic and application-specific chemical terms globally:",
  groups: [
    {
      heading: "Chemical and IUPAC Names",
      items: [
        "Hexahydro-1,3,5-tris(2-hydroxyethyl)-s-triazine",
        "1,3,5-Triazine-1,3,5(2H,4H,6H)-triethanol",
        "Triazinetriethanol",
        "Formaldehyde-Amine Condensate",
      ],
    },
    {
      heading: "Application-Based Names",
      items: [
        "Oilfield Biocide",
        "Sulfate-Reducing Bacteria (SRB) Biocide",
        "Acid-Producing Bacteria (APB) Biocide",
        "Water Injection System Sanitizer",
        "Produced Water Biocide",
        "Hydrostatic Test Biocide",
        "Fracturing Fluid Microbiocide",
        "Pipeline Preservation Biocide",
      ],
    },
    {
      heading: "Trade and Brand References",
      items: [
        "Grotan BK (equivalent)",
        "Onyxide 200 (equivalent)",
        "Bioban GK (equivalent)",
        "Protectol HT (equivalent)",
      ],
    },
  ],
  casNote: "CAS Number: 4719-04-4 | EC Number: 225-208-0",
  closingText:
    "Vasudev Chemo Pharma supplies high-efficiency biocides tailored for oilfield microbial control. Contact us to align specifications or request samples.",
};

export const MEA_TRIAZINE_78_HIGH_CONC_SYNONYMS: ProductSynonyms = {
  intro:
    "MEA Triazine 78% (High Concentration) is referenced in international logistics, trade, and engineering specifications under several synonyms and equivalent titles:",
  groups: [
    {
      heading: "Chemical and IUPAC Names",
      items: [
        "Hexahydro-1,3,5-tris(2-hydroxyethyl)-s-triazine (78% Active Matter)",
        "1,3,5-Triazine-1,3,5(2H,4H,6H)-triethanol (78% Solution)",
        "2,2',2''-(1,3,5-triazinane-1,3,5-triyl)triethanol",
        "Triazinetriethanol 78%",
      ],
    },
    {
      heading: "Trade Names and Brand Equivalents",
      items: [
        "MEA Triazine 78% Solution",
        "High-Active MEA Triazine",
        "MEA based Triazine 78%",
        "BASOLON SC 78 (equivalent)",
        "Sulfa-Clear 8411HC (equivalent)",
        "G-SCAV EA77 (equivalent)",
      ],
    },
    {
      heading: "Application-Based Names",
      items: [
        "High-Concentration H2S Scavenger",
        "Export-Grade Hydrogen Sulfide Scavenger",
        "Offshore H2S Scavenger Solution",
        "Biogas Desulfurization Agent",
        "Wastewater H2S Neutralizer",
      ],
    },
  ],
  casNote: "CAS Number: 4719-04-4 | HS Code: 29336990",
  closingText:
    "If your specification demands high-concentration MEA Triazine (78% active), Vasudev Chemo Pharma can supply the matching grade in drums, IBCs, or ISO tanks. Contact us today.",
};

