/**
 * Keywords database for sodium-cumene-sulfonate-40.
 * Generated automatically.
 */

export const SCS_40_BUYING_INTENT: string[] = [
  "buy sodium cumene sulfonate 40",
  "buy sodium cumene sulfonate 40%",
  "buy sodium cumene sulfonate 40 liquid",
  "buy sodium cumene sulphonate 40",
  "buy SCS 40",
  "buy SCS-40",
  "buy SCS 40 liquid",
  "buy SCS 40 hydrotrope",
  "purchase sodium cumene sulfonate 40",
  "purchase SCS 40 bulk",
  "order sodium cumene sulfonate 40",
  "order SCS 40 online",
  "sodium cumene sulfonate 40 for sale",
  "SCS 40 for sale india",
  "sodium cumene sulfonate 40 wholesale",
  "SCS 40 wholesale price",
  "sodium cumene sulfonate 40 bulk order",
  "SCS 40 drum purchase",
  "SCS 40 IBC purchase",
  "SCS 40 tanker order",
  "SCS 40 sample request",
  "SCS 40 free sample",
  "SCS 40 trial order",
  "SCS 40 spot purchase",
  "SCS 40 container load",
  "SCS 40 procurement",
  "SCS 40 quick quote",
  "buy liquid hydrotrope SCS 40",
  "order sodium cumene sulphonate liquid",
  "sodium cumene sulfonate 40 manufacturer",
  "sodium cumene sulfonate 40 manufacturer india",
  "sodium cumene sulfonate 40 manufacturer gujarat",
  "sodium cumene sulfonate 40 manufacturer ankleshwar",
  "sodium cumene sulfonate 40 manufacturer ahmedabad",
  "sodium cumene sulfonate 40 manufacturer surat",
  "sodium cumene sulfonate 40 manufacturer vadodara",
  "sodium cumene sulfonate 40 manufacturer mumbai",
  "sodium cumene sulfonate 40 manufacturer vapi",
  "sodium cumene sulfonate 40 manufacturer dahej",
  "sodium cumene sulfonate 40 manufacturers in india",
  "sodium cumene sulfonate 40 manufacturers in gujarat",
  "sodium cumene sulphonate 40 manufacturer in india",
  "sodium cumene sulphonate 40 manufacturer in gujarat",
  "scs 40 manufacturer india",
  "scs 40 manufacturer gujarat",
  "scs 40 manufacturer ankleshwar",
  "scs 40 manufacturer ahmedabad",
  "sodium cumene sulfonate 40 supplier",
  "sodium cumene sulfonate 40 supplier india",
  "sodium cumene sulfonate 40 supplier gujarat",
  "sodium cumene sulfonate 40 supplier mumbai",
  "sodium cumene sulfonate 40 supplier ahmedabad",
  "sodium cumene sulfonate 40 supplier ankleshwar",
  "sodium cumene sulphonate 40 supplier in india",
  "sodium cumene sulphonate 40 supplier in gujarat",
  "sodium cumene sulfonate 40 suppliers in india",
  "sodium cumene sulfonate 40 suppliers in gujarat",
  "scs 40 supplier india",
  "scs 40 supplier gujarat",
  "scs 40 supplier mumbai",
  "sodium cumene sulfonate 40 exporter",
  "sodium cumene sulfonate 40 exporter india",
  "sodium cumene sulfonate 40 exporter gujarat",
  "sodium cumene sulfonate 40 exporters in india",
  "scs 40 exporter india",
  "scs 40 exporter gujarat",
  "sodium cumene sulfonate 40 distributor",
  "sodium cumene sulfonate 40 stockist",
  "sodium cumene sulfonate 40 dealer",
  "sodium cumene sulfonate 40 wholesaler",
  "sodium cumene sulfonate 40 trading company",
  "sodium cumene sulfonate 40 OEM supplier",
  "sodium cumene sulfonate 40 private label manufacturer",
  "sodium cumene sulfonate 40 contract manufacturer",
  "sodium cumene sulfonate 40 toll manufacturer",
  "sodium cumene sulfonate 40 ISO certified supplier",
  "scs 40 ISO 9001 manufacturer",
  "scs 40 GMP manufacturer",
  "scs 40 verified supplier",
  "scs 40 trusted manufacturer india",
  "scs 40 reliable supplier gujarat",
  "eltesol sc 40 alternative india",
  "eltesol sc 40 supplier alternative",
  "eltesol sc 40 manufacturer alternative",
  "stepanate scs alternative",
  "stepanate scs 40 alternative india",
  "stepanate scs-40e alternative",
  "stepan scs 40 supplier alternative",
  "naxonate sc alternative india",
  "naxonate scs supplier alternative",
  "witconate scs alternative",
  "calsoft scs alternative",
  "ultrawet scs alternative",
  "teric 12a3n alternative",
  "scsdol-40 alternative",
  "scsdol 40 dolphin alternative",
  "neosol 40 alternative india",
  "mahanol scs-40 alternative",
  "mahavir expochem scs 40 alternative",
  "nln-scs 40 alternative",
  "unisurf sc 40 alternative",
  "unisurf scs alternative",
  "ariix sodium cumene sulfonate alternative",
  "nico orgo sodium cumenesulfonate alternative",
  "shinde chemicals sodium cumene sulfonate alternative",
  "navdeep scs-40 alternative",
  "nandadeep scs alternative",
  "dolphin pharma scs alternative",
  "duorganics sodium cumene sulfonate 40 alternative",
  "scimplify sodium cumene sulfonate alternative",
  "mallak chemicals sodium cumene sulfonate alternative",
  "kk india petroleum specialities scs alternative",
  "albright sodium cumene sulfonate alternative",
  "tennants distribution scs alternative",
  "sodium cumene sulfonate 40 price",
  "sodium cumene sulfonate 40 price india",
  "sodium cumene sulfonate 40 price per kg",
  "sodium cumene sulfonate 40 price per ton",
  "sodium cumene sulfonate 40 price per mt",
  "sodium cumene sulfonate 40 price per drum",
  "sodium cumene sulfonate 40 price per ibc",
  "sodium cumene sulfonate 40 price list",
  "sodium cumene sulfonate 40 price list 2026",
  "sodium cumene sulfonate 40 price list 2027",
  "sodium cumene sulfonate 40 market price",
  "sodium cumene sulfonate 40 wholesale price",
  "sodium cumene sulfonate 40 bulk price",
  "sodium cumene sulfonate 40 factory price",
  "sodium cumene sulfonate 40 fob price",
  "sodium cumene sulfonate 40 cif price",
  "sodium cumene sulfonate 40 ex works price",
  "sodium cumene sulfonate 40 cnf price",
  "sodium cumene sulfonate 40 best price india",
  "sodium cumene sulfonate 40 cheap price",
  "sodium cumene sulfonate 40 discount price",
  "sodium cumene sulfonate 40 latest price",
  "scs 40 price",
  "scs 40 price per kg",
  "scs 40 price per ton",
  "scs 40 price india",
  "scs 40 quotation",
  "scs 40 quote",
  "scs 40 rfq",
  "scs 40 fob mundra",
  "scs 40 fob nhava sheva",
  "scs 40 ex-works ahmedabad",
  "scs 40 cif jebel ali",
  "scs 40 cif jeddah",
  "scs 40 cif rotterdam",
  "scs 40 minimum order quantity",
  "scs 40 moq",
  "scs 40 1 mt moq",
  "scs 40 5 mt price",
  "scs 40 10 mt price",
  "scs 40 20 mt fcl price",
  "scs 40 sample price",
  "scs 40 trial price",
  "scs 40 240 kg drum supplier",
  "scs 40 240 kg hdpe drum price",
  "scs 40 1000 l ibc tank price",
  "scs 40 ibc supplier india",
  "scs 40 bulk tanker delivery",
  "scs 40 iso tank supplier",
  "scs 40 iso tank price",
  "scs 40 flexitank supply",
  "scs 40 220 l drum price",
  "scs 40 25 kg can price",
  "scs 40 packaging options",
  "scs 40 custom packaging",
  "sodium cumene sulfonate 40 hdpe drum manufacturer",
  "sodium cumene sulfonate 40 ibc tank manufacturer",
  "sodium cumene sulfonate 40 bulk tanker price",
  "sodium cumene sulfonate 40 indiamart",
  "sodium cumene sulfonate 40 tradeindia",
  "sodium cumene sulfonate 40 justdial",
  "sodium cumene sulfonate 40 exportersindia",
  "sodium cumene sulfonate 40 alibaba",
  "sodium cumene sulfonate 40 made-in-china",
  "sodium cumene sulfonate 40 tradewheel",
  "sodium cumene sulfonate 40 b2b",
  "sodium cumene sulfonate 40 b2b supplier india",
  "sodium cumene sulfonate 40 verified supplier",
  "scs 40 indiamart",
  "scs 40 tradeindia",
  "scs 40 alibaba",
  "scs 40 b2b",
  "scs 40 direct manufacturer india",
  "scs 40 direct factory price",
  "scs 40 trusted supplier",
  "scs 40 gold supplier",
  "scs 40 supplier ankleshwar",
  "scs 40 supplier bharuch",
  "scs 40 supplier vadodara",
  "scs 40 supplier ahmedabad",
  "scs 40 supplier surat",
  "scs 40 supplier mumbai",
  "scs 40 supplier vapi",
  "scs 40 supplier dahej",
  "scs 40 supplier kandla",
  "scs 40 exporter mundra",
  "scs 40 exporter nhava sheva",
  "scs 40 exporter mumbai port",
  "scs 40 exporter kandla port",
  "scs 40 exporter pipavav",
  "scs 40 exporter hazira",
  "scs 40 trader india",
  "scs 40 distributor india",
  "buy scs 40 in uae",
  "buy scs 40 in dubai",
  "buy scs 40 in abu dhabi",
  "buy scs 40 in saudi arabia",
  "buy scs 40 in jeddah",
  "buy scs 40 in dammam",
  "buy scs 40 in oman",
  "buy scs 40 in qatar",
  "buy scs 40 in kuwait",
  "buy scs 40 in iraq",
  "buy scs 40 in egypt",
  "buy scs 40 in turkey",
  "buy scs 40 in russia",
  "buy scs 40 in usa",
  "buy scs 40 in brazil",
  "buy scs 40 in vietnam",
  "buy scs 40 in thailand",
  "buy scs 40 in indonesia",
  "buy scs 40 in malaysia",
  "buy scs 40 in philippines",
  "buy scs 40 in nigeria",
  "buy scs 40 in china",
  "buy scs 40 in europe",
  "buy scs 40 in germany",
  "scs 40 supplier uae",
  "scs 40 supplier saudi arabia",
  "scs 40 supplier oman",
  "scs 40 supplier qatar",
  "scs 40 supplier kuwait",
  "scs 40 supplier iraq",
  "scs 40 supplier egypt",
  "scs 40 supplier turkey",
  "scs 40 supplier russia",
  "scs 40 supplier usa",
  "scs 40 supplier brazil",
  "scs 40 supplier vietnam",
  "scs 40 supplier thailand",
  "scs 40 supplier indonesia",
  "scs 40 exporter to uae",
  "scs 40 exporter to saudi arabia",
  "scs 40 exporter to usa",
  "scs 40 exporter to europe",
  "scs 40 export india to gulf",
  "scs 40 export india to africa",
  "scs 40 for liquid detergent manufacturers",
  "scs 40 for dish wash formulators",
  "scs 40 for laundry liquid manufacturers",
  "scs 40 for shampoo formulators",
  "scs 40 for body wash formulators",
  "scs 40 for personal care manufacturers",
  "scs 40 for agrochemical formulators",
  "scs 40 for pesticide formulators",
  "scs 40 for herbicide formulators",
  "scs 40 for oilfield service companies",
  "scs 40 for drilling fluid formulators",
  "scs 40 for metalworking fluids",
  "scs 40 for electroplating chemicals",
  "scs 40 for zinc plating brighteners",
  "scs 40 for textile auxiliaries",
  "scs 40 for paint coupling agents",
  "scs 40 for printing inks",
  "scs 40 for industrial cleaners",
  "scs 40 for hard surface cleaners",
  "scs 40 for floor strippers",
  "scs 40 for wax cleaners",
  "scs 40 for car wash concentrates",
  "scs 40 for kitchen cleaner concentrates",
  "scs 40 for alkaline degreasers",
  "iso 9001 scs 40 manufacturer",
  "iso certified scs 40 supplier india",
  "reach registered scs 40 supplier",
  "tsca compliant scs 40 supplier",
  "halal scs 40 supplier",
  "kosher scs 40 supplier",
  "msme scs 40 manufacturer india",
  "scs 40 sgs inspection supplier",
  "scs 40 bv inspection supplier",
  "scs 40 intertek inspection supplier",
  "scs 40 coa supplier india",
  "scs 40 tds supplier india",
  "scs 40 sds supplier india",
  "scs 40 batch traceability supplier",
  "scs 40 fcl shipping india",
  "scs 40 lcl shipping india",
  "scs 40 air freight",
  "scs 40 sea freight",
  "scs 40 bulk export india",
  "scs 40 export documentation",
  "scs 40 hs code supplier",
  "scs 40 hs code 29041090 supplier",
  "scs 40 ready stock india",
  "scs 40 fast delivery india",
  "scs 40 24/7 support supplier",
  "scs 40 technical service supplier",
  "scs 40 formulation support india",
];

export const SCS_40_RESEARCH_BASED: string[] = [
  "sodium cumene sulfonate cas no",
  "sodium cumene sulfonate cas number",
  "sodium cumene sulfonate cas 28348-53-0",
  "sodium cumene sulfonate 40 cas no",
  "sodium cumene sulfonate 40 cas number",
  "sodium cumene sulphonate cas number",
  "scs 40 cas number",
  "scs 40 cas no",
  "scs 40 cas 28348-53-0",
  "sodium cumene sulfonate einecs number",
  "sodium cumene sulfonate einecs 248-983-7",
  "sodium cumene sulfonate ec number",
  "sodium cumene sulfonate alternate cas 32073-22-6",
  "sodium cumene sulfonate chemical formula",
  "sodium cumene sulfonate molecular formula",
  "sodium cumene sulfonate molecular formula c9h11nao3s",
  "sodium cumene sulfonate molecular weight",
  "sodium cumene sulfonate molecular weight 222.24",
  "sodium cumene sulfonate structure",
  "sodium cumene sulfonate structural formula",
  "sodium cumene sulfonate smiles",
  "sodium cumene sulfonate inchi",
  "sodium cumene sulfonate inchi key",
  "sodium cumene sulfonate inchi key qekatqbvvazoay",
  "sodium cumene sulfonate iupac name",
  "sodium cumene sulfonate iupac name sodium 4-(propan-2-yl)benzenesulfonate",
  "sodium cumene sulfonate mdl number",
  "sodium cumene sulfonate mdl mfcd00007408",
  "sodium cumene sulfonate unii",
  "sodium cumene sulfonate unii q6nn81yxv4",
  "sodium cumene sulfonate cosing reference",
  "sodium cumene sulfonate cosing 79388",
  "sodium cumene sulfonate pubchem",
  "sodium cumene sulfonate pubchem cid",
  "sodium cumene sulfonate chemicalbook",
  "sodium cumene sulfonate chemicalbook cb8506326",
  "sodium cumene sulfonate epa registry",
  "sodium cumene sulfonate hsdb reference",
  "sodium cumene sulfonate synonyms",
  "sodium cumene sulfonate synonyms list",
  "sodium cumene sulfonate other names",
  "sodium cumene sulfonate alternate names",
  "sodium cumene sulfonate trade names",
  "sodium cumene sulfonate vs sodium cumenesulfonate",
  "sodium cumene sulfonate vs sodium cumenesulphonate",
  "sodium isopropylbenzenesulfonate cas",
  "sodium 4-isopropylbenzenesulfonate cas",
  "sodium p-cumenesulfonate cas",
  "cumenesulfonic acid sodium salt cas",
  "isopropylbenzenesulfonic acid sodium salt cas",
  "benzenesulfonic acid 1-methylethyl sodium salt cas",
  "sodium cumene sulfonate uses",
  "sodium cumene sulfonate 40 uses",
  "sodium cumene sulfonate uses in detergent",
  "sodium cumene sulfonate uses in shampoo",
  "sodium cumene sulfonate uses in dish wash",
  "sodium cumene sulfonate uses in laundry liquid",
  "sodium cumene sulfonate uses in personal care",
  "sodium cumene sulfonate uses in agrochemicals",
  "sodium cumene sulfonate uses in oil and gas",
  "sodium cumene sulfonate uses in metalworking",
  "sodium cumene sulfonate uses in electroplating",
  "sodium cumene sulfonate uses in textile",
  "sodium cumene sulfonate uses in paints",
  "sodium cumene sulfonate uses in printing inks",
  "sodium cumene sulfonate uses in industrial cleaners",
  "sodium cumene sulfonate uses in hard surface cleaners",
  "sodium cumene sulfonate uses in alkaline degreasers",
  "sodium cumene sulfonate uses in floor strippers",
  "sodium cumene sulfonate uses in wax cleaners",
  "sodium cumene sulfonate applications",
  "sodium cumene sulfonate applications list",
  "sodium cumene sulfonate industrial applications",
  "sodium cumene sulfonate hydrotrope applications",
  "sodium cumene sulfonate coupling agent applications",
  "scs 40 uses",
  "scs 40 applications",
  "scs 40 hydrotrope applications",
  "scs 40 in detergent formulation",
  "scs 40 in dish wash formulation",
  "scs 40 in laundry liquid formulation",
  "scs 40 in shampoo formulation",
  "scs 40 in body wash formulation",
  "scs 40 in floor cleaner formulation",
  "scs 40 in agrochemical formulation",
  "scs 40 in drilling fluid",
  "scs 40 in oil well stimulation",
  "scs 40 in cementing aid",
  "scs 40 in metal cleaning bath",
  "scs 40 in electroplating bath",
  "scs 40 in zinc plating brightener",
  "how sodium cumene sulfonate works",
  "how scs 40 works",
  "how does sodium cumene sulfonate solubilise surfactants",
  "sodium cumene sulfonate hydrotrope mechanism",
  "sodium cumene sulfonate coupling agent mechanism",
  "sodium cumene sulfonate cloud point depression mechanism",
  "sodium cumene sulfonate viscosity reduction mechanism",
  "sodium cumene sulfonate solubilisation mechanism",
  "sodium cumene sulfonate amphiphilic structure",
  "sodium cumene sulfonate hydrophobic part",
  "sodium cumene sulfonate hydrophilic part",
  "sodium cumene sulfonate aggregation behaviour",
  "sodium cumene sulfonate krafft point",
  "sodium cumene sulfonate cmc",
  "sodium cumene sulfonate compatibility with anionic surfactants",
  "sodium cumene sulfonate compatibility with nonionic surfactants",
  "sodium cumene sulfonate compatibility with amphoteric surfactants",
  "sodium cumene sulfonate compatibility with cationic conditioners",
  "sodium cumene sulfonate impact on surfactant cmc",
  "sodium cumene sulfonate impact on micelle structure",
  "scs 40 vs sxs 40",
  "scs 40 vs scs 90",
  "sodium cumene sulfonate vs sodium xylene sulfonate",
  "sodium cumene sulfonate vs sodium toluene sulfonate",
  "scs vs sxs vs sts hydrotrope comparison",
  "scs 40 vs urea hydrotrope",
  "scs 40 vs sodium octyl sulfate",
  "scs 40 vs disodium octyl sulfosuccinate",
  "scs 40 vs sodium benzene sulfonate",
  "scs 40 vs eltesol sc 40",
  "scs 40 vs stepanate scs",
  "scs 40 vs naxonate sc",
  "scs 40 vs witconate scs",
  "scs 40 vs calsoft scs",
  "scs 40 vs ultrawet scs",
  "scs 40 vs teric 12a3n",
  "scs 40 vs scsdol 40",
  "scs 40 vs neosol 40",
  "scs 40 vs unisurf sc 40",
  "scs 40 vs mahanol scs-40",
  "scs 40 vs nln-scs 40",
  "scs 40 advantages over sxs 40",
  "scs 40 disadvantages",
  "scs 40 vs sxs 40 in nonionic systems",
  "scs 40 vs sxs 40 in alkaline cleaners",
  "scs 40 vs sxs 40 freight cost comparison",
  "scs 40 vs scs 90 freight cost comparison",
  "scs 40 vs scs 90 active matter comparison",
  "liquid hydrotrope vs powder hydrotrope comparison",
  "sodium cumene sulfonate physical properties",
  "sodium cumene sulfonate chemical properties",
  "sodium cumene sulfonate appearance",
  "sodium cumene sulfonate color",
  "sodium cumene sulfonate odor",
  "sodium cumene sulfonate density",
  "sodium cumene sulfonate specific gravity",
  "sodium cumene sulfonate specific gravity 25c",
  "sodium cumene sulfonate refractive index",
  "sodium cumene sulfonate boiling point",
  "sodium cumene sulfonate boiling point 549c",
  "sodium cumene sulfonate melting point",
  "sodium cumene sulfonate melting point greater than 300c",
  "sodium cumene sulfonate freezing point",
  "sodium cumene sulfonate flash point",
  "sodium cumene sulfonate flash point greater than 100c",
  "sodium cumene sulfonate viscosity",
  "sodium cumene sulfonate viscosity at 25c",
  "sodium cumene sulfonate vapor pressure",
  "sodium cumene sulfonate vapor density",
  "sodium cumene sulfonate water solubility",
  "sodium cumene sulfonate water solubility 634 g per L",
  "sodium cumene sulfonate solubility in oil",
  "sodium cumene sulfonate solubility in solvents",
  "sodium cumene sulfonate solubility in dmso",
  "sodium cumene sulfonate ph",
  "sodium cumene sulfonate ph as supplied",
  "sodium cumene sulfonate ph 7 to 10",
  "sodium cumene sulfonate pka",
  "sodium cumene sulfonate pka 2",
  "sodium cumene sulfonate logp",
  "sodium cumene sulfonate logp -1.5",
  "sodium cumene sulfonate log pow",
  "sodium cumene sulfonate surface tension",
  "sodium cumene sulfonate surface tension 29 dyn cm",
  "sodium cumene sulfonate active matter",
  "sodium cumene sulfonate active content",
  "sodium cumene sulfonate 40 active content 39 to 41",
  "sodium cumene sulfonate sulfate content",
  "sodium cumene sulfonate sulfate less than 1 percent",
  "sodium cumene sulfonate sulfone content",
  "sodium cumene sulfonate moisture content",
  "sodium cumene sulfonate cloud point",
  "sodium cumene sulfonate cloud point less than 0c",
  "sodium cumene sulfonate spec sheet",
  "sodium cumene sulfonate technical specifications",
  "sodium cumene sulfonate typical specifications",
  "sodium cumene sulfonate msds",
  "sodium cumene sulfonate msds pdf",
  "sodium cumene sulfonate msds download",
  "sodium cumene sulfonate sds",
  "sodium cumene sulfonate sds pdf",
  "sodium cumene sulfonate sds download",
  "sodium cumene sulfonate safety data sheet",
  "sodium cumene sulfonate tds",
  "sodium cumene sulfonate technical data sheet",
  "sodium cumene sulfonate coa",
  "sodium cumene sulfonate certificate of analysis",
  "sodium cumene sulfonate hazard classification",
  "sodium cumene sulfonate ghs classification",
  "sodium cumene sulfonate ghs07 hazard",
  "sodium cumene sulfonate signal word warning",
  "sodium cumene sulfonate h315",
  "sodium cumene sulfonate h319",
  "sodium cumene sulfonate hazard statements",
  "sodium cumene sulfonate precautionary statements",
  "sodium cumene sulfonate first aid measures",
  "sodium cumene sulfonate firefighting measures",
  "sodium cumene sulfonate accidental release measures",
  "sodium cumene sulfonate handling and storage",
  "sodium cumene sulfonate storage conditions",
  "sodium cumene sulfonate storage temperature",
  "sodium cumene sulfonate shelf life",
  "sodium cumene sulfonate shelf life 24 months",
  "sodium cumene sulfonate exposure controls",
  "sodium cumene sulfonate ppe requirements",
  "sodium cumene sulfonate toxicity data",
  "sodium cumene sulfonate acute toxicity",
  "sodium cumene sulfonate ld50",
  "sodium cumene sulfonate skin sensitization",
  "sodium cumene sulfonate ecotoxicity",
  "sodium cumene sulfonate aquatic toxicity",
  "sodium cumene sulfonate biodegradability",
  "sodium cumene sulfonate biodegradable oecd 301b",
  "sodium cumene sulfonate readily biodegradable",
  "sodium cumene sulfonate reach registration",
  "sodium cumene sulfonate reach status",
  "sodium cumene sulfonate tsca status",
  "sodium cumene sulfonate dsl canada",
  "sodium cumene sulfonate encs japan",
  "sodium cumene sulfonate aics australia",
  "sodium cumene sulfonate iecsc china",
  "sodium cumene sulfonate keci korea",
  "sodium cumene sulfonate k-reach status",
  "sodium cumene sulfonate echa registration",
  "sodium cumene sulfonate echa substance information",
  "sodium cumene sulfonate transport information",
  "sodium cumene sulfonate un number",
  "sodium cumene sulfonate hs code 29041090",
  "sodium cumene sulfonate non hazardous transport",
  "sodium cumene sulfonate imdg classification",
  "sodium cumene sulfonate adr classification",
  "scs 40 dosage in liquid detergent",
  "scs 40 dosage in dish wash",
  "scs 40 dosage in laundry liquid",
  "scs 40 dosage in shampoo",
  "scs 40 dosage 1 to 8 percent",
  "scs 40 typical use level",
  "scs 40 starting dose detergent",
  "scs 40 addition order in detergent",
  "scs 40 cold blend procedure",
  "scs 40 hot blend procedure",
  "scs 40 dissolution procedure",
  "scs 40 mixing procedure",
  "scs 40 temperature sensitivity",
  "scs 40 ph compatibility",
  "scs 40 electrolyte tolerance",
  "scs 40 foam control",
  "scs 40 phase stability",
  "scs 40 storage stability test",
  "scs 40 freeze thaw stability",
  "scs 40 long term storage stability",
  "scs 40 packaging compatibility hdpe",
  "scs 40 packaging compatibility ibc",
  "scs 40 compatibility with builders",
  "scs 40 compatibility with chelants",
  "scs 40 compatibility with edta",
  "scs 40 compatibility with citrate",
  "scs 40 compatibility with sodium silicate",
  "scs 40 compatibility with sodium hydroxide",
  "scs 40 compatibility with fragrances",
  "scs 40 compatibility with dyes",
  "scs 40 compatibility with preservatives",
  "scs 40 compatibility with active ingredients",
  "sodium cumene sulfonate manufacturing process",
  "sodium cumene sulfonate production process",
  "sodium cumene sulfonate synthesis route",
  "sodium cumene sulfonate synthesis from cumene",
  "sodium cumene sulfonate raw materials",
  "sodium cumene sulfonate sulfonation step",
  "sodium cumene sulfonate neutralisation step",
  "sodium cumene sulfonate post-processing",
  "sodium cumene sulfonate production cost analysis",
  "sodium cumene sulfonate global market size",
  "sodium cumene sulfonate global market report",
  "sodium cumene sulfonate market size 2026",
  "sodium cumene sulfonate market growth rate",
  "sodium cumene sulfonate demand forecast",
  "sodium cumene sulfonate supply chain analysis",
  "sodium cumene sulfonate import export india",
  "sodium cumene sulfonate hs code import data",
  "sodium cumene sulfonate price trend",
  "sodium cumene sulfonate price forecast 2027",
  "sodium cumene sulfonate market share india",
  "sodium cumene sulfonate top manufacturers global",
  "sodium cumene sulfonate top suppliers india",
  "sodium cumene sulfonate competitive landscape",
  "sodium cumene sulfonate market drivers",
  "sodium cumene sulfonate market restraints",
  "sodium cumene sulfonate market opportunities",
  "hydrotrope global market size",
  "hydrotrope global market 2026",
  "scs 40 iso 9001 standards",
  "scs 40 astm test methods",
  "scs 40 oecd sids hydrotropes 2005",
  "scs 40 quality standards",
  "scs 40 qa qc parameters",
  "scs 40 impurity profile",
  "scs 40 stability study results",
  "scs 40 long term stability data",
  "scs 40 green chemistry",
  "scs 40 sustainable hydrotrope",
  "scs 40 life cycle assessment",
  "scs 40 carbon footprint",
  "scs 40 biodegradation profile",
  "scs 40 eco-friendly alternative",
  "scs 40 sulfate-free formulations",
  "scs 40 sulfone-free formulations",
  "sodium cumene sulfonate scientific literature",
  "sodium cumene sulfonate white paper",
  "sodium cumene sulfonate research paper",
  "sodium cumene sulfonate review article",
  "sodium cumene sulfonate ashland brochure",
  "sodium cumene sulfonate stepan tds",
  "sodium cumene sulfonate stepan sds pdf",
  "sodium cumene sulfonate ulprospector data",
  "sodium cumene sulfonate sigma aldrich data",
  "sodium cumene sulfonate aldrich 94904",
  "sodium cumene sulfonate sigma 243078",
  "sodium cumene sulfonate chemicalbook compound info",
  "sodium cumene sulfonate cymitquimica info",
  "sodium cumene sulfonate parchem info",
  "sodium cumene sulfonate dataintelo report",
  "eltesol sc 40 specification",
  "eltesol sc 40 composition",
  "eltesol sc 40 uses",
  "eltesol sc 40 vs scs 40",
  "stepanate scs 40 specification",
  "stepanate scs 40 vs scs 40",
  "naxonate sc specification",
  "naxonate sc vs scs 40",
  "witconate scs specification",
  "calsoft scs specification",
  "scsdol-40 specification",
  "scsdol-40 vs scs 40",
  "neosol 40 specification",
  "neosol 40 vs scs 40",
  "mahanol scs-40 specification",
  "nln-scs 40 specification",
  "unisurf sc 40 specification",
  "kk india scs 40 specification",
  "ariix sodium cumene sulfonate specification",
  "navdeep scs-40 specification",
  "nandadeep scs specification",
  "dolphin pharma scsdol-40 specification",
];

export const SCS_40_PRIMARY_KEYWORD: string = "sodium cumene sulfonate 40% manufacturer India";

export const SCS_40_LONG_TAIL_KEYWORDS: string[] = [
  "buy sodium cumene sulfonate 40%",
  "buy sodium cumene sulfonate 40 liquid",
  "buy SCS 40% bulk",
  "buy SCS-40 industrial grade",
  "purchase sodium cumene sulfonate 40%",
  "order sodium cumene sulfonate 40%",
  "sodium cumene sulfonate 40 for sale",
  "sodium cumene sulfonate 40% online order",
  "sodium cumene sulfonate 40 wholesale purchase",
  "sodium cumene sulfonate 40 bulk order",
  "sodium cumene sulfonate 40 drum purchase",
  "sodium cumene sulfonate 40 IBC purchase",
  "sodium cumene sulfonate 40 tanker order",
  "sodium cumene sulfonate 40 sample request",
  "sodium cumene sulfonate 40 trial order",
  "sodium cumene sulfonate 40 direct factory order",
  "buy liquid hydrotrope SCS 40",
  "buy sodium cumene sulphonate 40 liquid",
  "order SCS 40 hydrotrope India",
  "sodium cumene sulfonate 40 procurement",
  "sodium cumene sulfonate 40 B2B purchase",
  "sodium cumene sulfonate 40 industrial buyer enquiry",
  "sodium cumene sulfonate 40 quick quote",
  "sodium cumene sulfonate 40 container load",
  "sodium cumene sulfonate 40 spot purchase",
  "sodium cumene sulfonate 40% supplier",
  "sodium cumene sulfonate 40% supplier India",
  "sodium cumene sulfonate 40% manufacturer",
  "sodium cumene sulfonate 40% manufacturer India",
  "sodium cumene sulfonate 40% manufacturer Gujarat",
  "sodium cumene sulfonate 40% manufacturer Ahmedabad",
  "sodium cumene sulfonate 40% exporter",
  "sodium cumene sulfonate 40% exporter India",
  "SCS 40% supplier Gujarat",
  "SCS 40% manufacturer India",
  "SCS 40% exporter Mumbai",
  "bulk SCS 40 supplier India",
  "SCS 40 wholesale supplier",
  "sodium cumene sulfonate 40 distributor",
  "sodium cumene sulfonate 40 trading company India",
  "sodium cumene sulfonate 40 OEM supplier",
  "sodium cumene sulfonate 40 private label manufacturer",
  "sodium cumene sulfonate 40 contract manufacturer",
  "sodium cumene sulfonate 40 toll manufacturer",
  "sodium cumene sulfonate 40 ISO certified supplier",
  "SCS 40 factory direct India",
  "sodium cumene sulfonate 40 trusted supplier",
  "sodium cumene sulfonate 40 reliable manufacturer",
  "sodium cumene sulfonate 40 verified supplier",
  "sodium cumene sulfonate 40 GMP manufacturer",
  "sodium cumene sulfonate 40% exporter UAE",
  "sodium cumene sulfonate 40% supplier Saudi Arabia",
  "sodium cumene sulfonate 40% exporter Southeast Asia",
  "sodium cumene sulfonate 40% supplier Africa",
  "sodium cumene sulfonate 40% exporter Egypt",
  "sodium cumene sulfonate 40% price",
  "sodium cumene sulfonate 40% price per kg",
  "sodium cumene sulfonate 40 price per ton",
  "sodium cumene sulfonate 40 price India",
  "sodium cumene sulfonate 40 market price",
  "sodium cumene sulfonate 40 CIF price",
  "sodium cumene sulfonate 40 FOB Mundra",
  "sodium cumene sulfonate 40 FOB Nhava Sheva",
  "sodium cumene sulfonate 40 ex-works Ahmedabad",
  "sodium cumene sulfonate 40 wholesale rate",
  "sodium cumene sulfonate 40 bulk rate",
  "sodium cumene sulfonate 40 best price India",
  "sodium cumene sulfonate 40 lowest price supplier",
  "sodium cumene sulfonate 40 competitive quote",
  "sodium cumene sulfonate 40 price list 2026",
  "SCS 40 rate today India",
  "SCS 40 price trend 2026",
  "sodium cumene sulfonate 40 MOQ price",
  "sodium cumene sulfonate 40 minimum order quantity",
  "sodium cumene sulfonate 40 container price",
  "sodium cumene sulfonate 40 LCL rate",
  "sodium cumene sulfonate 40 FCL rate",
  "sodium cumene sulfonate 40 per kg USD",
  "sodium cumene sulfonate 40 dollar price",
  "sodium cumene sulfonate 40 INR rate",
  "sodium cumene sulfonate 40 yearly contract price",
  "sodium cumene sulfonate 40 long term supply agreement",
  "sodium cumene sulfonate 40 monthly supply contract",
  "sodium cumene sulfonate 40 trader price India",
  "sodium cumene sulfonate 40 export price",
  "sodium cumene sulfonate 40 supplier UAE",
  "sodium cumene sulfonate 40 supplier Dubai",
  "sodium cumene sulfonate 40 supplier Saudi Arabia",
  "sodium cumene sulfonate 40 supplier Egypt",
  "sodium cumene sulfonate 40 supplier Oman",
  "sodium cumene sulfonate 40 supplier Qatar",
  "sodium cumene sulfonate 40 supplier Kuwait",
  "sodium cumene sulfonate 40 supplier Turkey",
  "sodium cumene sulfonate 40 supplier Iran",
  "sodium cumene sulfonate 40 supplier Iraq",
  "sodium cumene sulfonate 40 supplier Jordan",
  "sodium cumene sulfonate 40 supplier Bangladesh",
  "sodium cumene sulfonate 40 supplier Sri Lanka",
  "sodium cumene sulfonate 40 supplier Vietnam",
  "sodium cumene sulfonate 40 supplier Thailand",
  "sodium cumene sulfonate 40 supplier Indonesia",
  "sodium cumene sulfonate 40 supplier Malaysia",
  "sodium cumene sulfonate 40 supplier Philippines",
  "sodium cumene sulfonate 40 supplier Nigeria",
  "sodium cumene sulfonate 40 supplier Kenya",
  "sodium cumene sulfonate 40 supplier South Africa",
  "sodium cumene sulfonate 40 supplier Brazil",
  "sodium cumene sulfonate 40 supplier USA",
  "sodium cumene sulfonate 40 supplier Germany",
  "sodium cumene sulfonate 40 supplier UK",
  "sodium cumene sulfonate 40 CIF Jebel Ali",
  "sodium cumene sulfonate 40 CIF Houston",
  "sodium cumene sulfonate 40 CIF Santos",
  "sodium cumene sulfonate 40 CIF Alexandria",
  "sodium cumene sulfonate 40 CIF Dammam",
  "sodium cumene sulfonate 40 CIF Laem Chabang",
  "sodium cumene sulfonate 40 export India to UAE",
  "sodium cumene sulfonate 40 export India to Saudi Arabia",
  "sodium cumene sulfonate 40 export India to Africa",
  "sodium cumene sulfonate 40 import Middle East",
  "sodium cumene sulfonate 40 240 kg drum supplier",
  "sodium cumene sulfonate 40 1000 kg IBC",
  "sodium cumene sulfonate 40 ISO tank supply",
  "sodium cumene sulfonate 40 HDPE drum packing",
  "sodium cumene sulfonate 40 flexi tank export",
  "sodium cumene sulfonate 40 sample 1 kg supplier",
  "sodium cumene sulfonate 40 technical grade supplier",
  "sodium cumene sulfonate 40 detergent grade supplier",
  "sodium cumene sulfonate 40 cosmetic grade supplier",
  "sodium cumene sulfonate 40 private label detergent grade",
  "sodium cumene sulfonate 40 COA supplier",
  "sodium cumene sulfonate 40 MSDS supplier",
  "sodium cumene sulfonate 40 SDS available",
  "sodium cumene sulfonate 40 tech data sheet download",
  "sodium cumene sulfonate 40 REACH registered supplier",
  "dolphin pharma SCS 40 alternative",
  "ariix sodium cumene sulfonate 40 alternative",
  "nandadeep SCS 40 alternative",
  "navdeep SCS-40 alternative",
  "nolan chemicals SCS liquid alternative",
  "marine chemicals SCS 40 alternative",
  "stepan cumene sulfonate alternative",
  "eltesol CS alternative India",
  "witcolate SE-5 alternative",
  "rhodacal CS 40 alternative",
  "cdb 40 alternative supplier",
  "colatrope cs-40 alternative",
  "norfox cs-40 alternative",
  "nansa SS-40 alternative India",
  "huntsman hydrotrope alternative",
  "what is sodium cumene sulfonate 40",
  "sodium cumene sulfonate 40 definition",
  "sodium cumene sulfonate 40 chemical structure",
  "sodium cumene sulfonate 40 molecular formula",
  "sodium cumene sulfonate C9H11NaO3S",
  "sodium cumene sulfonate IUPAC name",
  "sodium 4-isopropylbenzenesulfonate",
  "sodium p-cumene sulfonate structure",
  "sodium cumene sulfonate synonyms",
  "sodium cumene sulfonate other names",
  "what does sodium cumene sulfonate do",
  "is sodium cumene sulfonate a surfactant",
  "is sodium cumene sulfonate a hydrotrope",
  "is sodium cumene sulfonate safe",
  "sodium cumene sulfonate 40 overview",
  "sodium cumene sulfonate benzenesulfonic acid sodium salt",
  "sodium cumene sulphonate meaning",
  "SCS hydrotrope explained",
  "sodium cumene sulfonate vs sodium xylene sulfonate",
  "sodium cumene sulfonate CAS 28348-53-0 description",
  "sodium cumene sulfonate 40 molecular weight",
  "sodium cumene sulfonate molecular weight g/mol",
  "sodium cumene sulfonate pH value",
  "sodium cumene sulfonate 40 pH range",
  "sodium cumene sulfonate density",
  "sodium cumene sulfonate specific gravity",
  "sodium cumene sulfonate solubility in water",
  "sodium cumene sulfonate solubility ethanol",
  "sodium cumene sulfonate HLB value",
  "sodium cumene sulfonate appearance liquid",
  "sodium cumene sulfonate 40 color",
  "sodium cumene sulfonate 40 viscosity",
  "sodium cumene sulfonate 40 freezing point",
  "sodium cumene sulfonate 40 flash point",
  "sodium cumene sulfonate 40 cloud point",
  "sodium cumene sulfonate 40 boiling point",
  "sodium cumene sulfonate 40 stability",
  "sodium cumene sulfonate biodegradability",
  "sodium cumene sulfonate 40 active matter test",
  "sodium cumene sulfonate 40 free sulfate content",
  "sodium cumene sulfonate 40 sulfone content",
  "sodium cumene sulfonate 40 sodium sulfate by-product",
  "sodium cumene sulfonate 40 water content",
  "sodium cumene sulfonate 40 ionic charge",
  "sodium cumene sulfonate 40 CMC value",
  "sodium cumene sulfonate 40 surface tension",
  "sodium cumene sulfonate 40 foaming property",
  "sodium cumene sulfonate 40 electrolyte tolerance",
  "sodium cumene sulfonate 40 thermal stability",
  "sodium cumene sulfonate 40 hard water compatibility",
  "sodium cumene sulfonate 40 freeze-thaw stability",
  "sodium cumene sulfonate 40 shelf life",
  "sodium cumene sulfonate 40 storage conditions",
  "sodium cumene sulfonate 40 packaging specifications",
  "sodium cumene sulfonate 40 typical COA",
  "how to use sodium cumene sulfonate in detergent",
  "sodium cumene sulfonate dosage detergent formulation",
  "sodium cumene sulfonate role as hydrotrope",
  "sodium cumene sulfonate as coupling agent",
  "sodium cumene sulfonate as solubilizer",
  "sodium cumene sulfonate cloud point reduction",
  "sodium cumene sulfonate viscosity reduction liquid detergent",
  "sodium cumene sulfonate in dishwash liquid formulation",
  "sodium cumene sulfonate in laundry liquid formulation",
  "sodium cumene sulfonate in floor cleaner formulation",
  "sodium cumene sulfonate in hand wash formulation",
  "sodium cumene sulfonate in shampoo formulation",
  "sodium cumene sulfonate in body wash formulation",
  "sodium cumene sulfonate with SLES formulation",
  "sodium cumene sulfonate with LABSA",
  "sodium cumene sulfonate with cocamide DEA",
  "sodium cumene sulfonate compatibility sodium chloride",
  "sodium cumene sulfonate nonionic surfactant compatibility",
  "sodium cumene sulfonate in heavy duty cleaners",
  "sodium cumene sulfonate in degreasers",
  "sodium cumene sulfonate in bathroom cleaner",
  "sodium cumene sulfonate in toilet bowl cleaner",
  "sodium cumene sulfonate agrochemical adjuvant",
  "sodium cumene sulfonate pesticide formulation",
  "sodium cumene sulfonate herbicide wetting agent",
  "sodium cumene sulfonate textile auxiliary use",
  "sodium cumene sulfonate textile dyeing auxiliary",
  "sodium cumene sulfonate leather wetting agent",
  "sodium cumene sulfonate paper pulp processing",
  "sodium cumene sulfonate electroplating additive",
  "sodium cumene sulfonate metal cleaner application",
  "sodium cumene sulfonate oilfield drilling fluid use",
  "sodium cumene sulfonate EOR formulation",
  "sodium cumene sulfonate carpet shampoo use",
  "sodium cumene sulfonate in liquid alkaline cleaner",
  "sodium cumene sulfonate typical concentration detergent",
  "sodium cumene sulfonate 1-10% formulation dosage",
  "sodium cumene sulfonate formulation guidelines",
  "sodium cumene sulfonate anti-caking effect",
  "sodium cumene sulfonate effect on foam profile",
  "sodium cumene sulfonate MSDS",
  "sodium cumene sulfonate safety data sheet PDF",
  "sodium cumene sulfonate SDS download",
  "sodium cumene sulfonate GHS classification",
  "sodium cumene sulfonate hazard pictogram",
  "sodium cumene sulfonate signal word",
  "sodium cumene sulfonate toxicity LD50",
  "sodium cumene sulfonate skin irritation",
  "sodium cumene sulfonate eye irritation",
  "sodium cumene sulfonate first aid measures",
  "sodium cumene sulfonate storage handling",
  "sodium cumene sulfonate PPE requirements",
  "sodium cumene sulfonate spill cleanup",
  "sodium cumene sulfonate REACH registration",
  "sodium cumene sulfonate TSCA listing",
  "sodium cumene sulfonate IECSC China inventory",
  "sodium cumene sulfonate DSL Canada",
  "sodium cumene sulfonate AICS Australia",
  "sodium cumene sulfonate ECHA dossier",
  "sodium cumene sulfonate cosmetic ingredient INCI",
  "sodium cumene sulfonate vs sodium xylene sulfonate detergent",
  "sodium cumene sulfonate 40 vs 90 selection guide",
  "SCS vs SXS for liquid detergent",
  "SCS vs sodium toluene sulfonate",
  "sodium cumene sulfonate vs urea hydrotrope",
  "sodium cumene sulfonate vs glycerin solubilizer",
  "sodium cumene sulfonate vs sodium octyl sulfate",
  "SCS vs propylene glycol hydrotrope",
  "sodium cumene sulfonate vs sodium lauryl sulfate",
  "which hydrotrope is best for detergent",
  "SCS vs ethanol as solubilizer",
  "SCS 40 vs SCS 90 selection",
  "SCS vs TKPP hydrotrope",
  "SCS vs alkyl polyglucoside",
  "liquid hydrotrope comparison SCS SXS STS",
  "sodium cumene sulfonate market size 2026",
  "global hydrotrope market forecast",
  "SCS demand liquid detergent market",
  "hydrotrope industry growth rate",
  "India hydrotrope market size",
  "SCS production capacity India",
  "sodium cumene sulfonate manufacturer list India",
  "SCS pricing trend last 5 years",
  "sodium cumene sulfonate export data India",
  "India hydrotrope HS code 340290",
  "CAS 28348-53-0",
  "EC 248-983-7",
  "sodium isopropylbenzene sulfonate 40",
  "sodium 1-methylethylbenzenesulfonate",
  "benzenesulfonic acid 1-methylethyl sodium salt",
  "cumenesulfonic acid sodium salt",
  "sodium p-isopropyl benzene sulfonate",
  "NaCS hydrotrope chemical",
  "sodium cumol sulfonate",
  "sodium isopropylphenyl sulfonate",
];
