/**
 * Keywords database for sodium-xylene-sulfonate-90.
 * Generated automatically.
 */

export const SXS_90_PRIMARY_KEYWORD: string = "sodium xylene sulfonate 90% manufacturer india";

export const SXS_90_LONG_TAIL_KEYWORDS: string[] = [
  "buy sodium xylene sulfonate 90%",
  "buy sodium xylene sulfonate 90 powder",
  "buy SXS 90% bulk",
  "buy SXS-90 industrial grade",
  "purchase sodium xylene sulfonate 90%",
  "order sodium xylene sulfonate 90%",
  "sodium xylene sulfonate 90 for sale",
  "sodium xylene sulfonate 90% online order",
  "sodium xylene sulfonate 90 wholesale purchase",
  "sodium xylene sulfonate 90 bulk order",
  "sodium xylene sulfonate 90 25 kg bag order",
  "sodium xylene sulfonate 90 bag purchase",
  "sodium xylene sulfonate 90 container order",
  "sodium xylene sulfonate 90 sample request",
  "sodium xylene sulfonate 90 trial order",
  "sodium xylene sulfonate 90 direct factory buy",
  "buy powder hydrotrope SXS 90",
  "buy sodium xylene sulphonate 90 powder",
  "order SXS 90 hydrotrope India",
  "sodium xylene sulfonate 90 procurement",
  "sodium xylene sulfonate 90 B2B order",
  "sodium xylene sulfonate 90 FCL order",
  "sodium xylene sulfonate 90 LCL order",
  "sodium xylene sulfonate 90 spot purchase",
  "sodium xylene sulfonate 90 annual contract",
  "sodium xylene sulfonate 90% supplier",
  "sodium xylene sulfonate 90% supplier India",
  "sodium xylene sulfonate 90% manufacturer",
  "sodium xylene sulfonate 90% manufacturer India",
  "sodium xylene sulfonate 90% manufacturer Gujarat",
  "sodium xylene sulfonate 90% manufacturer Ahmedabad",
  "sodium xylene sulfonate 90% exporter",
  "sodium xylene sulfonate 90% exporter India",
  "SXS 90% supplier Gujarat",
  "SXS 90% manufacturer India",
  "SXS 90% exporter Mumbai",
  "bulk SXS 90 supplier India",
  "SXS 90 wholesale supplier",
  "sodium xylene sulfonate 90 distributor",
  "sodium xylene sulfonate 90 trading company",
  "sodium xylene sulfonate 90 OEM supplier",
  "sodium xylene sulfonate 90 private label powder",
  "sodium xylene sulfonate 90 contract manufacturer",
  "sodium xylene sulfonate 90 toll manufacturer",
  "sodium xylene sulfonate 90 ISO certified supplier",
  "SXS 90 factory direct India",
  "sodium xylene sulfonate 90 powder supplier verified",
  "sodium xylene sulfonate 90 trusted manufacturer",
  "sodium xylene sulfonate 90 GMP manufacturer",
  "sodium xylene sulfonate 90 powder exporter",
  "sodium xylene sulfonate 90 exporter UAE",
  "sodium xylene sulfonate 90 supplier Saudi Arabia",
  "sodium xylene sulfonate 90 exporter Southeast Asia",
  "sodium xylene sulfonate 90 supplier Africa",
  "sodium xylene sulfonate 90 exporter Europe",
  "sodium xylene sulfonate 90% price",
  "sodium xylene sulfonate 90% price per kg",
  "sodium xylene sulfonate 90 price per ton",
  "sodium xylene sulfonate 90 price India",
  "sodium xylene sulfonate 90 powder price",
  "sodium xylene sulfonate 90 market price",
  "sodium xylene sulfonate 90 CIF price",
  "sodium xylene sulfonate 90 FOB Mundra",
  "sodium xylene sulfonate 90 FOB Nhava Sheva",
  "sodium xylene sulfonate 90 ex-works Ahmedabad",
  "sodium xylene sulfonate 90 wholesale rate",
  "sodium xylene sulfonate 90 bulk rate",
  "sodium xylene sulfonate 90 best price India",
  "sodium xylene sulfonate 90 lowest price supplier",
  "sodium xylene sulfonate 90 competitive quote",
  "sodium xylene sulfonate 90 price list 2026",
  "SXS 90 rate today India",
  "SXS 90 price trend 2026",
  "sodium xylene sulfonate 90 MOQ price",
  "sodium xylene sulfonate 90 minimum order quantity",
  "sodium xylene sulfonate 90 container price",
  "sodium xylene sulfonate 90 FCL rate",
  "sodium xylene sulfonate 90 per kg USD",
  "sodium xylene sulfonate 90 dollar price",
  "sodium xylene sulfonate 90 INR rate",
  "sodium xylene sulfonate 90 yearly contract",
  "sodium xylene sulfonate 90 long term supply",
  "sodium xylene sulfonate 90 monthly supply",
  "sodium xylene sulfonate 90 trader price",
  "sodium xylene sulfonate 90 export price",
  "sodium xylene sulfonate 90 supplier UAE",
  "sodium xylene sulfonate 90 supplier Dubai",
  "sodium xylene sulfonate 90 supplier Saudi Arabia",
  "sodium xylene sulfonate 90 supplier Egypt",
  "sodium xylene sulfonate 90 supplier Oman",
  "sodium xylene sulfonate 90 supplier Qatar",
  "sodium xylene sulfonate 90 supplier Kuwait",
  "sodium xylene sulfonate 90 supplier Turkey",
  "sodium xylene sulfonate 90 supplier Iran",
  "sodium xylene sulfonate 90 supplier Iraq",
  "sodium xylene sulfonate 90 supplier Jordan",
  "sodium xylene sulfonate 90 supplier Bangladesh",
  "sodium xylene sulfonate 90 supplier Sri Lanka",
  "sodium xylene sulfonate 90 supplier Vietnam",
  "sodium xylene sulfonate 90 supplier Thailand",
  "sodium xylene sulfonate 90 supplier Indonesia",
  "sodium xylene sulfonate 90 supplier Malaysia",
  "sodium xylene sulfonate 90 supplier Philippines",
  "sodium xylene sulfonate 90 supplier Nigeria",
  "sodium xylene sulfonate 90 supplier Kenya",
  "sodium xylene sulfonate 90 supplier South Africa",
  "sodium xylene sulfonate 90 supplier Brazil",
  "sodium xylene sulfonate 90 supplier USA",
  "sodium xylene sulfonate 90 supplier Germany",
  "sodium xylene sulfonate 90 supplier UK",
  "sodium xylene sulfonate 90 CIF Jebel Ali",
  "sodium xylene sulfonate 90 CIF Houston",
  "sodium xylene sulfonate 90 CIF Santos",
  "sodium xylene sulfonate 90 CIF Alexandria",
  "sodium xylene sulfonate 90 CIF Dammam",
  "sodium xylene sulfonate 90 CIF Laem Chabang",
  "sodium xylene sulfonate 90 export India to UAE",
  "sodium xylene sulfonate 90 export India to Saudi Arabia",
  "sodium xylene sulfonate 90 export India to Africa",
  "sodium xylene sulfonate 90 import Middle East",
  "sodium xylene sulfonate 90 25 kg bag supplier",
  "sodium xylene sulfonate 90 15 kg bag",
  "sodium xylene sulfonate 90 HDPE woven bag",
  "sodium xylene sulfonate 90 jumbo bag 500 kg",
  "sodium xylene sulfonate 90 jumbo bag 1000 kg",
  "sodium xylene sulfonate 90 super sack supplier",
  "sodium xylene sulfonate 90 sample 1 kg",
  "sodium xylene sulfonate 90 technical grade",
  "sodium xylene sulfonate 90 detergent grade",
  "sodium xylene sulfonate 90 cosmetic grade",
  "sodium xylene sulfonate 90 private label",
  "sodium xylene sulfonate 90 COA supplier",
  "sodium xylene sulfonate 90 MSDS supplier",
  "sodium xylene sulfonate 90 tech data sheet",
  "sodium xylene sulfonate 90 REACH registered supplier",
  "stepanate SXS-90 alternative",
  "rhodacal sxs-90 alternative",
  "eltesol SX-90 alternative",
  "nansa SXS-90 alternative",
  "witconate SXS-90 alternative",
  "dolphin pharma SXS 90 alternative",
  "ariix sodium xylene sulfonate 90 alternative",
  "nandadeep SXS 90 alternative",
  "navdeep SXS-90 alternative",
  "nolan chemicals SXS 90 alternative",
  "marine chemicals SXS 90 alternative",
  "stepan powder SXS alternative",
  "huntsman SXS 90 powder alternative",
  "solvay sxs 90 alternative",
  "ineos SXS powder alternative",
  "what is sodium xylene sulfonate 90",
  "sodium xylene sulfonate 90 definition",
  "sodium xylene sulfonate 90 chemical structure",
  "sodium xylene sulfonate 90 molecular formula",
  "sodium xylene sulfonate powder C8H9NaO3S",
  "sodium xylene sulfonate IUPAC name",
  "sodium dimethylbenzenesulfonate 90",
  "sodium xylene sulfonate powder synonyms",
  "sodium xylene sulfonate powder other names",
  "what does sodium xylene sulfonate 90 do",
  "is sodium xylene sulfonate 90 a surfactant",
  "is sodium xylene sulfonate 90 a hydrotrope",
  "is sodium xylene sulfonate 90 safe",
  "sodium xylene sulfonate 90 overview",
  "SXS 90 hydrotrope explained",
  "sodium xylene sulfonate 90 description",
  "sodium xylene sulfonate powder meaning",
  "sodium xylene sulfonate concentrate 90",
  "sodium xylene sulfonate 90 vs liquid form",
  "sodium xylene sulfonate 90 CAS 1300-72-7",
  "sodium xylene sulfonate 90 molecular weight",
  "sodium xylene sulfonate 90 density",
  "sodium xylene sulfonate 90 bulk density",
  "sodium xylene sulfonate 90 tapped density",
  "sodium xylene sulfonate 90 particle size",
  "sodium xylene sulfonate 90 mesh size",
  "sodium xylene sulfonate 90 moisture content",
  "sodium xylene sulfonate 90 loss on drying",
  "sodium xylene sulfonate 90 appearance white powder",
  "sodium xylene sulfonate 90 off-white powder",
  "sodium xylene sulfonate 90 color",
  "sodium xylene sulfonate 90 odor",
  "sodium xylene sulfonate 90 pH 1% solution",
  "sodium xylene sulfonate 90 pH 10% solution",
  "sodium xylene sulfonate 90 solubility water",
  "sodium xylene sulfonate 90 solubility ethanol",
  "sodium xylene sulfonate 90 HLB value",
  "sodium xylene sulfonate 90 hygroscopicity",
  "sodium xylene sulfonate 90 melting point",
  "sodium xylene sulfonate 90 flash point",
  "sodium xylene sulfonate 90 thermal stability",
  "sodium xylene sulfonate 90 decomposition temperature",
  "sodium xylene sulfonate 90 biodegradability",
  "sodium xylene sulfonate 90 active matter",
  "sodium xylene sulfonate 90 assay",
  "sodium xylene sulfonate 90 free sulfate",
  "sodium xylene sulfonate 90 sulfone content",
  "sodium xylene sulfonate 90 sodium sulfate impurity",
  "sodium xylene sulfonate 90 surface tension",
  "sodium xylene sulfonate 90 CMC value",
  "sodium xylene sulfonate 90 electrolyte tolerance",
  "sodium xylene sulfonate 90 hard water tolerance",
  "sodium xylene sulfonate 90 foaming property",
  "sodium xylene sulfonate 90 shelf life",
  "sodium xylene sulfonate 90 storage conditions",
  "how to use sodium xylene sulfonate 90 in powder detergent",
  "sodium xylene sulfonate 90 dosage powder detergent",
  "sodium xylene sulfonate 90 role powder formulation",
  "sodium xylene sulfonate 90 anti-caking effect",
  "sodium xylene sulfonate 90 as coupling agent",
  "sodium xylene sulfonate 90 as solubilizer concentrate",
  "sodium xylene sulfonate 90 in spray dried detergent",
  "sodium xylene sulfonate 90 in zeolite detergent",
  "sodium xylene sulfonate 90 in compact tablet",
  "sodium xylene sulfonate 90 in single dose capsule",
  "sodium xylene sulfonate 90 in detergent bar",
  "sodium xylene sulfonate 90 in dishwash powder",
  "sodium xylene sulfonate 90 in automatic dishwasher",
  "sodium xylene sulfonate 90 in laundry powder",
  "sodium xylene sulfonate 90 in industrial powder cleaner",
  "sodium xylene sulfonate 90 in car wash concentrate",
  "sodium xylene sulfonate 90 in degreaser concentrate",
  "sodium xylene sulfonate 90 in shampoo concentrate",
  "sodium xylene sulfonate 90 in syndet bar",
  "sodium xylene sulfonate 90 with LABSA powder",
  "sodium xylene sulfonate 90 with zeolite compatibility",
  "sodium xylene sulfonate 90 with sodium carbonate",
  "sodium xylene sulfonate 90 agrochemical wettable powder",
  "sodium xylene sulfonate 90 pesticide WP formulation",
  "sodium xylene sulfonate 90 herbicide wettable powder",
  "sodium xylene sulfonate 90 textile processing",
  "sodium xylene sulfonate 90 leather processing",
  "sodium xylene sulfonate 90 paper industry",
  "sodium xylene sulfonate 90 electroplating",
  "sodium xylene sulfonate 90 metal processing",
  "sodium xylene sulfonate 90 oilfield EOR powder",
  "sodium xylene sulfonate 90 drilling fluid additive",
  "sodium xylene sulfonate 90 carpet shampoo powder",
  "sodium xylene sulfonate 90 concentrated cleaner",
  "sodium xylene sulfonate 90 typical formulation 2-8%",
  "sodium xylene sulfonate 90 dissolve rate water",
  "sodium xylene sulfonate 90 blend with STPP",
  "sodium xylene sulfonate 90 blend sodium silicate",
  "sodium xylene sulfonate 90 blend nonionic",
  "sodium xylene sulfonate 90 for high-solid detergent",
  "sodium xylene sulfonate 90 MSDS",
  "sodium xylene sulfonate 90 SDS PDF",
  "sodium xylene sulfonate 90 GHS classification",
  "sodium xylene sulfonate 90 hazard statement",
  "sodium xylene sulfonate 90 toxicity LD50",
  "sodium xylene sulfonate 90 skin irritation",
  "sodium xylene sulfonate 90 eye irritation",
  "sodium xylene sulfonate 90 inhalation hazard dust",
  "sodium xylene sulfonate 90 first aid",
  "sodium xylene sulfonate 90 PPE requirement",
  "sodium xylene sulfonate 90 storage temperature",
  "sodium xylene sulfonate 90 spill management",
  "sodium xylene sulfonate 90 disposal",
  "sodium xylene sulfonate 90 REACH status",
  "sodium xylene sulfonate 90 TSCA compliance",
  "sodium xylene sulfonate 90 IECSC China",
  "sodium xylene sulfonate 90 DSL Canada",
  "sodium xylene sulfonate 90 AICS Australia",
  "sodium xylene sulfonate 90 ECHA registration",
  "sodium xylene sulfonate INCI cosmetic name",
  "sodium xylene sulfonate 90 vs 40",
  "SXS 90 vs SCS 90",
  "sodium xylene sulfonate 90 vs sodium cumene sulfonate 90",
  "SXS 90 vs sodium toluene sulfonate 90",
  "SXS 90 powder vs SXS 40 liquid selection",
  "SXS 90 vs sodium octyl sulfate",
  "SXS 90 vs urea hydrotrope",
  "SXS 90 vs propylene glycol powder",
  "SXS 90 vs alkyl polyglucoside powder",
  "SXS 90 vs TKPP anti-caking",
  "SXS 90 vs sodium sulfate carrier",
  "SXS 90 concentrated vs liquid form",
  "SXS 90 powder vs granule",
  "SXS 90 vs SCS 90 cloud point",
  "SXS 90 vs noodle detergent mix",
  "sodium xylene sulfonate 90 market size",
  "SXS 90 powder market forecast India",
  "global hydrotrope powder market",
  "SXS 90 demand powder detergent",
  "India powder hydrotrope market",
  "SXS 90 production capacity India",
  "sodium xylene sulfonate 90 manufacturer list India",
  "SXS 90 pricing trend historical",
  "SXS 90 export data India HS 340290",
  "powder hydrotrope industry growth",
  "CAS 1300-72-7 powder",
  "EC 215-090-9 sodium xylene sulfonate",
  "sodium dimethylbenzenesulfonate powder",
  "dimethylbenzenesulfonic acid sodium salt powder",
  "sodium xylene sulphonate CAS powder",
  "xylenesulfonic acid sodium salt powder",
  "sodium xylene sulfonate mixed isomers powder",
  "sodium 2,4-xylene sulfonate powder",
  "sodium m-xylene sulfonate powder",
  "sodium p-xylene sulfonate powder",
];
