/**
 * Keywords database for sodium-xylene-sulfonate-40.
 * Generated automatically.
 */

export const SXS_40_PRIMARY_KEYWORD: string = "sodium xylene sulfonate 40% manufacturer india";

export const SXS_40_LONG_TAIL_KEYWORDS: string[] = [
  "buy sodium xylene sulfonate 40%",
  "buy sodium xylene sulfonate 40 liquid",
  "buy SXS 40% bulk",
  "buy SXS-40 industrial grade",
  "purchase sodium xylene sulfonate 40%",
  "order sodium xylene sulfonate 40%",
  "sodium xylene sulfonate 40 for sale",
  "sodium xylene sulfonate 40% online order",
  "sodium xylene sulfonate 40 wholesale purchase",
  "sodium xylene sulfonate 40 bulk order",
  "sodium xylene sulfonate 40 drum purchase",
  "sodium xylene sulfonate 40 IBC purchase",
  "sodium xylene sulfonate 40 tanker order",
  "sodium xylene sulfonate 40 sample request",
  "sodium xylene sulfonate 40 trial order",
  "sodium xylene sulfonate 40 direct factory",
  "buy liquid hydrotrope SXS 40",
  "buy sodium xylene sulphonate 40 liquid",
  "order SXS 40 hydrotrope India",
  "sodium xylene sulfonate 40 procurement",
  "sodium xylene sulfonate 40 B2B order",
  "sodium xylene sulfonate 40 industrial buyer enquiry",
  "sodium xylene sulfonate 40 quick quote",
  "sodium xylene sulfonate 40 container load",
  "sodium xylene sulfonate 40 spot purchase",
  "sodium xylene sulfonate 40% supplier",
  "sodium xylene sulfonate 40% supplier India",
  "sodium xylene sulfonate 40% manufacturer",
  "sodium xylene sulfonate 40% manufacturer India",
  "sodium xylene sulfonate 40% manufacturer Gujarat",
  "sodium xylene sulfonate 40% manufacturer Ahmedabad",
  "sodium xylene sulfonate 40% exporter",
  "sodium xylene sulfonate 40% exporter India",
  "SXS 40% supplier Gujarat",
  "SXS 40% manufacturer India",
  "SXS 40% exporter Mumbai",
  "bulk SXS 40 supplier India",
  "SXS 40 wholesale supplier",
  "sodium xylene sulfonate 40 distributor",
  "sodium xylene sulfonate 40 trading company",
  "sodium xylene sulfonate 40 OEM supplier",
  "sodium xylene sulfonate 40 private label manufacturer",
  "sodium xylene sulfonate 40 contract manufacturer",
  "sodium xylene sulfonate 40 toll manufacturer",
  "sodium xylene sulfonate 40 ISO certified supplier",
  "SXS 40 factory direct India",
  "sodium xylene sulfonate 40 trusted supplier",
  "sodium xylene sulfonate 40 reliable manufacturer",
  "sodium xylene sulfonate 40 verified supplier",
  "sodium xylene sulfonate 40 GMP manufacturer",
  "sodium xylene sulfonate 40% exporter UAE",
  "sodium xylene sulfonate 40% supplier Saudi Arabia",
  "sodium xylene sulfonate 40% exporter Southeast Asia",
  "sodium xylene sulfonate 40% supplier Africa",
  "sodium xylene sulfonate 40% exporter Egypt",
  "sodium xylene sulfonate 40% price",
  "sodium xylene sulfonate 40% price per kg",
  "sodium xylene sulfonate 40 price per ton",
  "sodium xylene sulfonate 40 price India",
  "sodium xylene sulfonate 40 market price",
  "sodium xylene sulfonate 40 CIF price",
  "sodium xylene sulfonate 40 FOB Mundra",
  "sodium xylene sulfonate 40 FOB Nhava Sheva",
  "sodium xylene sulfonate 40 ex-works Ahmedabad",
  "sodium xylene sulfonate 40 wholesale rate",
  "sodium xylene sulfonate 40 bulk rate",
  "sodium xylene sulfonate 40 best price India",
  "sodium xylene sulfonate 40 lowest price supplier",
  "sodium xylene sulfonate 40 competitive quote",
  "sodium xylene sulfonate 40 price list 2026",
  "SXS 40 rate today India",
  "SXS 40 price trend 2026",
  "sodium xylene sulfonate 40 MOQ price",
  "sodium xylene sulfonate 40 minimum order quantity",
  "sodium xylene sulfonate 40 container price",
  "sodium xylene sulfonate 40 LCL rate",
  "sodium xylene sulfonate 40 FCL rate",
  "sodium xylene sulfonate 40 per kg USD",
  "sodium xylene sulfonate 40 dollar price",
  "sodium xylene sulfonate 40 INR rate",
  "sodium xylene sulfonate 40 yearly contract price",
  "sodium xylene sulfonate 40 long term price",
  "sodium xylene sulfonate 40 monthly supply contract",
  "sodium xylene sulfonate 40 trader price",
  "sodium xylene sulfonate 40 export price",
  "sodium xylene sulfonate 40 supplier UAE",
  "sodium xylene sulfonate 40 supplier Dubai",
  "sodium xylene sulfonate 40 supplier Saudi Arabia",
  "sodium xylene sulfonate 40 supplier Egypt",
  "sodium xylene sulfonate 40 supplier Oman",
  "sodium xylene sulfonate 40 supplier Qatar",
  "sodium xylene sulfonate 40 supplier Kuwait",
  "sodium xylene sulfonate 40 supplier Turkey",
  "sodium xylene sulfonate 40 supplier Iran",
  "sodium xylene sulfonate 40 supplier Iraq",
  "sodium xylene sulfonate 40 supplier Jordan",
  "sodium xylene sulfonate 40 supplier Bangladesh",
  "sodium xylene sulfonate 40 supplier Sri Lanka",
  "sodium xylene sulfonate 40 supplier Vietnam",
  "sodium xylene sulfonate 40 supplier Thailand",
  "sodium xylene sulfonate 40 supplier Indonesia",
  "sodium xylene sulfonate 40 supplier Malaysia",
  "sodium xylene sulfonate 40 supplier Philippines",
  "sodium xylene sulfonate 40 supplier Nigeria",
  "sodium xylene sulfonate 40 supplier Kenya",
  "sodium xylene sulfonate 40 supplier South Africa",
  "sodium xylene sulfonate 40 supplier Brazil",
  "sodium xylene sulfonate 40 supplier USA",
  "sodium xylene sulfonate 40 supplier Germany",
  "sodium xylene sulfonate 40 supplier UK",
  "sodium xylene sulfonate 40 CIF Jebel Ali",
  "sodium xylene sulfonate 40 CIF Houston",
  "sodium xylene sulfonate 40 CIF Santos",
  "sodium xylene sulfonate 40 CIF Alexandria",
  "sodium xylene sulfonate 40 CIF Dammam",
  "sodium xylene sulfonate 40 CIF Laem Chabang",
  "sodium xylene sulfonate 40 export India to UAE",
  "sodium xylene sulfonate 40 export India to Saudi Arabia",
  "sodium xylene sulfonate 40 export India to Africa",
  "sodium xylene sulfonate 40 import Middle East",
  "sodium xylene sulfonate 40 240 kg drum",
  "sodium xylene sulfonate 40 1000 kg IBC",
  "sodium xylene sulfonate 40 ISO tank supply",
  "sodium xylene sulfonate 40 HDPE drum",
  "sodium xylene sulfonate 40 flexi tank export",
  "sodium xylene sulfonate 40 sample supplier",
  "sodium xylene sulfonate 40 technical grade",
  "sodium xylene sulfonate 40 detergent grade",
  "sodium xylene sulfonate 40 cosmetic grade",
  "sodium xylene sulfonate 40 private label",
  "sodium xylene sulfonate 40 COA supplier",
  "sodium xylene sulfonate 40 MSDS supplier",
  "sodium xylene sulfonate 40 SDS download",
  "sodium xylene sulfonate 40 tech data sheet",
  "sodium xylene sulfonate 40 REACH compliant supplier",
  "stepanate SXS-40 alternative",
  "rhodacal sxs-40 alternative",
  "eltesol SX-40 alternative",
  "nansa HS-90 SXS alternative",
  "witconate SXS-40 alternative",
  "dolphin pharma SXS 40 alternative",
  "ariix sodium xylene sulfonate alternative",
  "nandadeep SXS 40 alternative",
  "navdeep SXS-40 alternative",
  "nolan chemicals SXS 40 alternative",
  "marine chemicals SXS 40 alternative",
  "stepan sxs-40 alternative India",
  "huntsman SXS 40 alternative",
  "solvay sxs 40 alternative",
  "ineos SXS alternative supplier",
  "what is sodium xylene sulfonate 40",
  "sodium xylene sulfonate 40 definition",
  "sodium xylene sulfonate 40 chemical structure",
  "sodium xylene sulfonate 40 molecular formula",
  "sodium xylene sulfonate C8H9NaO3S",
  "sodium xylene sulfonate IUPAC name",
  "sodium dimethylbenzenesulfonate 40",
  "sodium xylene sulfonate synonyms",
  "sodium xylene sulphonate other names",
  "what does sodium xylene sulfonate do",
  "is sodium xylene sulfonate a surfactant",
  "is sodium xylene sulfonate a hydrotrope",
  "is sodium xylene sulfonate safe",
  "sodium xylene sulfonate 40 overview",
  "sodium xylene sulfonate 40 application basics",
  "SXS hydrotrope explained",
  "sodium xylene sulphonate meaning",
  "sodium xylene sulfonate vs sodium cumene sulfonate",
  "sodium xylene sulfonate 40 CAS 1300-72-7",
  "sodium xylene sulfonate mixed isomers definition",
  "sodium xylene sulfonate 40 molecular weight",
  "sodium xylene sulfonate 40 density",
  "sodium xylene sulfonate 40 specific gravity",
  "sodium xylene sulfonate 40 pH value",
  "sodium xylene sulfonate 40 pH range",
  "sodium xylene sulfonate 40 solubility water",
  "sodium xylene sulfonate 40 solubility ethanol",
  "sodium xylene sulfonate 40 HLB value",
  "sodium xylene sulfonate 40 appearance liquid",
  "sodium xylene sulfonate 40 color clear",
  "sodium xylene sulfonate 40 clear light yellow",
  "sodium xylene sulfonate 40 viscosity",
  "sodium xylene sulfonate 40 freezing point",
  "sodium xylene sulfonate 40 flash point",
  "sodium xylene sulfonate 40 cloud point",
  "sodium xylene sulfonate 40 boiling point",
  "sodium xylene sulfonate 40 stability",
  "sodium xylene sulfonate biodegradability",
  "sodium xylene sulfonate 40 active matter test",
  "sodium xylene sulfonate 40 free sulfate",
  "sodium xylene sulfonate 40 sulfone content",
  "sodium xylene sulfonate 40 sodium sulfate impurity",
  "sodium xylene sulfonate 40 water content",
  "sodium xylene sulfonate 40 ionic charge anionic",
  "sodium xylene sulfonate 40 CMC",
  "sodium xylene sulfonate 40 surface tension",
  "sodium xylene sulfonate 40 foam performance",
  "sodium xylene sulfonate 40 electrolyte tolerance",
  "sodium xylene sulfonate 40 thermal stability",
  "sodium xylene sulfonate 40 hard water compatibility",
  "sodium xylene sulfonate 40 freeze-thaw stability",
  "sodium xylene sulfonate 40 shelf life",
  "sodium xylene sulfonate 40 storage conditions",
  "sodium xylene sulfonate 40 packaging specifications",
  "sodium xylene sulfonate 40 typical COA",
  "how to use sodium xylene sulfonate 40 in detergent",
  "sodium xylene sulfonate 40 dosage detergent formulation",
  "sodium xylene sulfonate 40 role as hydrotrope",
  "sodium xylene sulfonate 40 as coupling agent",
  "sodium xylene sulfonate 40 as solubilizer",
  "sodium xylene sulfonate 40 cloud point depressant",
  "sodium xylene sulfonate 40 viscosity reducer liquid detergent",
  "sodium xylene sulfonate 40 in dishwash liquid",
  "sodium xylene sulfonate 40 in laundry liquid",
  "sodium xylene sulfonate 40 in floor cleaner",
  "sodium xylene sulfonate 40 in hand wash",
  "sodium xylene sulfonate 40 in shampoo",
  "sodium xylene sulfonate 40 in body wash",
  "sodium xylene sulfonate 40 with SLES",
  "sodium xylene sulfonate 40 with LABSA",
  "sodium xylene sulfonate 40 with cocamide DEA",
  "sodium xylene sulfonate 40 salt tolerance",
  "sodium xylene sulfonate 40 with nonionic surfactant",
  "sodium xylene sulfonate 40 heavy duty cleaner",
  "sodium xylene sulfonate 40 degreaser formulation",
  "sodium xylene sulfonate 40 bathroom cleaner",
  "sodium xylene sulfonate 40 toilet bowl cleaner",
  "sodium xylene sulfonate 40 agrochemical adjuvant",
  "sodium xylene sulfonate 40 pesticide formulation",
  "sodium xylene sulfonate 40 herbicide wetting",
  "sodium xylene sulfonate 40 textile dyeing",
  "sodium xylene sulfonate 40 leather wetting",
  "sodium xylene sulfonate 40 paper pulp",
  "sodium xylene sulfonate 40 electroplating",
  "sodium xylene sulfonate 40 metal cleaner",
  "sodium xylene sulfonate 40 oilfield drilling fluid",
  "sodium xylene sulfonate 40 EOR formulation",
  "sodium xylene sulfonate 40 carpet shampoo",
  "sodium xylene sulfonate 40 alkaline cleaner",
  "sodium xylene sulfonate 40 acidic cleaner",
  "sodium xylene sulfonate 40 concentration detergent",
  "sodium xylene sulfonate 40 2-10% formulation",
  "sodium xylene sulfonate 40 formulation guidelines",
  "sodium xylene sulfonate 40 wax stripper formulation",
  "sodium xylene sulfonate 40 sanitizer formulation",
  "sodium xylene sulfonate 40 MSDS",
  "sodium xylene sulfonate 40 SDS PDF",
  "sodium xylene sulfonate 40 GHS classification",
  "sodium xylene sulfonate 40 hazard statement",
  "sodium xylene sulfonate 40 signal word",
  "sodium xylene sulfonate 40 toxicity LD50",
  "sodium xylene sulfonate 40 skin irritation",
  "sodium xylene sulfonate 40 eye irritation",
  "sodium xylene sulfonate 40 first aid",
  "sodium xylene sulfonate 40 storage handling",
  "sodium xylene sulfonate 40 PPE",
  "sodium xylene sulfonate 40 spill cleanup",
  "sodium xylene sulfonate 40 disposal",
  "sodium xylene sulfonate 40 REACH registration",
  "sodium xylene sulfonate 40 TSCA listing",
  "sodium xylene sulfonate 40 IECSC China",
  "sodium xylene sulfonate 40 DSL Canada",
  "sodium xylene sulfonate 40 AICS Australia",
  "sodium xylene sulfonate 40 ECHA dossier",
  "sodium xylene sulfonate INCI cosmetic",
  "sodium xylene sulfonate vs sodium cumene sulfonate",
  "sodium xylene sulfonate 40 vs 90",
  "SXS vs SCS for liquid detergent",
  "SXS vs sodium toluene sulfonate",
  "sodium xylene sulfonate vs urea hydrotrope",
  "sodium xylene sulfonate vs glycerin",
  "sodium xylene sulfonate vs sodium octyl sulfate",
  "SXS vs propylene glycol",
  "sodium xylene sulfonate vs sodium lauryl sulfate",
  "which hydrotrope is better SCS or SXS",
  "SXS vs ethanol solubilizer",
  "SXS 40 vs SXS 90 selection",
  "SXS vs TKPP hydrotrope",
  "SXS vs alkyl polyglucoside",
  "liquid hydrotrope comparison SXS STS SCS",
  "sodium xylene sulfonate market size 2026",
  "global SXS market forecast",
  "SXS demand detergent liquid",
  "hydrotrope industry growth rate",
  "India SXS market size",
  "SXS production capacity India",
  "sodium xylene sulfonate manufacturer list India",
  "SXS price trend 5 years",
  "sodium xylene sulfonate export India HS 340290",
  "SXS market share vs SCS",
  "CAS 1300-72-7",
  "EC 215-090-9 xylene sulfonate",
  "sodium dimethylbenzenesulfonate",
  "dimethylbenzenesulfonic acid sodium salt",
  "sodium xylene sulphonate CAS",
  "xylenesulfonic acid sodium salt",
  "sodium xylene sulfonate mixed isomers",
  "sodium 2,4-xylene sulfonate",
  "sodium m-xylene sulfonate",
  "sodium p-xylene sulfonate",
];
